Repository flybywiresim/aircraft, pull requests merged in 2020-12, with the labels that each got.

#2149 [CDU] Fix negative default takeoff speeds
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#2121 [CDU] Allow input while message is shown, minor bug fixes and improvements
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Testing Started

#2154 Increase autopilot bank angle
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/systems.cfg
Labels: Autopilot, Ready to Test

#2070 [CDU] Change visuals for constraints on flight plan page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Labels: Tested

#1998 [CDU] Fix CRZ FL unintentionally changed by fcu
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Testing Started, Waiting For Response

#2085 Hotfix qnh flashing
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Labels: Tested

#2092 [CDU] Altitude Constraints Logic recode
  A32NX/html_ui/Pages/A32NX_Core/FMGC/A32NX_ConstraintManager.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
Labels: Testing Started

#2179 [CORE] hotfix gd not visible
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Vspeeds.js
Labels: Tested

#2019 [CDU] Added ATSU ATC Pages
  .husky/pre-commit
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/FINALFLAPS.wav
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Connection.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_ConnectionNotification.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_ConnectionStatus.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_DepartReq.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Emergency.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Menu.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_MessagesRecord.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_PositionReport.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Reports.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Request.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATSU_DatalinkStatus.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATSU_Menu.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_Comm_Menu.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#2182 [PFD] FMA's fix alt magenta on open clb/des
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Labels: Needs Changelog

#2192 [ECAM] Add G LOAD indication to lower ECAM
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXLogic.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.js
Labels: Testing Started

#2194 [PFD] Add vR indication
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
Labels: Ready to Test

#2201 [FBW] Fix ELAC/SEC/FAC Simvars and sidestick animation
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Sidestick.xml
  A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js
Labels: Ready to Test

#2175 [CDU] improvements to scratchpad update on message deletions
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: Testing Started

#2216 Fix to the lateral swaying in cruise
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/ai.cfg
Labels: Extensive Testing Needed, Testing Started

#2218 [ND] Navigration display improvements
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
Labels: Accuracy Checked, Tested

#2214 Update icon for decel point on flightplan in mfd
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/MFD/Images/A32NX_DECEL.png
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/MFD/Images/A32NX_DECEL.svg
  A32NX/html_ui/Pages/VCockpit/Instruments/FlightElements/Waypoint.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: Tested

#2242 TCAS improvements
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Misc.xml
  A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.html
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_TCAS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
Labels: Ready to Test

#2264 [ECAM] Add icing related ECAM warnings and memos
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXLogic.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Ready to Test

#2229 Add default baro unit option
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_BaroSelector.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_Menu.js
Labels: Tested

#2226 [VSpeeds Core] refactor SimVar names and add documentation
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Speeds.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
  docs/a320-simvars.md
Labels: Tested

#2236 Tie Switches/Buttons Local Variables to Animations
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Fire.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
Labels: Tested

#2231 [PFD] switch to core speed calculations
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Speeds.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
Labels: Testing Started

#2278 [CDU] Add missing keyboard delays
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: MCDU, Tested

#2291 make core speed computation an util
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Speeds.js
  A32NX/html_ui/Pages/A32NX_Utils/NXSpeeds.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: Tested

#2271 Flight model update and full landing flaps to 40
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Extensive Testing Needed, Testing Started

#2265 [ECAM] Recall messages automatically if they reappear
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Testing Started

#2287 [CDU] F-PLN page visual rework
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: Tested

#2255 Fix small font on sts page - temporary
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.html
Labels: Tested

#2329 Changed name in repo README to logo
  README.md
Labels: Changes Requested

#2391 [ECAM] Fix some lower ECAM colors
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.js
Labels: Tested

#2304 [FMS] Add ground speed mini
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXSpeeds.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Testing Started

#2251 [CDU] General Bugfixes to INIT and FUEL PRED pages
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Testing Started

#2367 Fix incomplete switch from node-sass
  .github/workflows/pr.yml
  scripts/setup.sh
  src/instruments/rollup.config.js
Labels: Tested

#2277 Fix radio frequencies/squawk not being visible in default forward pedestal view
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cameras.cfg
Labels: Tested

#2286 Fuel tank capacities
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: Accuracy Checked, Tested

#2441 Fix wiper issue
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: Ready to Test

#2419 Add option to switch between KG and LBS
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_Menu.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#2459 Fix SAI not working
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.xml
Labels: Tested

#2456 [CDU] Rework Options Page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MenuPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_ADIRS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_ATIS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_METAR.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_TAF.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_Menu.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_REALISM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js
Labels: Ready to Test

#2468 Fix ND Invisible Airplane Icon
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
Labels: Ready to Test

#2267 Prevent override of altitude in flightplan page
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Labels: Tested

#2405 [ECAM REWRITE] Added SAT and TAT to SD
  src/instruments/src/Common/definitions.scss
  src/instruments/src/SD/StatusArea/StatusArea.jsx
  src/instruments/src/SD/Text/Text.jsx
  src/instruments/src/SD/Text/Text.scss
  src/instruments/src/util.mjs
Labels: Tested

#2470 Add Soft Go-Around Function
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Labels: Ready to Test

#2479 Various fixes/additions to ECAM, FWC, and FMA
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_CIDS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_Menu.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css
Labels: Ready to Test

#2489 [FIX] Retard callout bugs
  A32NX/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Labels: Prioritize for Next Stable Release, Ready to Test

#2398 Increase descent rate at 250 knots below 10,000 feet
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/engines.cfg
Labels: Ready to Test

#2465 [LIGHTS] Small Improvements & Changes
  A32NX/effects/LIGHT_A32NX_LandingLarge.fx
  A32NX/effects/LIGHT_A32NX_TakeOff.fx
  A32NX/effects/LIGHT_A32NX_TaxiLarge.fx
Labels: Tested

#1865 [CDU] INIT Page - OFP Data - SimBrief Integration
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  A32NX/html_ui/Pages/A32NX_Utils/SimBriefApi.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_Init.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_Menu.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_SIMBRIEF.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: Changes Requested, Needs Changelog, Tested

#2496 [CDU] Allow SimBrief user IDs instead of usernames
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  A32NX/html_ui/Pages/A32NX_Utils/SimBriefApi.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_SIMBRIEF.js
Labels: Tested

#2263 Arrival Page Fixes
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
Labels: Tested

#2566 Fix wiper issues
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: Tested

#2527 [ECAM] Improve packs indication
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Tested

#2578 Changed MDA and DH to BARO and RADIO in PERF APRR Page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Labels: MCDU

#2447 [CDU] Fix ascend constraint algorithm
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/FMGC/A32NX_ConstraintManager.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Testing Started

#2589 [CDU] Fix airways showing as undefined
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Labels: Ready to Test

#2593 [CDU] Allow SimBrief OFP to override previous flight plan
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: Ready to Test

#2611 fix: port fuel system changes
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/systems.cfg
Labels: Tested

#2615 [FIX] Broken flap indicator
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Ready to Test

#2621 [MISC] Stop autobrake max disengaging on the ground
  src/behavior/src/A32NX_Interior_Misc.xml
Labels: Tested

#2597 [CDU] Wind page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_WindPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#2584 [CDU] Create definition for currently used messages
  A32NX/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  A32NX/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirportsMonitor.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_HoldAtPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSInit.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MenuPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NavaidPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_WaypointPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_WindPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/AIDS/A320_Neo_CDU_AIDS_Menu.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_FreeText.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_METAR.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_SIMBRIEF.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_CIDS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_REALISM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#2583 Fix outer tank fuel transfer
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: Ready to Test

#2483 [FPD] Add Autobrake to FMA
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
Labels: Tested

#2604 [CDU] Bugfixes to INIT and FUEL PRED pages
  A32NX/html_ui/Pages/A32NX_Core/A32NX_FuelPred.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#2672 refactor: import asobo templates
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
  A32NX/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  A32NX/ModelBehaviorDefs/A32NX/FMC.xml
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  A32NX/ModelBehaviorDefs/Asobo/Airliner/FMC.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: Ready to Test

#2698 Prelim fix for uncontrollable dive
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: Tested

#2555 fix: ND flight plan removed from ROSE VOR/ILS
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css
Labels: Tested

#2722 [PFD] Improve Vfe and Vfen
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Speeds.js
  A32NX/html_ui/Pages/A32NX_Utils/NXSpeeds.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
Labels: Tested

#2755 Proportional Gain of rollPID reverted to default
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/ai.cfg
Labels: Tested

#2461 [ECAM REWRITE] Add doors page
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
  src/instruments/src/Common/definitions.scss
  src/instruments/src/SD/Common/definitions.scss
  src/instruments/src/SD/Pages/Door.jsx
  src/instruments/src/SD/Pages/Door/Door.jsx
  src/instruments/src/SD/Pages/Door/Door.scss
  src/instruments/src/SD/PagesContainer.jsx
  src/instruments/src/SD/StatusArea/StatusArea.jsx
  src/instruments/src/SD/Text/Text.jsx
  src/instruments/src/SD/Text/Text.scss
  src/instruments/src/util.mjs
Labels: Tested

#2778 fix: invalid code in CAB PRESS page
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js
Labels: Tested

#2486 [BUG] fix altitude button setting the speed on atc request
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Request.js
Labels: Tested
