Repository flybywiresim/aircraft, pull requests merged in 2020-11, with the labels that each got.

#1502 Provide modern layout for instruments and port DCDU to react
  .eslintrc.json
  .github/Contributing.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .gitignore
  .vscode/tasks.json
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Misc.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Com/A320_Neo_Com.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Com/A320_Neo_Com.js
  docs/Classes.md
  docs/resources.md
  package-lock.json
  package.json
  src/instruments/.eslintrc.js
  src/instruments/README.md
  src/instruments/rollup.config.js
  src/instruments/src/DCDU/config.json
  src/instruments/src/DCDU/index.jsx
  src/instruments/src/DCDU/style.css
  src/instruments/src/util.mjs
  src/instruments/template/rollup.js
  src/instruments/template/template.html
  src/instruments/template/template.js
Labels: Tested

#1578 Upper ECAM Fixed wrong condition for thrust modes and engine mode START
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Ready to Test

#1604 [PFD] Add proper speed behaviour on approach phase and layout changes.
  .github/CHANGELOG.md
  A32NX/html_ui/CSS/A32NX_Display_Common.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Labels: Tested

#1672 [MCDU/PFD/ND/ECAM] Update colors
  .github/CHANGELOG.md
  A32NX/html_ui/CSS/A32NX_Display_Common.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDCompass.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/HSIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/ILSIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/VerticalSpeedIndicator.js
Labels: Tested

#1750 [FCU] remember selected pressure mode when returning from Std mode
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_FCU.xml
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.js
Labels: Ready to Test

#1650 [ECAM] Throttle lever position and AVAIL message on N1 gauge fix
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Tested

#1740 [PFD] Add altitude constraints visual behavior
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Labels: Tested

#1725 Ported some fuel system changes for Thrustmaster quadrant compatibility
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Misc.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  A32NX/html_ui/Pages/A32NX_Core/A32NX_FADEC.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
Labels: Ready to Test

#1772 [MCDU] Add page identifier and Progress Page OPT and REC MAX functionality
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirportsMonitor.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableFlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_DataIndexPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_GPSMonitor.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_HoldAtPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSInit.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSMonitor.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSStatus.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSStatusFrozen.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IdentPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MenuPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NavaidPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NewWaypoint.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PilotsWaypoint.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PositionFrozen.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PositionMonitorPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_SelectWptPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_SelectedNavaids.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_WaypointPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#1762 fix: braking while taxiing should not turn autobrake off
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Misc.xml
Labels: Tested

#1583 Fix: allow inserting landing QNH in inHg
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#1757 [MCDU] Add functionalities to PROG and PER PAGE, lock INIT page B
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#1843 [CDU] Fix Performance page broken
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#1652 [CDU] Implement proper flight plan data update and DECEL management
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/FlightElements/Waypoint.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: Tested

#1742 GPWS Rework
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/A32NX_Interior_Generics.xml
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Misc.xml
  A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.xml
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_SoundManager.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
Labels: Tested

#1830 [CDU] Add MCDU formatting helpers
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSInit.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: Tested

#1867 [CDU] Fix IRS coordinates always showing N/E
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: Ready to Test

#1868 [CDU] Add location reporting and fix ATC issue
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXApi.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#1875 Fix altitude knob increment/decrement
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_FCU.xml
Labels: Tested

#1845 [CDU] Improve LAT REV page layout
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js
Labels: Ready to Test

#1786 V1/VR/V2 Disagree logic
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#1524 [CDU] Fuel Predictions and Functional Init B
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_FuelPred.js
  A32NX/html_ui/Pages/A32NX_Core/math.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#1715 fix FMA modes for ILS Approach when disconnecting AP. Also add new fl…
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Autopilot.xml
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Labels: Tested

#1896 [PFD] Improve text readability
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/HSIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/VerticalSpeedIndicator.js
Labels: Tested

#1373 ECAM cabin press page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js
Labels: ECAM, Needs System Implementation

#1907 [ND] Improve flight path shape display
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.html
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgFlightPlanElement.js
Labels: Ready to Test

#1597 [CDU] Duplicate waypoint names page rework
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_SelectWptPage.js
Labels: Ready to Test

#1922 [FIX] Wrong GPWS warnings
  A32NX/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Labels: Ready to Test

#1886 [CDU] Fix initial flight phase
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#1812 [ND] Add altitude constraint in flight level (FL) after transition altitude
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.html
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#1944 [CDU] Fix athr targeting flap speed on climb
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#1946 [CDU] Fix dynamic error message shows old scratchpad clear
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#1955 [ECAM] Getter/Setter for cabin temperature
  A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
Labels: Tested

#1950 [FIX] retard callout playing on goaround
  A32NX/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Labels: Tested

#1965 [ECAM] Stop updating the ECAM pages twice
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Testing Started

#1889 [PFD] Add altitude indicator alerts
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Labels: Testing Started

#1972 [CDU] Update the precomputed ZFW/ZFWCG values when weight parameters are changed
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Testing Started

#1975 [CDU] Fix athr still targeting flaps speed
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Testing Started

#1996 Enhance ECAM COND Page
  A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.html
Labels: Tested

#1980 [ND] Add missing altitude constraint symbol
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js
Labels: Tested

#1951 [CDU] Add Type I and Type II Messages
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#1943 [ECAM] Implement FWC flight phases and update ECAM messages
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_FWC.js
  A32NX/html_ui/Pages/A32NX_Utils/NXLogic.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  docs/a320-simvars.md
Labels: Tested

#2016 fix: Flight model changes to fix pitch oscillation (better transitions between flight modes)
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: Tested

#2025 fix(ecam): temporary fix for self test font size
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
Labels: Tested

#2009 [CDU] Add check for destination data, improvements to Type II Messages
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#2014 [CDU] Reduced fuel pred delay and average wind change delay
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Accuracy Checked, Tested

#2062 Fix brake temperature
  A32NX/html_ui/Pages/A32NX_Core/A32NX_BrakeTemp.js
Labels: Tested

#2060 [ND] Add track line to ARC and NAV map mode
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDCompass.js
Labels: Tested

#1985 [CDU] Constraint improvements
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
Labels: Needs Accuracy Check, Tested

#2012 [PFD] Add QNH Flashing when reach transition altitude
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Labels: Accuracy Checked, Tested

#2046 Aircon improvements
  A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js
Labels: Ready to Test

#2029 [ECAM] Improve inhibit and recall behaviour
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_FWC.js
  A32NX/html_ui/Pages/A32NX_Utils/NXLogic.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  docs/a320-simvars.md
Labels: Testing Started

#2076 [CDU] Added constraints symbols logic to flight plan
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: Ready to Test

#2098 Improve ground handling, steering, and suspension
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: Ready to Test

#2107 Attempts to fix AP issue
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
Labels: Autopilot, Tested

#2117 Fix compass spinning wildly
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseNDCompass.js
Labels: Ready to Test

#1580 Improvements to Flightmodel, PFD Speedband and calculations for various speeds
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/engines.cfg
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Vspeeds.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
Labels: Extensive Testing Needed, Needs Accuracy Check, Ready to Test

#2133 Removed MaxBankIndex from apron.flt
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
Labels: Autopilot

#2134 [ND] Fix weather radar not showing after switching to plan view
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
Labels: Tested

#2069 MCDU: scroll fix for F-PLN page
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  docs/README.md
Labels: Tested

#2110 [CDU] Implement airway to airway insertion
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js
Labels: Tested

#2140 Lateral autopilot fix
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/ai.cfg
Labels: Autopilot, Do Not Merge, Extensive Testing Needed
