Repository flybywiresim/aircraft, pull requests merged in 2020-09, with the labels that each got.

#336 Turned off emergency exit signs in cold and dark state.
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
Labels: Tested, True to life

#335 Changed minimum brightness to 0 on all displays
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: Tested, True to life

#322 Improved phase change logic
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/layout.json
Labels: Tested, True to life

#374 Corrected typo in FMA code, fixes error on APPR hold pressed.
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Labels: Tested, bug-a32nx

#270 Set defaults for seatbelt light, FD, and ATC switches
  .gitignore
  A32NX/ModelBehaviorDefs/Asobo/Airliner/AirlinerCommon.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  docs/a320-simvars.md
  docs/i-vars.md
Labels: bug-a32nx, bug-vanilla

#227 Wind Indicator Fix
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/MFD/NDInfo.js
  A32NX/layout.json
Labels: awaiting feedback, bug-vanilla

#423 Adds support for 'G/S*' and 'LOC *' FMA modes, fixes 'THR CLB' appearing when on the ground.
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/ILSIndicator.js
Labels: enhancement, ready to test

#232 Hide BingMap on ND when no weather or terrain
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
Labels: bug-vanilla

#501 Toga engine fix and ecam updates
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/engines.cfg
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: awaiting feedback

#497 Added two captain to cabin crew calls
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/Asobo_A320_NEO_Improved.PC.PCK
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml
  src/sound/.cache/SoundBankInfoCache.dat
  src/sound/.cache/Windows/Plugins/Wwise Convolution Reverb/AE_DistantBuilding_MicsFar_28E70600.wem
  src/sound/.cache/Windows/Plugins/Wwise Convolution Reverb/AE_DistantBuilding_MicsFar_7B6DC981.wem
  src/sound/.cache/Windows/Plugins/Wwise Convolution Reverb/IR_ATR42-600_AT4022_BB01EA9C.wem
  src/sound/.cache/Windows/Plugins/Wwise Convolution Reverb/Wwise.dat
  src/sound/.cache/Windows/SFX/CAPTAIN-CABINCREW-SEATS-FOR-LANDING_1E8ECBBC.wem
  src/sound/.cache/Windows/SFX/CAPTAIN-CABINCREW-SEATS-FOR-LANDING_2_1E8ECBBC.wem
  src/sound/.cache/Windows/SFX/CAPTAIN-CABINCREW-SEATS-FOR-LANDING_3_1E8ECBBC.wem
  src/sound/.cache/Windows/SFX/CAPTAIN-CABINCREW-SEATS-FOR-TAKEOFF_1E8ECBBC.wem
  src/sound/.cache/Windows/SFX/CAPTAIN-CABINCREW-SEATS-FOR-TAKEOFF_2_1E8ECBBC.wem
  src/sound/.cache/Windows/SFX/CAPTAIN-CABINCREW-SEATS-FOR-TAKEOFF_3_1E8ECBBC.wem
  src/sound/.cache/Windows/SFX/Wwise.dat
  src/sound/Actor-Mixer Hierarchy/AIRCRAFTS/AIRCRAFT_WWISEDATA/AIRCRAFT_PLAYER/Asobo_A320_NEO_Improved.wwu
  src/sound/DISCLAIMER.txt
  src/sound/Events/AIRCRAFTS/AIRCRAFT_WWISEDATA/AIRCRAFT_PLAYER/Asobo_A320_NEO_Improved.wwu
  src/sound/FlightSim.olive.validationcache
  src/sound/FlightSim.olive.wsettings
  src/sound/GeneratedSoundBanks/Asobo_A320_NEO_Improved.PC.PCK
  src/sound/GeneratedSoundBanks/Windows/Asobo_A320_NEO_Improved.bnk
  src/sound/GeneratedSoundBanks/Windows/Asobo_A320_NEO_Improved.txt
  src/sound/GeneratedSoundBanks/Windows/Asobo_A320_NEO_Improved.xml
  src/sound/GeneratedSoundBanks/Windows/Init.bnk
  src/sound/GeneratedSoundBanks/Windows/Init.txt
  src/sound/GeneratedSoundBanks/Windows/Init.xml
  src/sound/GeneratedSoundBanks/Windows/PluginInfo.xml
  src/sound/GeneratedSoundBanks/Windows/SoundbanksInfo.xml
  src/sound/GeneratedSoundBanks/Windows/local_soundbank.bnk
  src/sound/GeneratedSoundBanks/Windows/local_soundbank.txt
  src/sound/GeneratedSoundBanks/Windows/local_soundbank.xml
  src/sound/GeneratedSoundBanks/Wwise_IDs.h
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-LANDING.akd
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-LANDING.wav
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-LANDING_2.akd
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-LANDING_2.wav
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-LANDING_3.akd
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-LANDING_3.wav
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-TAKEOFF.akd
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-TAKEOFF.wav
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-TAKEOFF_2.akd
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-TAKEOFF_2.wav
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-TAKEOFF_3.akd
  src/sound/Originals/SFX/CAPTAIN-CABINCREW-SEATS-FOR-TAKEOFF_3.wav
  src/sound/SoundBanks/Asobo_A320_NEO_Improved.wwu
Labels: awaiting feedback

#523 Update A320_Neo_FCU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.html
Labels: awaiting feedback

#582 ECAM status page and engine failures
  A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  A32NX/layout.json
  A32NX/manifest.json
  CODEOWNERS
Labels: ECAM

#652 Fixed flight phase stuck in takeoff
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: ready to test

#587 Fix MCDU green dot speed
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Labels: ready to test

#616 [PFD] Altimeter strip Update (AltimeterIndicator.js)
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Labels: ready to test

#654 SAI/Integrated Standy Instrument Self Test
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js
Labels: ready to test

#676 Fixed new Gally & cab and Commercial push button in ANN Testing
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: ready to test

#675 [MCDU] Fix takeoff speed to V2+10
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: ready to test

#635 Use generic tootl-tips for no smoking light switch
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/en-US.locPak
  A32NX/layout.json
Labels: ready to test

#666 MFD/ND Text position fixes
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
Labels: ND (Navigation Display), changes requested

#749 Brake temp improvements
  A32NX/html_ui/Pages/A32NX_Core/A32NX_BrakeTemp.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js
  docs/a320-simvars.md
Labels: Tested

#695 [CLOCK] Modified date & middle digits displays
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js
Labels: ready to test

#770 port Asobo changes from 1.8.3.0 for PFD Instruments
  A32NX/html_ui/JS/A32NX_Avionics.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/ILSIndicator.js
Labels: ready to test

#753 Engine fan rotation
  A32NX/ModelBehaviorDefs/A32NX/A32NX_Exterior.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO.xml
Labels: enhancement

#710 Added Checklist evaluation for PWS, Seatbelts, Smoking, ADIRS, Emergency Exit Light Switches
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: enhancement, ready to test

#729 feat(bustie): Add animation, sounds, emission and SimVars to Elec pushbuttons
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
Labels: Overhead panel, enhancement

#762 Fix incorrect slat position after 1.8.3
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: needs A320 pilot input, ready to test

#771 Remove manual fix for initial flight director state
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.js
Labels: ready to test

#757 fix(ecam/ewd): do not show REV and thrust limit in reverse
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: ready to test

#769 [STEERING] Changes in rudder steering speeds authority and max steering angle (Update flight_model.cfg)
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: ready to test

#727 [RTPI] Added RTPI modified gauge to the list: removed the -sign
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.js
Labels: enhancement, ready to test

#766 Acceleration altitude should be MSL instead of AGL
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Labels: bug, ready to test

#787 fix s p o o k y brightness knob action 👻
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/systems.cfg
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
Labels: MSFS 1.8.3.0, ready to test

#721 Port MCDU changes from 1.8.3.0
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Labels: MCDU, awaiting feedback, changes requested, ready to test

#701 [ATC] Added background lighting and realistic size (update A320Neo_ATC.css)
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/ATC/A320_Neo_ATC.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/ATC/A320_Neo_ATC.html
Labels: changes requested

#795 Fix #783 Overspeed Warning
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: bug-a32nx, ready to test

#705 [BUGFIX] Prevent ECAM auto page switching when page is selected
  A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
Labels: awaiting feedback, changes requested

#827 [PFD] Fix boxes
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Labels: ready to test

#844 [CDU] Fix airways page after 1.8.3
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js
Labels: MCDU, ready to test

#826 [PFD] Compass ticks
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
Labels: ready to test

#846 Ground cursor improvements
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
Labels: ready to test

#864 make some FMAs have permanent box
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseAirliners.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Labels: ready to test

#875 Fixes G/S* and LAND vertical line on FMA
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/ILSIndicator.js
Labels: ready to test

#916 Improve upper ECAM visuals
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: ready to test

#927 [CDU] Fix a crash when trying to replace a waypoint in the flight plan
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Labels: critical bug

#937 Patch #911 Lower ECAM DOOR Page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.css
Labels: ECAM, True to Life, enhancement

#885 feat: add VOR/DME and ADF for rose VOR/ILS ND mode
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/systems.cfg
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseNDCompass.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDCompass.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDInfo.js
Labels: Ready to Test

#966 Fix broken file references due to 1.9.3.0
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/ATC/A320_Neo_ATC.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.html
Labels: MSFS 1.9.3.0

#960 Fix #957 Battery Indicators
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.js
Labels: Ready to Test
