Repository flybywiresim/aircraft, pull requests merged in 2021-08, with the labels that each got.

#5483 feat(displays): Improve pixelated screens
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/CSS/A32NX_Display_Common.css
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A320_Neo_MFD.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A320_Neo_MFD.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js
  src/instruments/src/Common/displayUnit.tsx
  src/instruments/src/Common/pixels.scss
  src/instruments/src/Common/simVars.tsx
  src/instruments/src/DCDU/index.jsx
  src/instruments/src/DCDU/style.scss
  src/instruments/src/PFD/style.scss
Labels: QA Tier 1

#5513 fix: change external view HUD back to airliner type (SU5 compatibility fix)
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cockpit.cfg
Labels: QA Tier 1

#5122 fix(mcdu): amber coloring for efob values
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
Labels: Needs Accuracy Check, QA Tier 1, Tested

#5219 fix(efb): Upgrade @flybywiresim/react-components to version 0.3.1
  package.json
Labels: Waiting For Response

#5326 feat(efb): make callibration deadzone range bars green when within dead range
  src/instruments/src/EFB/Components/Progress/Progress.scss
  src/instruments/src/EFB/Components/Progress/Progress.tsx
  src/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx
Labels: Tested

#5190 refactor(isis): Convert ISIS to React
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js
  src/behavior/src/A32NX_Interior_ISIS.xml
  src/instruments/src/ISIS/AirplaneSymbol.tsx
  src/instruments/src/ISIS/AirspeedIndicator.tsx
  src/instruments/src/ISIS/AltitudeIndicator.tsx
  src/instruments/src/ISIS/ArtificialHorizon.tsx
  src/instruments/src/ISIS/ArtificialHorizonDisplay.tsx
  src/instruments/src/ISIS/Att10sFlag.tsx
  src/instruments/src/ISIS/AutoBrightness.tsx
  src/instruments/src/ISIS/Bug.ts
  src/instruments/src/ISIS/BugSetupDisplay.tsx
  src/instruments/src/ISIS/DigitalAltitudeIndicator.tsx
  src/instruments/src/ISIS/ISISDisplayUnit.tsx
  src/instruments/src/ISIS/ISISUtils.tsx
  src/instruments/src/ISIS/LandingSystem.tsx
  src/instruments/src/ISIS/MachIndicator.tsx
  src/instruments/src/ISIS/PitchScale.tsx
  src/instruments/src/ISIS/PressureIndicator.tsx
  src/instruments/src/ISIS/RollIndex.tsx
  src/instruments/src/ISIS/RollScale.tsx
  src/instruments/src/ISIS/VerticalTape.tsx
  src/instruments/src/ISIS/config.json
  src/instruments/src/ISIS/index.tsx
  src/instruments/src/ISIS/style.scss
Labels: QA Tier 2

#5626 refactor(pfd): move towards tsx
  src/instruments/src/PFD/AltitudeIndicator.tsx
  src/instruments/src/PFD/AttitudeIndicatorFixed.tsx
  src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
  src/instruments/src/PFD/DigitalAltitudeReadout.tsx
  src/instruments/src/PFD/FMA.tsx
  src/instruments/src/PFD/HeadingIndicator.tsx
  src/instruments/src/PFD/LandingSystemIndicator.tsx
  src/instruments/src/PFD/PFDUtils.tsx
  src/instruments/src/PFD/SpeedIndicator.tsx
  src/instruments/src/PFD/VerticalSpeedIndicator.tsx
  src/instruments/src/PFD/config.json
  src/instruments/src/PFD/index.tsx
  typings/fs-base-ui/html_ui/JS/SimPlane.d.ts
Labels: Tested

#5490 fix: un-mirror sharklet textures
  .github/CHANGELOG.md
  src/model/models.json
Labels: Tested, QA Tier 1

#5624 feat(efb): add power button
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
Labels: Tested

#5665 fix: strobe flashing
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: Lighting, QA Tier 1

#5524 feat(efb): tabbed settings page and new autobrightness option
  .github/CHANGELOG.md
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
  src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
  src/instruments/src/EFB/Settings/sync.ts
Labels: QA Tier 1

#5674 fix: Retard callout at 20 ft with autopilot off
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Labels: QA Tier 1

#5683 fix: CVR GND CTRL
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_Generics.xml
  src/behavior/src/A32NX_Interior_Misc.xml
Labels: True to Life, QA Tier 1

#5329 refactor: (ecam) Convert Fuel page to React
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js
  src/instruments/buildSrc/igniter/tasks.mjs
  src/instruments/src/SD/Common/FuelFunctions.tsx
  src/instruments/src/SD/Common/Shapes.tsx
  src/instruments/src/SD/Pages/Crz/Crz.tsx
  src/instruments/src/SD/Pages/Fuel.jsx
  src/instruments/src/SD/Pages/Fuel/Fuel.scss
  src/instruments/src/SD/Pages/Fuel/Fuel.tsx
  src/instruments/src/SD/Pages/Fuel/config.json
  src/instruments/src/SD/Pages/Hyd/Hyd.tsx
  src/instruments/src/SD/PagesContainer.jsx
Labels: QA Tier 1

#5261 feat(ui): Notifications and Popups
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Core.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_TipsManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_MCDU_KB.js
  src/fbw/src/ThrottleAxisMapping.cpp
  src/fbw/src/ThrottleAxisMapping.h
  src/instruments/src/EFB/Settings/Settings.tsx
  src/instruments/src/EFB/react-app-env.d.ts
  src/shared/src/notification.ts
  src/shared/src/popup.ts
Labels: QA Tier 1

#5688 fix: improve button template api
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_Generics.xml
  src/behavior/src/A32NX_Interior_Misc.xml
Labels: QA Tier 1

#5541 refactor(efb): improvements to code quality and conformance to eslint-config v0.2.0 rules
  src/instruments/src/EFB/ATC/ATC.tsx
  src/instruments/src/EFB/Components/Form/SelectInput/SelectInput.tsx
  src/instruments/src/EFB/Components/Help.tsx
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
  src/instruments/src/EFB/Dispatch/Dispatch.tsx
  src/instruments/src/EFB/Dispatch/Pages/LoadsheetPage.tsx
  src/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Ground/DoorToggle.tsx
  src/instruments/src/EFB/Ground/Ground.tsx
  src/instruments/src/EFB/Navigation/Navigation.tsx
  src/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx
  src/instruments/src/EFB/Performance/Widgets/RunwayVisualizationWidget.tsx
  src/instruments/src/EFB/Service/TODCalculator.ts
  src/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx
  src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
  src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleSimVar.tsx
  src/instruments/src/EFB/Settings/sync.ts
  src/instruments/src/EFB/SimbriefApi/simbriefParser.ts
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/instruments/src/EFB/Store/actions.ts
  src/instruments/src/EFB/Store/index.ts
  src/instruments/src/EFB/TODCalculator/Data/Data.tsx
  src/instruments/src/EFB/ToolBar/ToolBar.tsx
Labels: QA Tier 1

#5699 fix: large performance loss when using vertical speed sync
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/TODCalculator/Data/Data.tsx
Labels: QA Tier 1

#5684 fix: pushback without command
  src/instruments/src/EFB/Ground/Ground.tsx
  src/instruments/src/EFB/Store/action-creator/ground-state.tsx
  src/instruments/src/EFB/Store/actions.ts
  src/instruments/src/EFB/Store/reducer/ground-reducer.tsx
  src/instruments/src/EFB/rollup.development.config.js
Labels: EFB, QA Tier 1

#5741 fix: NXDataStore cannot store numbers
  .github/CHANGELOG.md
  src/.eslintrc.js
  src/instruments/src/Common/displayUnit.tsx
  src/instruments/src/Common/persistence.tsx
  src/instruments/src/EFB/ATC/ATC.tsx
  src/instruments/src/EFB/ChartsApi/Navigraph.tsx
  src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
  src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
  src/instruments/src/EFB/Dispatch/Pages/LoadsheetPage.tsx
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Navigation/Navigation.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
  src/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx
  src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
  src/instruments/src/EFB/Settings/sync.ts
  src/instruments/src/SD/Pages/Crz/Crz.tsx
  src/instruments/src/SD/Pages/Eng/Eng.tsx
  src/instruments/src/SD/Pages/Fuel/Fuel.tsx
  src/shared/src/persistence.ts
Labels: QA Tier 1

#5697 feat: efb power button (physical)
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/instruments/src/EFB/index.tsx
Labels: Waiting For Response
