Repository flybywiresim/aircraft, pull requests merged in 2021-04, with the labels that each got.

#4216 fix: correct fueling rate by using deltaTime
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
Labels: QA Tier 1, Tested

#4280 refactor: remove unused a32nx_core module, improve some LocalVarUpdater functions
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Core.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GroundReference.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
Labels: QA Tier 1, Testing Started

#3959 feat(mcdu): Title line of Progress page displays flight phase
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
Labels: QA Tier 2, Tested

#3545 fix(mcdu): Fix input issues on PERF/W&B and fuel prediction pages
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Please Resolve Conflicts, Tested

#4303 fix: update UI_MANUFACTURER and UI_MODEL in locPak files
  flybywire-aircraft-a320-neo/de-DE.locPak
  flybywire-aircraft-a320-neo/en-US.locPak
  flybywire-aircraft-a320-neo/es-ES.locPak
  flybywire-aircraft-a320-neo/fr-FR.locPak
  flybywire-aircraft-a320-neo/it-IT.locPak
  flybywire-aircraft-a320-neo/pl-PL.locPak
  flybywire-aircraft-a320-neo/pt-BR.locPak
  flybywire-aircraft-a320-neo/ru-RU.locPak
  flybywire-aircraft-a320-neo/zh-CN.locPak
Labels: QA Tier 1, Tested

#4037 fix: MODE SEL manual visual improvements
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js
Labels: Testing Started, True to Life

#4336 fix: wing and runway turnoff lights
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
Labels: QA Tier 1, Ready to Test

#4335 fix(mcdu): limit scratchpad to 22 characters
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: QA Tier 1, Tested

#4329 feat(mcdu): Progress Page line 5R only shows GPS Primary when it is available
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
Labels: QA Tier 1, Tested

#4340 fix(model): cabin clipping into cockpit
  src/model/models.json
Labels: QA Tier 1, Testing Started

#4304 fix(nd): show vor/adf needles on ils rose
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/A32NX_BaseNDCompass.js
Labels: QA Tier 2, Tested

#4305 fix(mcdu): on appr, show temp sign, remove fls/final app
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Labels: QA Tier 1, Tested

#4295 fix(efb): unresponsive buttons and deactivated doors
  src/instruments/src/EFB/Components/Button/Button.tsx
  src/instruments/src/EFB/Ground/DoorToggle.tsx
  src/instruments/src/EFB/Ground/Ground.tsx
Labels: QA Tier 1, Tested

#4210 fix(adirs): delay "on bat" activation
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js
Labels: QA Tier 1, Tested

#4362 feat(battery): connect to BAT BUS when set to AUTO
  .github/CHANGELOG.md
  src/systems/systems/src/electrical/battery_charge_limiter.rs
Labels: QA Tier 1, Tested

#4367 fix: update runs with deltaTime of -1
  flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A320_Neo_MFD.js
Labels: QA Tier 1, Tested

#3752 feat(mcdu): Progress Page Bearing/Dist To
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_SelectWptPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#4411 feat(du): self-test only when unpowered over 10 seconds
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/DisplayUnit.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A320_Neo_MFD.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A320_Neo_MFD.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/PFD/A320_Neo_PFD.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/PFD/A320_Neo_PFD.js
Labels: QA Tier 1, Testing Started

#4337 fix: panel display font color and backlight
  .github/CHANGELOG.md
  src/instruments/src/ATC/style.scss
  src/instruments/src/RMP/Components/RadioPanelDisplay.tsx
  src/instruments/src/RMP/style.scss
  src/instruments/src/RTPI/style.scss
Labels: QA Tier 1, Tested

#4449 feat(RMP): enable RMP LED indicators when testing ANN lights
  .github/CHANGELOG.md
  src/behavior/src/A32NX_Interior_RMP.xml
Labels: QA Tier 1, Tested

#4427 fix: Trim limits are now no longer able to be exceeded by using the right trim wheel
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_Handling.xml
Labels: QA Tier 1, Tested

#4391 fix: EFB fuel tank capacities
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
  src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
Labels: QA Tier 1, Tested

#4366 fix: approach landing lights
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
Labels: QA Tier 1, Tested

#4479 perf: enable EFB tailwindcss purging
  src/instruments/src/EFB/tailwind.config.js
Labels: QA Tier 1, Ready to Test

#4462 feat: separate dome lights
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/model/light/light.bin
  src/model/light/light.gltf
  src/model/models.json
Labels: QA Tier 1, Ready to Test

#4357 fix: evac button animation direction
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/A32NX_Interior_Generics.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1, Ready to Test

#4511 build: only enabled tailwindcss purging in production
  .github/workflows/experimental.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  src/instruments/src/EFB/tailwind.config.js
Labels: QA Tier 1, Tested

#4502 fix: Alternating igniter behaviour
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js
Labels: QA Tier 1, Ready to Test

#3980 feat(elec): replace default electrical system
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/A32NX_Interior_Generics.xml
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Airbus_A320neo_Checklist.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Library.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_APU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Core.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Electricity.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FADEC.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/DisplayUnit.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A320_Neo_MFD.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/PFD/A320_Neo_PFD.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
  src/behavior/src/A32NX_Interior_ATC.xml
  src/behavior/src/A32NX_Interior_Autopilot.xml
  src/behavior/src/A32NX_Interior_Elec.xml
  src/behavior/src/A32NX_Interior_Fire.xml
  src/behavior/src/A32NX_Interior_MCDU.xml
  src/behavior/src/A32NX_Interior_Misc.xml
  src/behavior/src/A32NX_Interior_RMP.xml
  src/instruments/src/ATC/index.tsx
  src/instruments/src/Clock/index.tsx
  src/instruments/src/DCDU/index.jsx
  src/instruments/src/EFB/Tests/globals.js
  src/instruments/src/EWD/index.jsx
  src/instruments/src/RMP/Components/BaseRadioPanels.tsx
  src/instruments/src/RTPI/index.tsx
  src/instruments/src/SD/index.jsx
  src/instruments/src/util.js
  src/systems/README.md
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/electrical/battery_charge_limiter.rs
Labels: QA Tier 2, Ready to Test

#4516 feat(checklist): add Fuel Pumps checkpoint
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Airbus_A320neo_Checklist.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Library.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1, Tested

#4478 fix(mcdu): appr qnh entry bug
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#4271 refactor: (ecam) Convert FCTL page to React
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js
  src/instruments/rollup.config.js
  src/instruments/src/SD/Pages/Fctl.jsx
  src/instruments/src/SD/Pages/Fctl/Fctl.scss
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
  src/instruments/src/SD/Pages/Fctl/config.json
  src/instruments/src/SD/PagesContainer.jsx
Labels: QA Tier 2, Tested

#4543 feat(ecam): show REFUELG on upper ECAM when refueling via EFB
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1, Tested

#4553 fix: engine oscillations at high temperature conditions
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
Labels: QA Tier 1, Testing Started

#4528 fix: initial tug waiting state
  src/instruments/src/EFB/Store/reducer/ground-reducer.tsx
Labels: QA Tier 1, Tested

#4549 fix(efb): disable link-mcdu button
  .github/CHANGELOG.md
  src/instruments/src/EFB/Dashboard/Widgets/FlightWidget.tsx
Labels: QA Tier 1, Ready to Test

#4422 fix(mcdu): Duplicate waypoints page callback
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavaidPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_SelectWptPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_WaypointPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCDataManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Ready to Test

#4620 fix(mcdu): fix aoc telex warning
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js
Labels: QA Tier 1, Tested

#4568 fix(mcdu): remove replacement chars on aoc atis page
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js
Labels: QA Tier 1, Ready to Test

#4638 fix(clock): make clock backlight subtle
  src/instruments/src/Clock/style.scss
Labels: QA Tier 1, Tested
