Repository flybywiresim/aircraft, pull requests merged in 2021-07, with the labels that each got.

#5220 fix(mcdu): Fix TOW Calculation
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#5208 feat(sound): add custom FCU sound events
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  src/behavior/src/A32NX_Interior_FCU.xml
  src/behavior/src/A32NX_Interior_Misc.xml
Labels: Tested

#4970 feat(hyd): custom autobrake
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Library.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_BrakeTemp.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/behavior/src/A32NX_Interior_Misc.xml
  src/instruments/src/SD/Pages/Wheel/Wheel.tsx
  src/systems/a320_systems/src/hydraulic.rs
  src/systems/a320_systems/src/lib.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/hydraulic/brake_circuit.rs
  src/systems/systems/src/overhead/mod.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/test.rs
Labels: QA Tier 2, Testing Started

#5203 refactor(aoc/apt): housekeeping
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_AirportList.js
Labels: QA Tier 1, Tested

#5266 feat(sound): ECAM buttons custom sound event
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
Labels: Tested

#5196 refactor(ecam): ecam autoswitch uses correct fwc logic
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
Labels: Testing Started

#5248 fix: move apu exhaust heat blur forward
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/aircraft.cfg
  src/model/fx_exhaust_apu/fx_exhaust_apu.bin
  src/model/fx_exhaust_apu/fx_exhaust_apu.gltf
  src/model/models.json
Labels: QA Tier 1

#5282 fix(chrono): improved logic for operations
  .github/CHANGELOG.md
  src/instruments/src/Clock/Components/Chrono.tsx
  src/instruments/src/Clock/Components/ElapsedTime.tsx
  src/instruments/src/Clock/index.tsx
  src/instruments/src/Clock/style.scss
Labels: QA Tier 1, Testing Started, True to Life

#5255 fix: rename default named gltf materials
  src/model/registration/registration.gltf
  src/model/sound_nodes/sound_nodes.gltf
Labels: Need in ME Fork, QA Tier 1

#5153 fix(displays): self-test no longer triggers when spawning in an in-flight state
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/DisplayUnit.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js
  src/instruments/src/Common/displayUnit.tsx
Labels: QA Tier 1

#5086 refactor: (ecam) Convert Cruise page to React
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.css
  src/instruments/buildSrc/igniter/tasks.mjs
  src/instruments/buildSrc/simulatorBuild.mjs
  src/instruments/src/SD/Pages/Crz/Crz.scss
  src/instruments/src/SD/Pages/Crz/Crz.tsx
  src/instruments/src/SD/Pages/Crz/common.tsx
  src/instruments/src/SD/Pages/Crz/config.json
  src/instruments/src/SD/Pages/Status.jsx
  src/instruments/src/SD/PagesContainer.jsx
Labels: QA Tier 1

#5263 fix: Non-continuous Idle N1 calculation
  src/fadec/src/EngineControl.h
Labels: QA Tier 1

#5322 refactor(fmgc): removed unused/obsolete code
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Testing Started

#5105 fix(atsu): FOB information is reset when Refuel *LOAD pressed in MCDU mid-flight
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
Labels: QA Tier 1

#5323 feat(sound): replace default sound events
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_ATC.xml
  src/behavior/src/A32NX_Interior_Fire.xml
  src/behavior/src/A32NX_Interior_Generics.xml
  src/behavior/src/A32NX_Interior_Handling.xml
  src/behavior/src/A32NX_Interior_Misc.xml
  src/behavior/src/A32NX_Interior_RMP.xml
Labels: QA Tier 1

#5028 feat(hyd): electric pump spool up time and hydraulic simvar for sounds
  docs/a320-simvars.md
  src/systems/a320_systems/src/hydraulic.rs
  src/systems/systems/src/hydraulic/mod.rs
Labels: QA Tier 1

#5366 ci: auto-merge bot config
  .github/auto-merge.yml
Labels: Auto Merge

#5385 feat(displays): Add pixelated screens
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/html_ui/CSS/A32NX_Display_Common.css
  src/behavior/src/A32NX_Interior_MCDU.xml
  src/instruments/src/ATC/style.scss
  src/instruments/src/BAT/style.scss
  src/instruments/src/Clock/style.scss
  src/instruments/src/Common/pixels.scss
  src/instruments/src/DCDU/style.scss
  src/instruments/src/PFD/style.scss
  src/instruments/src/RMP/style.scss
  src/instruments/src/RTPI/style.scss
Labels: QA Tier 1, Screens

#5415 fix(displays): Fix potentiometer bug - adjust pixel intensity
  flybywire-aircraft-a320-neo/html_ui/CSS/A32NX_Display_Common.css
  src/instruments/src/Common/displayUnit.tsx
  src/instruments/src/Common/pixels.scss
  src/instruments/src/PFD/index.jsx
Labels: PFD, Screens

#5400 fix(efb): Add custom attribution text
  src/instruments/src/EFB/Assets/Efb.scss
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
Labels: EFB, QA Tier 1

#5409 fix(pfd): display constraint alt prior to flight phase 2
  src/instruments/src/PFD/index.jsx
Labels: QA Tier 1

#5254 feat(hyd): weight on wheels sensors to replace SIM ON GROUND
  .github/CHANGELOG.md
  src/systems/a320_systems/src/electrical/direct_current.rs
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/a320_systems/src/hydraulic.rs
  src/systems/a320_systems/src/lib.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/electrical/battery_charge_limiter.rs
  src/systems/systems/src/hydraulic/brake_circuit.rs
  src/systems/systems/src/landing_gear/mod.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/test.rs
Labels: Update for SU5

#5457 fix(sound): pack one
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
Labels: QA Tier 1

#5492 fix: workaround for #5487 in regards to altitude issues
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cockpit.cfg
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/interface/SimConnectData.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/interface/SimConnectInterface.h
Labels: QA Tier 1
