Repository flybywiresim/aircraft, pull requests merged in 2021-01, with the labels that each got.

#2788 [CDU] Cleanup
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXConstants.js
  A32NX/html_ui/Pages/A32NX_Utils/NXFunctions.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirportsMonitor.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_HoldAtPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IdentPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_WindPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_FreeText.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_Init.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesReceived.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesSent.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_PositionReport.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_SIMBRIEF.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_REALISM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#2699 Two small fixes for flightphase speeds
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#2747 fix: API connection logic
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXApi.js
Labels: Tested

#2847 Revert "[CDU] Cleanup (#2788)"
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXConstants.js
  A32NX/html_ui/Pages/A32NX_Utils/NXFunctions.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirportsMonitor.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_HoldAtPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IdentPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_WindPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_FreeText.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_Init.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesReceived.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesSent.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_PositionReport.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_SIMBRIEF.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_REALISM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#2819 Change pitchPID + headingPID to default values
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/ai.cfg
Labels: Tested

#2855 Tcas traffic knob movement fix
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
Labels: Tested

#2857 Fix spoiler auto-retract on landing
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: Ready to Test

#2881 fix: Display BG on DCDU & SAI
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.html
  src/instruments/src/DCDU/style.scss
Labels: Needs Changelog, Tested

#2896 Enable F/O MCDU buttons
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#2804 Improved fix for uncontrollable dive
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Speeds.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Testing Started

#2762 [ECAM] Add missing fuel conversion
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js
Labels: Ready to Test

#2389 Add FCU TRK/FPA Mode
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/en-US.locPak
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseNDCompass.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/HSIndicator.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/VerticalSpeedIndicator.js
  docs/a320-simvars.md
  src/behavior/src/A32NX_Interior_FCU.xml
Labels: Accuracy Checked, Tested

#2876 [CDU] Changing CRZ and DES speed to allow and hold any speed restriction
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: MCDU, Ready to Test

#2877 MCDU Improvements
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_WindPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessageSentDetail.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsMessage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: MCDU, Ready to Test, Visual

#2904 [BUGFIX] Error message for invalid trip wind delim
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#2945 ADIRS "ON BAT" light
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js
  src/model/build.js
  src/model/models.json
  src/model/onbat/onbat.bin
  src/model/onbat/onbat.gltf
Labels: Ready to Test

#2950 fix: door lock animation
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
Labels: Tested

#2915 [MCDU] Fix bad old user input being displayed on scratchpad
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: MCDU, Tested

#2940 [CDU] Fix APPR/GO AROUND page order
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Labels: Tested

#2879 [CDU] Fix INIT-A CRZ FL/TEMP input
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: MCDU, Tested

#2824 [OPTIONS] Initialize unit conversion only start up
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.js
Labels: Tested, Visual

#2989 fix: upper ECAM showing engineering mode overlay
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html
  docs/resources.md
  typings/fs-base-ui/html_ui/JS/common.d.ts
Labels: Tested

#3015 [CDU] Fix to speeds disagree check
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Tested

#3019 [CDU] Removed redundant code for to check
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Ready to Test

#3032 fixed morse code sound on idle at high altitudes
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml
Labels: Ready to Test

#2748 Fix load factor limits
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: Tested

#3016 [ECAM] Improve ECAM Memo TO Flaps and TO CONFIG checks
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Tested

#2976 Optimize performance by sequencing updates (+ ~50% fps)
  .github/CHANGELOG.md
  A32NX/html_ui/JS/A32NX_Util.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Elec.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js
Labels: Tested

#3054 fix: synch load script and template resources
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/ATC/A320_Neo_ATC.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.html
  typings/fs-base-ui/html_ui/JS/common.d.ts
Labels: Ready to Test

#3060 feat: [ECAM] F/CTL FLAP/MCDU DISAGREE check
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: Tested

#2984 cleanup: cdu/fms code
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Extensive Testing Needed, QA Tier 2, Testing Started

#3118 Changed AIRCOND knobs starting position to 12 o'clock
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
Labels: QA Tier 1, Tested

#3115 fix: condition for F/CTL FLAP/MCDU DISAGREE
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1, Tested

#3114 cleanup: cdu/fms code (part 2)
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Extensive Testing Needed, QA Tier 2, Tested

#3012 [CDU] Fix double arrows on INIT FUEL PRED page
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: QA Tier 1, Testing Started

#3135 feat: printer
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessageSentDetail.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsMessage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/CFDS/A320_Neo_CDU_CFDS_Avionics_Menu.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/CFDS/A320_Neo_CDU_CFDS_Menu.js
  A32NX/html_ui/Pages/VLivery/Liveries/Printer/Printer.css
  A32NX/html_ui/Pages/VLivery/Liveries/Printer/Printer.html
  A32NX/html_ui/Pages/VLivery/Liveries/Printer/Printer.js
  src/behavior/src/A32NX_Interior_Printer.xml
  src/model/models.json
  src/model/printer/print-static.bin
  src/model/printer/print-static.gltf
  src/model/printer/print-torn.bin
  src/model/printer/print-torn.gltf
  src/model/printer/printer.bin
  src/model/printer/printer.gltf
Labels: QA Tier 1, Ready to Test, Testing Started

#3140 [ECAM] Support CONF 3 Landing
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1, Tested

#3174 fix: correct printer animation speed
  src/behavior/src/A32NX_Interior_Printer.xml
Labels: Tested

#3155 fix(sound): add timer to basic packs logic
  A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
Labels: QA Tier 1, Tested

#3188 fix: disable tiller plate emissive
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: Tested

#2889 feat(mcdu): Support CONF 3 Landing
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXSpeeds.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#1877 fix: refactor overhead panel modelbehaviors (new sounds)
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/A32NX_Interior_Generics.xml
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_Elec.xml
  src/behavior/src/A32NX_Interior_Fire.xml
  src/behavior/src/A32NX_Interior_Misc.xml
Labels: QA Tier 2, Tested

#3216 feat(efb): added company page
  src/instruments/src/EFB/Company/Company.tsx
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/README.md
  src/instruments/src/EFB/ToolBar/ToolBar.tsx
Labels: Ready to Test

#3154 fix(mcdu): Vapp pilot entry improvements
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#3223 fix(mcdu): fix race condition when spawning directly into approach
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: QA Tier 1, Tested

#2980 feat(rmp): separate and rewrite radio management panels
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.js
  docs/a320-simvars.md
  package.json
  src/.eslintrc.js
  src/behavior/build.js
  src/behavior/src/A32NX_Interior_RMP.xml
  src/instruments/src/DCDU/index.jsx
  src/instruments/src/RMP/Components/RadioManagementPanel.jsx
  src/instruments/src/RMP/Components/SevenSegmentDisplay.jsx
  src/instruments/src/RMP/Components/StandbyFrequency.jsx
  src/instruments/src/RMP/Framework/AcceleratedKnob.mjs
  src/instruments/src/RMP/Framework/CachedSimVar.mjs
  src/instruments/src/RMP/Framework/RateScheduler.mjs
  src/instruments/src/RMP/Framework/StatefulSimVar.mjs
  src/instruments/src/RMP/config.json
  src/instruments/src/RMP/index.jsx
  src/instruments/src/RMP/style.scss
  src/instruments/src/util.mjs
  src/model/models.json
Labels: QA Tier 2, Ready to Test

#3251 fix: Adjust landing gear suspension to be stiffer
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: QA Tier 1, Ready to Test
