Repository flybywiresim/aircraft, pull requests merged in 2021-03, with the labels that each got.

#3767 feat(apu): improve bleed air EGT model
  src/systems/systems/src/apu/APS3200.md
  src/systems/systems/src/apu/aps3200.rs
  src/systems/systems/src/apu/mod.rs
Labels: QA Tier 1, Ready to Test

#3769 feat(apu): remove BLEED FAULT light behaviour
  src/systems/a320_systems/src/lib.rs
  src/systems/a320_systems/src/pneumatic.rs
Labels: QA Tier 1, Ready to Test

#3768 revert: APU FLAP OPEN indication until closed
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
  docs/a320-simvars.md
  src/systems/systems/src/apu/air_intake_flap.rs
  src/systems/systems/src/apu/mod.rs
Labels: QA Tier 1, Ready to Test

#3649 fix(mcdu): Import cost index into MCDU when importing from SimBrief
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#3726 fix(mcdu): Check Take Off Data
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#3753 fix(ecam): correct registration of new ecam pages
  src/instruments/ecam-page-template/template.js
Labels: QA Tier 1, Tested

#3773 build: use fragmenter for optimised distribution
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  package.json
  scripts/fragment.js
Labels: CI, QA Tier 1, Tested

#3469 fix: hide colon when chrono stopped (#3237)
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js
Labels: QA Tier 1, Tested

#3376 feat: Implement even more additional overhead button/switch functionality (MASK MAN ON, EMER ELEC PWR MAN ON, Cargo smoke DISCH, etc.)
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/A32NX_Interior_Generics.xml
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  docs/a320-simvars.md
  src/behavior/src/A32NX_Interior_Handling.xml
Labels: QA Tier 2, Tested

#3367 feat(efb): pre-defined camera view
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cameras.cfg
Labels: QA Tier 1, Ready to Test

#3805 fix(nd): fixes overlapping distance text
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDInfo.js
Labels: QA Tier 1, Tested

#3785 feat: Added instrument hints to PRELIMINARY COCKPIT PREP. checklist page
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1, Tested

#3795 build: fragmenter fix & artifact size reduction
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: CI, QA Tier 1, Tested

#3827 fix(mcdu): options page text overlap and typo
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js
Labels: QA Tier 1, Tested

#3828 feat(efb): add adjustable brightness setting
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/instruments/src/EFB/Settings/Settings.tsx
  src/instruments/src/EFB/Settings/sync.ts
Labels: QA Tier 1, Tested

#3611 feat: hangar.flt
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/hangar.flt
Labels: QA Tier 1, Tested

#3855 fix(fmgc): bad flight phase change on spawn
  A32NX/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
Labels: QA Tier 1, Tested

#3889 fix(efb): restore interactivity after MSFS 1.14.5.0
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/instruments/src/EFB/index.jsx
Labels: QA Tier 1, Testing Started

#3881 fix: vertical speed FCU logic
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.js
  src/behavior/src/A32NX_Interior_FCU.xml
Labels: QA Tier 2, Tested

#3856 build: get rid of FTP upload
  .github/workflows/master.yml
  .github/workflows/release.yml
  scripts/cdn.sh
Labels: CI

#3884 fix(nd): VOR/ADF info after Asobo update 1.14.5.0
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDCompass.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDInfo.js
  typings/fs-base-ui/html_ui/JS/SimPlane.d.ts
Labels: QA Tier 1, Tested

#3520 feat(efb): added functionality to ground services page
  .github/CHANGELOG.md
  src/instruments/src/EFB/Components/Button/Button.tsx
  src/instruments/src/EFB/Ground/DoorToggle.tsx
  src/instruments/src/EFB/Ground/Ground.scss
  src/instruments/src/EFB/Ground/Ground.tsx
  src/instruments/src/EFB/Store/action-creator/ground-state.tsx
  src/instruments/src/EFB/Store/actions.tsx
  src/instruments/src/EFB/Store/index.tsx
  src/instruments/src/EFB/Store/reducer/ground-reducer.tsx
Labels: QA Tier 2, Testing Started

#3928 fix: Add cockpit.cfg to fix full flap angle in ext view
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cockpit.cfg
Labels: QA Tier 1, Tested

#3766 refactor(ecam): Convert COND page to React and add new SimVars
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js
  docs/a320-simvars.md
  src/instruments/ecam-page-template/template.html
  src/instruments/ecam-page-template/template.js
  src/instruments/rollup.config.js
  src/instruments/src/Common/defaults.ts
  src/instruments/src/Common/hooks.tsx
  src/instruments/src/Common/index.tsx
  src/instruments/src/SD/Pages/Cond.jsx
  src/instruments/src/SD/Pages/Cond/Cond.scss
  src/instruments/src/SD/Pages/Cond/Cond.tsx
  src/instruments/src/SD/Pages/Cond/config.json
  src/instruments/src/SD/Pages/Door/Door.tsx
  src/instruments/src/SD/PagesContainer.jsx
Labels: QA Tier 1, Tested

#3917 fix(mcdu): new crz alt message
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 2, Tested

#3908 refactor(fms): some cleanup
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#3952 fix(efb): Fix Scrolling in EFB OFP
  src/instruments/src/EFB/Dispatch/Dispatch.tsx
  src/instruments/src/EFB/Dispatch/Pages/Loadsheet.scss
  src/instruments/src/EFB/Dispatch/Pages/LoadsheetPage.tsx
Labels: QA Tier 1, Testing Started

#3878 fix: Update flaps in flight model for MSFS update 1.14.5.0
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/engines.cfg
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: QA Tier 3, Testing Started

#3954 build: purge cdn cache after upload
  scripts/cdn.sh
Labels: CI

#3930 feat: add console/floor light switch functionality
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/hangar.flt
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/systems.cfg
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  A32NX/effects/LIGHT_A32NX_Console.fx
  src/behavior/src/A32NX_Interior_Misc.xml
Labels: QA Tier 2, Ready to Test

#3624 build: simple igniter configuration
  .eslintignore
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .gitignore
  igniter.config.mjs
  package.json
  scripts/build.sh
  scripts/metadata.sh
Labels: QA Tier 1, Tested

#3870 fix(nd): prettier ND with more formatting
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDInfo.js
Labels: QA Tier 1, Tested, Waiting For Response

#3683 feat(mcdu): Messages dynamic field compatibility
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
  A32NX/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 2, Tested

#3985 fix(misc): Change of default switch positions for RAM AIR, WX Mode, TCAS ALT RPTG and TCAS Threat
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/hangar.flt
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  src/behavior/src/A32NX_Interior_ATC.xml
Labels: QA Tier 1, Tested

#4013 fix(mcdu): takeoff performance page
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#4012 fix(nd): quick fix for PPOS/Wpt when ADIRS not aligned
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
Labels: QA Tier 1, Tested

#2870 refactor: save simbrief user IDs instead of usernames
  A32NX/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  A32NX/html_ui/Pages/A32NX_Utils/SimBriefApi.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_SIMBRIEF.js
  README.md
Labels: QA Tier 1, Tested

#4003 fix(mcdu): waypoint deletion not showing in tmpy fp
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: QA Tier 1, Tested

#3784 fix: getConstraintAltitude() function crash
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/FMGC/A32NX_ConstraintManager.js
Labels: QA Tier 2, Tested

#3794 feat: React Chrono, BAT indicator, rudder trim indicator
  A32NX/ModelBehaviorDefs/A32NX/A32NX_Interior_Generics.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.js
  src/instruments/src/BAT/config.json
  src/instruments/src/BAT/index.tsx
  src/instruments/src/BAT/style.scss
  src/instruments/src/Clock/Components/Chrono.tsx
  src/instruments/src/Clock/Components/Clock.tsx
  src/instruments/src/Clock/Components/ElapsedTime.tsx
  src/instruments/src/Clock/config.json
  src/instruments/src/Clock/index.tsx
  src/instruments/src/Clock/style.scss
  src/instruments/src/RTPI/config.json
  src/instruments/src/RTPI/index.tsx
  src/instruments/src/RTPI/style.scss
Labels: QA Tier 2, Tested

#3131 fix(ecam): All cycle functionality
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseAirliners.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
Labels: QA Tier 1, Tested

#3886 feat(nd): VOR/ADF needles on ARC screen
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseNDCompass.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDCompass.js
Labels: QA Tier 1, Tested

#3924 fix(fmgc): flight phase manager improvements
  A32NX/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MenuPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 2, Tested

#4029 chore: roll igniter to 1.1.4
  package.json
Labels: QA Tier 1, Ready to Test

#4033 fix(mcdu): init a small improvements
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: QA Tier 1, Tested

#3643 feat(mcdu): upgrade perf appr page to release 2
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 2, Tested

#4022 fix: visual error on COND page when hot air pressure valve is off
  .github/CHANGELOG.md
  src/instruments/src/SD/Pages/Cond/Cond.scss
  src/instruments/src/SD/Pages/Cond/Cond.tsx
Labels: QA Tier 1, Tested

#3760 fix: minor altitude alert sound fix
  A32NX/html_ui/Pages/A32NX_Core/A32NX_FWC.js
Labels: QA Tier 2, Testing Started

#3744 feat(efb): fuel page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  src/instruments/src/EFB/Assets/320neo_outline_fuel.svg
  src/instruments/src/EFB/Components/Form/Select.tsx
  src/instruments/src/EFB/Components/Form/SimpleInput/SimpleInput.tsx
  src/instruments/src/EFB/Components/Form/Slider.tsx
  src/instruments/src/EFB/Components/Progress/Progress.scss
  src/instruments/src/EFB/Components/Progress/Progress.tsx
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/Dispatch/Dispatch.tsx
  src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
  src/instruments/src/EFB/Dispatch/Styles/Fuel.scss
  src/instruments/src/EFB/Settings/sync.ts
Labels: QA Tier 2, Tested

#4076 fix(elec): lack of power not detected in same tick
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/systems/src/apu/aps3200.rs
  src/systems/systems/src/apu/mod.rs
  src/systems/systems/src/electrical/emergency_generator.rs
  src/systems/systems/src/electrical/engine_generator.rs
  src/systems/systems/src/electrical/external_power_source.rs
Labels: QA Tier 1, Ready to Test

#3979 fix: Flight model update to reduce flap drag
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/engines.cfg
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: QA Tier 2, Tested

#4100 fix(mcdu): do not round baro/radio, remove ILS check on PERF APPR
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Ready to Test

#3751 feat: add custom loading tips
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/aircraft.cfg
  A32NX/de-DE.locPak
  A32NX/en-US.locPak
  A32NX/es-ES.locPak
  A32NX/fr-FR.locPak
  A32NX/it-IT.locPak
  A32NX/pl-PL.locPak
  A32NX/pt-BR.locPak
  A32NX/ru-RU.locPak
  A32NX/zh-CN.locPak
Labels: QA Tier 1, Ready to Test

#4118 feat(RMP): add illumination to the RMP volume knobs
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
  A32NX/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1, Ready to Test

#4103 fix(mcdu): revise route reserve calculation
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: MCDU, QA Tier 1, Tested

#4128 fix(ACP): correct CALL buttons behaviour when ANN LT is on
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1, Tested

#4166 fix(pf): replace dh/mda with radio/baro
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Labels: QA Tier 1, Tested

#4178 fix: make holds inop
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js
Labels: QA Tier 1, Tested

#4077 refactor(core): update throttling, restructuring
  A32NX/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_APU.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_BrakeTemp.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Electricity.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Speeds.js
Labels: QA Tier 2, Tested

#4045 refactor: MCDU model behaviors into src
  A32NX/ModelBehaviorDefs/A32NX/FMC.xml
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_MCDU.xml
Labels: QA Tier 1, Ready to Test
