Repository flybywiresim/aircraft, pull requests merged in 2021-11, with the labels that each got.

#6099 feat: registration decal setting
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  flybywire-aircraft-a320-neo/html_ui/Pages/VLivery/Liveries/A32NX_Registration/Registration.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VLivery/Liveries/A32NX_Registration/Registration.js
  src/instruments/src/EFB/Settings/Settings.tsx
Labels: QA Tier 1

#6110 revert: remove pixels (after SU6)
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/CSS/A32NX_Display_Common.css
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  src/instruments/src/Common/displayUnit.tsx
  src/instruments/src/Common/pixels.scss
  src/instruments/src/DCDU/index.jsx
  src/instruments/src/DCDU/style.scss
  src/instruments/src/ISIS/ISISDisplayUnit.tsx
  src/instruments/src/ISIS/style.scss
Labels: QA Tier 1

#6103 feat(hyd): low pass filter function in shared system module
  src/systems/systems/src/hydraulic/brake_circuit.rs
  src/systems/systems/src/shared/low_pass_filter.rs
  src/systems/systems/src/shared/mod.rs
Labels: QA Tier 1

#6107 feat(model): add portholes
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cameras.cfg
  src/model/build.js
  src/model/models.json
Labels: 3D Model, QA Tier 1

#6148 fix: Removed MCDU Link button from EFB to avoid user confusion
  src/instruments/src/EFB/Dashboard/Widgets/FlightWidget.tsx
Labels: EFB

#6158 fix(model): delete redundant views #12+#13, add back old views #14+#15
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cameras.cfg
Labels: 3D Model

#6088 refactor: use coherent events to transfer printer data
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VLivery/Liveries/Printer/Printer.js
Labels: QA Tier 1

#6163 fix(lights): Adjust top beacon for compability with portholes + daytime color adjustment
  flybywire-aircraft-a320-neo/effects/LIGHT_A32NX_BeaconTop.fx
Labels: Lighting

#6152 fix(mcdu): scratchpad input behaviour with messages displayed
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Scratchpad.js
Labels: QA Tier 1

#6179 fix(elec): connect captain dome and nav lights to gnd flt svc buses
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
Labels: QA Tier 1

#6156 feat(sound): add alt increment sound and fix ISI sound events.
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_Autopilot.xml
  src/behavior/src/A32NX_Interior_ISIS.xml
Labels: QA Tier 1

#6201 fix(mcdu): backlight and brightness
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.css
  src/behavior/src/A32NX_Interior_MCDU.xml
Labels: QA Tier 1

#6217 fix(model): Adjust heat effect on ENG1+2
  .github/CHANGELOG.md
  src/model/models.json
Labels: 3D Model

#6219 fix(pfd): speed tape outline at low speeds
  .github/CHANGELOG.md
  src/instruments/src/PFD/SpeedIndicator.tsx
Labels: True to Life, QA Tier 1

#6200 feat(atsu): get trans alt and level from simbrief
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  src/fmgc/src/flightplanning/FlightPlanManager.ts
Labels: QA Tier 1

#5895 feat: improved flightmodel, w&b, baggage loading and MSFS fuel UI override
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Boarding.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadConstructor.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fadec/src/EngineControl.h
  src/fadec/src/FadecGauge.h
  src/fadec/src/RegPolynomials.h
  src/fadec/src/SimVars.h
  src/fadec/src/common.h
  src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
Labels: Flight Model, QA Tier 1

#6228 fix: transition alt/level
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fmgc/src/components/EfisLabels.ts
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/lib/FmgcComponent.ts
  src/fmgc/src/loop.ts
Labels: QA Tier 1
