Repository flybywiresim/aircraft, pull requests merged in 2021-12, with the labels that each got.

#6258 fix(fcu): feed display lighting from correct bus
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1

#6135 fix: prevent triggering key events for more inputs in efb
  src/instruments/src/EFB/Components/Form/Input/Input.tsx
  src/instruments/src/EFB/Components/Form/SimpleInput/SimpleInput.tsx
  src/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx
  src/instruments/src/EFB/TODCalculator/GroundSpeed/GroundSpeedManual/GroundSpeedManual.tsx
Labels: QA Tier 1

#6175 fix(inst): chrono & ET behavior on time shift
  .github/CHANGELOG.md
  src/instruments/src/Clock/Components/Chrono.tsx
  src/instruments/src/Clock/Components/ElapsedTime.tsx
  src/instruments/src/Common/index.tsx
  src/instruments/src/ND/elements/Chrono.tsx
Labels: QA Tier 2

#6297 feat(ecam): Add delta symbol to font
  flybywire-aircraft-a320-neo/html_ui/Fonts/ECAMFontRegular.ttf
  src/fonts/ECAMFontRegular_Source.sfd
Labels: QA Tier 1

#6327 fix(ecam): fix gross weight being shown without engines running
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.js
Labels: QA Tier 2

#5705 refactor(ecam): Convert Pressure page to React
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js
  src/instruments/buildSrc/igniter/tasks.mjs
  src/instruments/src/Common/gauges.scss
  src/instruments/src/Common/gauges.tsx
  src/instruments/src/SD/Pages/Crz/Crz.tsx
  src/instruments/src/SD/Pages/Crz/common.tsx
  src/instruments/src/SD/Pages/Press.jsx
  src/instruments/src/SD/Pages/Press/Press.scss
  src/instruments/src/SD/Pages/Press/Press.tsx
  src/instruments/src/SD/Pages/Press/config.json
  src/instruments/src/SD/PagesContainer.jsx
Labels: QA Tier 1

#5384 feat(bleed): replace default bleed system
  .github/CHANGELOG.md
  .gitignore
  docs/a320-simvars.md
  src/behavior/src/A32NX_Interior_Misc.xml
  src/systems/a320_hydraulic_simulation_graphs/src/main.rs
  src/systems/a320_systems/src/hydraulic.rs
  src/systems/a320_systems/src/lib.rs
  src/systems/a320_systems/src/pneumatic.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/apu/aps3200.rs
  src/systems/systems/src/apu/electronic_control_box.rs
  src/systems/systems/src/apu/mod.rs
  src/systems/systems/src/hydraulic/brake_circuit.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/update_iterator.rs
  src/systems/systems/src/pneumatic/mod.rs
  src/systems/systems/src/pneumatic/valve.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/update_context.rs
Labels: QA Tier 2, Pneumatic

#6353 feat: autopilot improvements and preparation work
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  src/fbw/build.sh
  src/fbw/src/FlightDataRecorder.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/interface/SimConnectData.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/AutopilotLaws.h
  src/fbw/src/model/AutopilotLaws_data.cpp
  src/fbw/src/model/AutopilotLaws_types.h
  src/fbw/src/model/AutopilotStateMachine.cpp
  src/fbw/src/model/AutopilotStateMachine.h
  src/fbw/src/model/AutopilotStateMachine_data.cpp
  src/fbw/src/model/AutopilotStateMachine_types.h
  src/fbw/src/model/Autothrust.cpp
  src/fbw/src/model/Autothrust.h
  src/fbw/src/model/Autothrust_data.cpp
  src/fbw/src/model/Double2MultiWord.cpp
  src/fbw/src/model/FlyByWire.cpp
  src/fbw/src/model/FlyByWire.h
  src/fbw/src/model/FlyByWire_data.cpp
  src/fbw/src/model/MultiWordIor.cpp
  src/fbw/src/model/div_s32.cpp
  src/fbw/src/model/div_s32.h
  src/fbw/src/model/look1_binlxpw.cpp
  src/fbw/src/model/mod_lHmooAo5.h
  src/fbw/src/model/mod_mvZvttxs.cpp
  src/fbw/src/model/mod_mvZvttxs.h
  src/fbw/src/model/mod_tnBo173x.cpp
  src/fbw/src/model/mod_tnBo173x.h
  src/fbw/src/model/rt_modd.cpp
  src/fbw/src/model/rt_remd.cpp
  src/fbw/src/model/rt_roundd.cpp
  src/fbw/src/model/rt_roundd.h
  src/fbw/src/model/uMultiWord2Double.cpp
  src/fdr2csv/src/FlightDataRecorderConverter.cpp
  src/fdr2csv/src/main.cpp
Labels: QA Tier 2

#6043 feat: Manual ILS Tuning by Ident, Course
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCDataManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  src/instruments/src/ND/pages/ArcMode.tsx
  src/instruments/src/ND/pages/RoseMode.tsx
  src/instruments/src/PFD/HeadingIndicator.tsx
  src/instruments/src/PFD/index.tsx
Labels: QA Tier 1

#6363 fix(atsu): use https for simbrief
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/SimBriefApi.js
  src/instruments/src/EFB/Settings/Settings.tsx
Labels: QA Tier 1

#6369 fix: increase airport loading timeout
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_WaypointLoader.js
Labels: QA Tier 1

#6387 fix(ap): CLB engagement on take-off, improved ALT condition
  .github/CHANGELOG.md
  src/fbw/src/model/AutopilotStateMachine.cpp
  src/fbw/src/model/AutopilotStateMachine.h
Labels: QA Tier 1

#6371 feat(lights): Add PARK BRK EXT LT
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
  flybywire-aircraft-a320-neo/effects/LIGHT_A32NX_ParkBrkLight.fx
  flybywire-aircraft-a320-neo/effects/LIGHT_A32NX_ParkBrkLightAmbient.fx
  src/behavior/src/A32NX_Interior_Generics.xml
Labels: Lighting

#6382 fix: Added new tab to EFB "Realism"
  src/instruments/src/EFB/Settings/Settings.tsx
Labels: EFB

#3467 feat: support connecting mcdu to websocket server
  .github/CHANGELOG.md
  .gitignore
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AirportsMonitor.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FixInfoPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_IRSInit.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Scratchpad.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessageSentDetail.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesReceived.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsMessage.js
  igniter.config.mjs
  package.json
  src/instruments/src/EFB/Components/Form/SimpleInput/SimpleInput.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
  src/mcdu-server/client/public/android-chrome-192x192.png
  src/mcdu-server/client/public/android-chrome-512x512.png
  src/mcdu-server/client/public/apple-touch-icon-180x180.png
  src/mcdu-server/client/public/favicon.ico
  src/mcdu-server/client/public/index.html
  src/mcdu-server/client/public/manifest.json
  src/mcdu-server/client/public/mcdu-r2-c.png
  src/mcdu-server/client/rollup.config.js
  src/mcdu-server/client/src/App.css
  src/mcdu-server/client/src/App.jsx
  src/mcdu-server/client/src/McduButtons.css
  src/mcdu-server/client/src/McduButtons.jsx
  src/mcdu-server/client/src/McduScreen.css
  src/mcdu-server/client/src/McduScreen.jsx
  src/mcdu-server/client/src/WebsocketContext.jsx
  src/mcdu-server/client/src/index.css
  src/mcdu-server/client/src/index.jsx
  src/mcdu-server/index.js
  src/mcdu-server/standalone-patch.js
Labels: QA Tier 1
