Repository flybywiresim/aircraft, pull requests merged in 2021-02, with the labels that each got.

#3282 fix: flight director pitch bar alignment
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
Labels: QA Tier 1, Ready to Test

#3280 feat(apu): FLAP OPEN indication until fully closed
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
  docs/a320-simvars.md
  src/systems/a320/src/lib.rs
  src/systems/systems/src/apu/air_intake_flap.rs
  src/systems/systems/src/apu/mod.rs
  src/systems/systems/src/simulator/mod.rs
Labels: QA Tier 1, Ready to Test

#3276 fix(apu): MASTER SW reversed push state
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1, Ready to Test

#3275 fix(apu): bleed available while in cooldown
  A32NX/html_ui/Pages/A32NX_Core/A32NX_APU.js
  A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  docs/a320-simvars.md
  src/behavior/src/A32NX_Interior_Misc.xml
  src/systems/a320/src/lib.rs
Labels: QA Tier 1, Ready to Test

#3252 feat: enable efb
  .eslintignore
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg
  package.json
  src/.eslintrc.js
  src/instruments/rollup.config.js
  src/instruments/src/EFB/Assets/Boot.scss
  src/instruments/src/EFB/Assets/Efb.scss
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/Dispatch/Dispatch.tsx
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Ground/Ground.scss
  src/instruments/src/EFB/Ground/Ground.tsx
  src/instruments/src/EFB/ToolBar/ToolBar.tsx
  src/instruments/src/EFB/config.json
  src/instruments/src/EFB/index.jsx
  src/instruments/src/EFB/tailwind.config.js
  src/instruments/src/EFB/temporary.jsx
  src/model/efb/flypad.bin
  src/model/efb/flypad.gltf
Labels: QA Tier 2, Tested

#3296 feat(efb): make EFB have its own battery
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/instruments/src/EFB/index.jsx
  src/instruments/src/EFB/react-app-env.d.ts
Labels: Ready to Test, Tested

#3300 fix(efb): UI fixes, dev server
  .gitignore
  package.json
  src/instruments/src/EFB/Assets/Boot.scss
  src/instruments/src/EFB/Assets/Efb.scss
  src/instruments/src/EFB/Company/Company.tsx
  src/instruments/src/EFB/Components/Navbar.tsx
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/Dispatch/Dispatch.tsx
  src/instruments/src/EFB/README.md
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/instruments/src/EFB/ToolBar/ToolBar.tsx
  src/instruments/src/EFB/index-web.tsx
  src/instruments/src/EFB/index.html
  src/instruments/src/EFB/rollup.development.config.js
Labels: QA Tier 1, Tested

#3325 fix(mcdu): Remove PAX on INIT A page
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: QA Tier 1, Ready to Test

#3182 refactor(cdu/fms): code cleanup (part 3)
  A32NX/html_ui/Pages/A32NX_Utils/NXSpeeds.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Extensive Testing Needed, QA Tier 2, Tested

#3328 fix: EFB Dispatch page fuel quantity, cargo capacity, MRW, MTOW, MZFW
  src/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
Labels: QA Tier 1, Tested

#3315 fix(efb): introduce input component to EFB device and put it on simbrief page
  src/instruments/src/EFB/Company/Company.tsx
  src/instruments/src/EFB/Components/Form/Input/Input.scss
  src/instruments/src/EFB/Components/Form/Input/Input.tsx
  src/instruments/src/EFB/tailwind.config.js
Labels: QA Tier 1, Ready to Test

#3344 refactor(efb): few fixes and restructuring 🥚
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  package.json
  src/instruments/src/EFB/Assets/Boot.scss
  src/instruments/src/EFB/Assets/Efb.scss
  src/instruments/src/EFB/Components/Navbar.tsx
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/instruments/src/EFB/index-web.tsx
  src/instruments/src/EFB/index.jsx
Labels: QA Tier 1, Tested

#3358 fix(rmp): RateScheduler unscheduling not working
  src/instruments/src/RMP/Framework/RateScheduler.mjs
  src/instruments/src/RMP/Framework/StatefulSimVar.mjs
Labels: QA Tier 2, Ready to Test

#3295 fix: FCU knobs sound and minor emissive fixes
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_Autopilot.xml
  src/behavior/src/A32NX_Interior_FCU.xml
Labels: QA Tier 1, Tested

#3310 refactor(mcdu): AC STATUS page
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IdentPage.js
Labels: QA Tier 1, Tested

#3262 perf: Performance fixes for flight plans
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: QA Tier 2, Tested

#3372 fix(mcdu): perf page
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Critical Bug, QA Tier 2, Testing Started

#3239 fix(mcdu): AOC RCVD MSGS scrolling, add arrows, and update on receipt
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesReceived.js
Labels: QA Tier 1, Tested

#3378 feat(ecam): Add TCAS STBY warning
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1, Tested

#3336 fix: brake temps for new wheel size
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_BrakeTemp.js
Labels: QA Tier 1, Ready to Test

#3287 fix(core:speeds): Vls computation during Take Off
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_Speeds.js
  A32NX/html_ui/Pages/A32NX_Utils/NXSpeeds.js
Labels: QA Tier 1, Testing Started

#3375 fix(efb): improve readability
  src/instruments/src/EFB/Dashboard/Widgets/FlightWidget.tsx
  src/instruments/src/EFB/ToolBar/ToolBar.tsx
Labels: QA Tier 1, Ready to Test

#3291 fix(utils:speeds): TO Vls config 3
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXSpeeds.js
Labels: QA Tier 1, Testing Started

#3414 fix: v2 table conf3
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXSpeeds.js
Labels: QA Tier 1, Tested

#3285 feat(mcdu): Check Take Off Data
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#3405 fix(nd): remove label from smallest circle in arc mode
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDCompass.js
Labels: QA Tier 1, Tested

#3443 refactor: move DH LVar init into FMC
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Labels: QA Tier 1, Ready to Test

#3396 fix: regressions for flight plan drawing throttling
  A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: QA Tier 2, Tested

#3434 refactor(mcdu): create MCDU field classes
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_Field.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: QA Tier 1, Tested

#3270 refactor: introduce new SimVar hooks for React
  src/behavior/src/A32NX_Interior_RMP.xml
  src/instruments/rollup.config.js
  src/instruments/src/Common/RateMultiplierKnob.ts
  src/instruments/src/Common/defaults.ts
  src/instruments/src/Common/hooks.tsx
  src/instruments/src/Common/index.tsx
  src/instruments/src/Common/simVars.tsx
  src/instruments/src/RMP/Components/BaseRadioPanels.tsx
  src/instruments/src/RMP/Components/RadioManagementPanel.jsx
  src/instruments/src/RMP/Components/RadioPanelDisplay.tsx
  src/instruments/src/RMP/Components/SevenSegmentDisplay.jsx
  src/instruments/src/RMP/Components/StandbyFrequency.jsx
  src/instruments/src/RMP/Components/StandbyFrequency.tsx
  src/instruments/src/RMP/Components/VhfRadioPanel.tsx
  src/instruments/src/RMP/Framework/CachedSimVar.mjs
  src/instruments/src/RMP/Framework/RateScheduler.mjs
  src/instruments/src/RMP/Framework/StatefulSimVar.mjs
  src/instruments/src/RMP/config.json
  src/instruments/src/RMP/index.jsx
  src/instruments/src/RMP/index.tsx
  src/instruments/template/template.js
  src/instruments/tsconfig.json
Labels: QA Tier 2, Testing Started, Waiting on Core Decision

#3479 feat: coffee cup
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/TEXTURE/CUP_LOW2_ALBEDO.PNG.DDS
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/TEXTURE/CUP_LOW2_ALBEDO.PNG.DDS.json
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/TEXTURE/CUP_LOW2_METAL.PNG.DDS
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/TEXTURE/CUP_LOW2_METAL.PNG.DDS.json
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/TEXTURE/CUP_LOW2_NORMAL.PNG.DDS
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/TEXTURE/CUP_LOW2_NORMAL.PNG.DDS.json
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_Misc.xml
  src/model/cup/cup.bin
  src/model/cup/cup.gltf
  src/model/models.json
Labels: QA Tier 1, Tested

#3498 fix(nd): use correct font for waypoints
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/mapConfig.json
Labels: QA Tier 1, Tested

#3400 fix(efb): Fix display crash on incomplete Metar Data
  src/instruments/src/EFB/Dashboard/Widgets/FlightWidget.tsx
  src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
Labels: QA Tier 1, Tested

#3521 feat: custom chronometer font
  .github/CHANGELOG.md
  A32NX/html_ui/Fonts/AirbusChronometer.ttf
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js
  src/fonts/AirbusChronometer.sfd
Labels: QA Tier 1, Ready to Test

#3407 fix: various simbrief route import failures
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: QA Tier 2, Testing Started

#3471 fix: correct FCU ALT Increment Selector emissive behaviour
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1, Testing Started

#3535 feat: custom RMP font
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg
  A32NX/html_ui/Fonts/AirbusRMP.ttf
  src/fonts/AirbusRMP.sfd
  src/instruments/src/RMP/Components/RadioPanelDisplay.tsx
  src/instruments/src/RMP/style.scss
Labels: QA Tier 1, Tested

#3492 fix: Prevent TCAS STBY warning from appearing in wrong flight phase
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1, Tested

#3515 feat: custom FCU font
  .github/CHANGELOG.md
  A32NX/html_ui/Fonts/AirbusFCU.ttf
  A32NX/html_ui/Fonts/Poppins-SemiBold.ttf
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.js
  src/fonts/AirbusFCU.sfd
  src/fonts/Poppins-SemiBold.sfd
  src/instruments/src/RMP/style.scss
Labels: QA Tier 2, Tested

#3532 fix(sound): pack opening condition
  A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
Labels: QA Tier 1, Tested

#3561 build: fix failing workflows and builds
  .github/workflows/pr.yml
  package.json
  scripts/dev-env/run.cmd
  scripts/dev-env/run.sh
  scripts/setup.sh
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/index.jsx
Labels: QA Tier 1, Tested

#3526 fix(mcdu): incorrect display center runway on flightplan page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: QA Tier 2, Tested

#3564 fix: Quick flight model fix for 1.13.16.0
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Labels: QA Tier 3, Tested

#3572 fix(efb): loading bar reset & delay 🚀
  src/instruments/src/EFB/Assets/Efb.scss
Labels: QA Tier 1, Tested

#3598 fix: ignition switch "MODE NORM" on Final
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
Labels: QA Tier 1, Tested

#3590 fix: change starting position of dome lights on runway
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT
Labels: QA Tier 1, Tested

#3620 fix: add brake fan memo
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1, Ready to Test

#3582 feat: custom BAT font
  .github/CHANGELOG.md
  A32NX/html_ui/Fonts/AirbusBAT.ttf
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.js
  src/fonts/AirbusBAT.sfd
Labels: QA Tier 1, Tested

#3557 fix(mcdu): empty sids when scrolling on departures page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
Labels: QA Tier 1, Tested

#3597 fix(lights): final/approach/cruise DOME lights being turned ON (on spawn)
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT
Labels: QA Tier 1, Tested

#3577 fix: windshield wipers animation
  A32NX/ModelBehaviorDefs/A32NX/A32NX_Exterior.xml
Labels: QA Tier 1, Testing Started

#3446 fix(mcdu): check to data
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#3599 fix(cdu): ILS frequency autofill
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: QA Tier 2, Tested

#3500 build: switch to separate msfs rollup plugin
  package.json
  src/instruments/rollup.config.js
  src/instruments/template/rollup.js
  src/instruments/template/template.html
  src/instruments/template/template.js
Labels: QA Tier 1

#3659 feat(sound): add custom sounds to multiple buttons and throttle lever reverse locks
  .github/CHANGELOG.md
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml
  src/behavior/src/A32NX_Interior_Engine.xml
  src/behavior/src/A32NX_Interior_Misc.xml
Labels: QA Tier 1, Tested

#3650 feat: custom honeywell MCDU font
  .github/CHANGELOG.md
  A32NX/html_ui/Fonts/HoneywellMCDU.ttf
  A32NX/html_ui/Fonts/HoneywellMCDUSmall.ttf
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
Labels: QA Tier 1, Testing Started

#3563 fix: Fix issues with update throttler
  A32NX/html_ui/JS/A32NX_Util.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
  A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
Labels: QA Tier 2, Testing Started

#3574 fix(gpws): "too low terrain" warning on 2nd departure
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Labels: QA Tier 1, Tested

#3281 feat: add altitude C chord warning sounds
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml
  A32NX/html_ui/Pages/A32NX_Core/A32NX_FWC.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Labels: QA Tier 2, Tested

#3573 refactor(mcdu): RADNAV (part 2)
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
Labels: QA Tier 2, Tested

#3382 refactor(ecam): start moving individual pages to ReactJS
  .eslintignore
  A32NX/ModelBehaviorDefs/A32NX/Airbus.xml
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.js
  src/behavior/src/A32NX_Interior_Misc.xml
  src/instruments/ecam-page-template/rollup.js
  src/instruments/ecam-page-template/template.html
  src/instruments/ecam-page-template/template.js
  src/instruments/rollup.config.js
  src/instruments/src/Common/definitions.scss
  src/instruments/src/EWD/config.json
  src/instruments/src/EWD/index.jsx
  src/instruments/src/EWD/style.scss
  src/instruments/src/SD/Common/definitions.scss
  src/instruments/src/SD/Pages/Apu.jsx
  src/instruments/src/SD/Pages/Bleed.jsx
  src/instruments/src/SD/Pages/Cond.jsx
  src/instruments/src/SD/Pages/Cond/Cond.jsx
  src/instruments/src/SD/Pages/Cond/Cond.scss
  src/instruments/src/SD/Pages/Door/Door.jsx
  src/instruments/src/SD/Pages/Door/Door.scss
  src/instruments/src/SD/Pages/Door/config.json
  src/instruments/src/SD/Pages/Elec.jsx
  src/instruments/src/SD/Pages/Eng.jsx
  src/instruments/src/SD/Pages/Fctl.jsx
  src/instruments/src/SD/Pages/Fuel.jsx
  src/instruments/src/SD/Pages/Hyd.jsx
  src/instruments/src/SD/Pages/Press.jsx
  src/instruments/src/SD/Pages/Wheel.jsx
  src/instruments/src/SD/PagesContainer.jsx
  src/instruments/src/SD/StatusArea/StatusArea.jsx
  src/instruments/src/SD/StatusArea/StatusArea.scss
  src/instruments/src/SD/Text/Text.jsx
  src/instruments/src/SD/Text/Text.scss
  src/instruments/src/SD/config.json
  src/instruments/src/SD/index.jsx
  src/instruments/src/SD/style.scss
  src/instruments/src/util.mjs
  src/instruments/template/rollup.js
  typings/asobo-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/BaseAirliners.d.ts
Labels: QA Tier 1, Tested

#3702 feat(camera): added new interior views
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cameras.cfg
Labels: QA Tier 1, Tested

#3725 feat(apu): realistic stopping N and EGT decrease
  src/systems/systems/src/apu/APS3200.md
  src/systems/systems/src/apu/aps3200.rs
Labels: QA Tier 1, Ready to Test

#3735 fix(ecam): fix broken ECAM page lights
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseAirliners.js
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
Labels: QA Tier 1, Tested

#3675 refactor: React transponder
  A32NX/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/ATC/A320_Neo_ATC.css
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/ATC/A320_Neo_ATC.html
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/ATC/A320_Neo_ATC.js
  src/behavior/src/A32NX_Interior_ATC.xml
  src/behavior/src/A32NX_Interior_Misc.xml
  src/instruments/src/ATC/config.json
  src/instruments/src/ATC/index.tsx
  src/instruments/src/ATC/style.scss
Labels: QA Tier 2, Tested

#3691 feat(lights): add ambient light to the cockpit
  .github/CHANGELOG.md
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/systems.cfg
  A32NX/effects/LIGHT_A32NX_CockpitMinimalAmbiantLarge.fx
Labels: QA Tier 2, Tested

#3684 feat: attach tiller plate emissive to a potentiometer
  A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1, Tested

#3746 fix(mcdu): fix incorrect trip wind value handling on INIT-B page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#3504 fix: Upper ECAM STS
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html
Labels: QA Tier 1, Tested

#3748 fix: PFD missing function
  A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Labels: QA Tier 2, Tested

#3728 refactor(ecam): add useSimVars to DOOR/OXY page
  .github/CHANGELOG.md
  A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  src/instruments/ecam-page-template/template.js
  src/instruments/src/SD/Pages/Door/Door.scss
  src/instruments/src/SD/Pages/Door/Door.tsx
  src/instruments/src/SD/Pages/Door/config.json
  src/instruments/src/SD/PagesContainer.jsx
Labels: QA Tier 1, Tested
