Repository flybywiresim/aircraft, pull requests merged in 2021-09, with the labels that each got.

#5763 fix: pack sounds use new apu speed variable
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
Labels: Audio

#5792 feat: grid-layout same sized buttons on failure page
  .github/CHANGELOG.md
  src/instruments/src/EFB/Failures/FailureButton.tsx
  src/instruments/src/EFB/Failures/Failures.tsx
Labels: EFB, QA Tier 1

#5803 fix(pfd): correct roll indicator triangle height
  src/instruments/src/PFD/AttitudeIndicatorFixed.tsx
Labels: QA Tier 1

#5775 feat(efb): in-flight refueling capabilities
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
  src/instruments/src/EFB/Components/Form/Select.tsx
  src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
Labels: EFB, QA Tier 1

#5804 fix(adirs): use heading as track at low ground speeds
  .github/CHANGELOG.md
  src/systems/systems/src/navigation/adirs.rs
Labels: QA Tier 1

#5811 fix(pfd): fix mach number flickering between mach 0.45 and 0.5
  .github/CHANGELOG.md
  src/instruments/src/PFD/SpeedIndicator.tsx
  src/instruments/src/PFD/index.tsx
Labels: QA Tier 1

#5807 fix(ecam): drop redundant CABIN READY memo
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1, FWS

#5790 fix(fmgc): Sync FMGC go around flight phase with AP state
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
Labels: QA Tier 1

#5547 fix: updated flight model weights and balance
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Boarding.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Core.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadConstructor.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_Menu.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
Labels: Flight Model, QA Tier 2

#5809 fix: Update max passenger number on EFB Dispatch Overview page
  src/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
Labels: Tested, EFB, QA Tier 1

#5808 fix: changelog for previous PR and change cabin ready sound logic
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
Labels: QA Tier 1

#5781 feat: AP and FBW improvements v2
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  src/fbw/build.sh
  src/fbw/src/FlightDataRecorder.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/interface/SimConnectData.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/interface/SimConnectInterface.h
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/AutopilotLaws.h
  src/fbw/src/model/AutopilotLaws_data.cpp
  src/fbw/src/model/AutopilotLaws_types.h
  src/fbw/src/model/AutopilotStateMachine.cpp
  src/fbw/src/model/AutopilotStateMachine.h
  src/fbw/src/model/AutopilotStateMachine_data.cpp
  src/fbw/src/model/AutopilotStateMachine_types.h
  src/fbw/src/model/Autothrust.cpp
  src/fbw/src/model/FlyByWire.cpp
  src/fbw/src/model/FlyByWire.h
  src/fbw/src/model/FlyByWire_data.cpp
  src/fbw/src/model/mod_lHmooAo5.cpp
  src/fbw/src/model/mod_lHmooAo5.h
  src/fdr2csv/src/FlightDataRecorderConverter.cpp
  src/fdr2csv/src/main.cpp
  src/instruments/src/PFD/AttitudeIndicatorFixed.tsx
  src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
Labels: QA Tier 2

#5813 refactor(efb/mcdu): move simbrief username input out of mcdu
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_SIMBRIEF.js
  src/instruments/src/EFB/Components/Form/SimpleInput/SimpleInput.tsx
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
  src/instruments/src/EFB/SimbriefApi/simbriefParser.ts
Labels: QA Tier 1

#5848 fix: Change GPS ground speed on MCDU Data GPS Monitor page from meters/second to knots
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_GPSMonitor.js
Labels: QA Tier 1

#5806 refactor(engine): FADEC and fuel consumption code overall clean-up
  .github/CHANGELOG.md
  src/fadec/src/EngineControl.h
  src/fadec/src/FadecGauge.cpp
  src/fadec/src/FadecGauge.h
  src/fadec/src/RegPolynomials.h
  src/fadec/src/SimVars.h
  src/fadec/src/Tables.h
  src/fadec/src/common.h
Labels: QA Tier 1

#5842 feat(fbw): improved speed dependent roll law model
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  src/fbw/src/model/FlyByWire.cpp
  src/fbw/src/model/FlyByWire.h
  src/fbw/src/model/FlyByWire_data.cpp
Labels: QA Tier 2

#5902 refactor(efb/mcdu): move telex prompt out of MCDU and changes to PopUp class
  flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MenuPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_Menu.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js
  src/instruments/src/EFB/Settings/Settings.tsx
  src/shared/src/popup.ts
Labels: QA Tier 1

#5936 fix(hyd): wrong acceleration coordinates causing autobrake fail
  src/systems/systems/src/simulation/update_context.rs
Labels: Critical Bug, QA Tier 1
