Repository flybywiresim/aircraft, pull requests merged in 2021-06, with the labels that each got.

#4888 fix: centre fuel pump 2 fault annunciator light
  .github/CHANGELOG.md
  src/model/build.js
  src/model/models.json
Labels: Need in ME Fork, QA Tier 1, Tested

#4912 feat(apu): ecb powered by dc bat bus
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
  src/systems/a320_hydraulic_simulation_graphs/src/main.rs
  src/systems/a320_systems/src/electrical/alternating_current.rs
  src/systems/a320_systems/src/electrical/direct_current.rs
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/a320_systems/src/hydraulic.rs
  src/systems/a320_systems/src/lib.rs
  src/systems/a320_systems/src/power_consumption.rs
  src/systems/systems/src/apu/air_intake_flap.rs
  src/systems/systems/src/apu/aps3200.rs
  src/systems/systems/src/apu/electronic_control_box.rs
  src/systems/systems/src/apu/mod.rs
  src/systems/systems/src/electrical/battery.rs
  src/systems/systems/src/electrical/consumption.rs
  src/systems/systems/src/electrical/emergency_generator.rs
  src/systems/systems/src/electrical/engine_generator.rs
  src/systems/systems/src/electrical/external_power_source.rs
  src/systems/systems/src/electrical/mod.rs
  src/systems/systems/src/electrical/static_inverter.rs
  src/systems/systems/src/electrical/transformer_rectifier.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/pneumatic/mod.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/mod.rs
  src/systems/systems/src/simulation/test.rs
Labels: QA Tier 1, Tested

#4986 feat: APU heat blur
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/aircraft.cfg
Labels: QA Tier 1, Tested

#4935 fix(mcdu): Improve bearing/distance code
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#4991 feat: add custom font file for RTPI
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Fonts/AirbusRTPI.ttf
  src/fonts/AirbusRTPI.sfd
  src/instruments/src/RTPI/index.tsx
  src/instruments/src/RTPI/style.scss
Labels: QA Tier 1, Tested

#5002 feat: added lvar if ground spoilers are active
  docs/a320-simvars.md
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
Labels: QA Tier 1, Ready to Test

#5003 fix(efb): Fix for missing icons in EFB Map
  package.json
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
  src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
Labels: QA Tier 1, Tested

#4998 refactor: replace f64::MIN with values closer to 0
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/a320_systems/src/fuel.rs
  src/systems/a320_systems/src/hydraulic.rs
  src/systems/systems/src/apu/electronic_control_box.rs
  src/systems/systems/src/apu/mod.rs
  src/systems/systems/src/electrical/battery_charge_limiter.rs
  src/systems/systems/src/electrical/consumption.rs
  src/systems/systems/src/electrical/engine_generator.rs
  src/systems/systems/src/electrical/external_power_source.rs
  src/systems/systems/src/electrical/mod.rs
  src/systems/systems/src/engine/leap_engine.rs
  src/systems/systems/src/hydraulic/brake_circuit.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/landing_gear/mod.rs
  src/systems/systems/src/overhead/mod.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/mod.rs
  src/systems/systems/src/simulation/update_context.rs
Labels: QA Tier 1, Tested

#5004 feat: improved ROLLOUT and AP disengage conditions + improved ground spoiler logic
  .github/CHANGELOG.md
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/SpoilersHandler.cpp
  src/fbw/src/SpoilersHandler.h
  src/fbw/src/model/AutopilotStateMachine.cpp
  src/fbw/src/model/AutopilotStateMachine.h
Labels: QA Tier 1, Tested

#5023 fix: corrected THR LK activation (#5020)
  .github/CHANGELOG.md
  src/fbw/src/model/Autothrust.cpp
Labels: QA Tier 1, Ready to Test

#5025 feat: support FD off take-off procedure (#5016)
  .github/CHANGELOG.md
  src/fbw/src/FlightDataRecorder.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/model/Autothrust.cpp
  src/fbw/src/model/Autothrust.h
  src/fbw/src/model/Autothrust_data.cpp
  src/fbw/src/model/Autothrust_types.h
  src/fdr2csv/src/FlightDataRecorderConverter.cpp
  src/fdr2csv/src/main.cpp
Labels: QA Tier 1, Ready to Test

#5044 fix(mcdu): init-a tropo entry validation
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#5047 feat: improved managed speed validity + VS speed protection and LOC/GS arm fix
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fbw/src/model/AutopilotStateMachine.cpp
Labels: QA Tier 1, Ready to Test

#4381 fix(model): reverser animation
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Exterior/A32NX_Exterior_Includes.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  src/behavior/src/A32NX_Exterior_Engines.xml
Labels: QA Tier 1, Ready to Test

#5049 feat: init FCU with correct default values and improved flight / plane load for alpha protection
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  src/fbw/src/model/FlyByWire.cpp
Labels: QA Tier 1, Tested

#5062 fix: synchronising park brake lever value from sim
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  src/systems/a320_systems_wasm/src/lib.rs
Labels: QA Tier 1, Ready to Test

#4663 fix: use sensible defaults for non configured throttles
  src/fbw/src/ThrottleAxisMapping.cpp
Labels: QA Tier 1, Tested, Waiting For Response

#5075 fix(ecam): Hide REFUELG immediately once refueling is complete
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
Labels: QA Tier 1, Tested

#5084 fix(mcdu): perf page thr red/acc alt entry validation
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: True to Life

#4973 feat: ils auto-tuning for departure and approach
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/Waypoint.js
Labels: QA Tier 2, Tested

#5046 feat(mcdu): scratchpad clear on clr held
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  src/behavior/src/A32NX_Interior_MCDU.xml
Labels: QA Tier 1, Tested

#4646 fix(mcdu): performance page refresh on flight phase transition
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#5096 fix: permanent A/THR disconnect with 3D button on thrust lever
  .github/CHANGELOG.md
  docs/a320-events.md
  docs/a320-simvars.md
  src/behavior/src/A32NX_Interior_Autopilot.xml
  src/fbw/src/FlightDataRecorder.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/interface/SimConnectData.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/interface/SimConnectInterface.h
  src/fbw/src/model/Autothrust.cpp
  src/fbw/src/model/Autothrust_data.cpp
  src/fbw/src/model/Autothrust_types.h
  src/fdr2csv/src/FlightDataRecorderConverter.cpp
  src/fdr2csv/src/main.cpp
Labels: QA Tier 1, Ready to Test

#5059 fix(nd): TCAS symbols correctly display in all nav/rose views, fixed TCAS related TypeError exception to console
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_TCAS.js
Labels: QA Tier 1, Tested

#5048 feat(fmgc): re-initialization of fmgc variables after landing
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Labels: QA Tier 1, Tested

#5106 feat(efb): Add flypad themed simbrief maps to EFB/OFP
  .github/CHANGELOG.md
  src/instruments/src/EFB/Assets/Efb.scss
Labels: QA Tier 1, Ready to Test

#5081 feat(engine): Cold Start - Primary Parameters
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  src/fadec/src/EngineControl.h
  src/fadec/src/FadecGauge.h
  src/fadec/src/RegPolynomials - Cubic.h
  src/fadec/src/RegPolynomials.h
  src/fadec/src/SimVars.h
  src/fadec/src/common.h
  src/fbw/src/EngineData.h
  src/fbw/src/FlightDataRecorder.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fdr2csv/src/FlightDataRecorderConverter.cpp
  src/fdr2csv/src/main.cpp
Labels: QA Tier 1, Ready to Test

#5027 feat: Refined gear/flap drag increments
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
Labels: QA Tier 2, Testing Started

#5118 fix: Fix falsy SimVar values not being persisted properly
  src/instruments/src/Common/persistence.tsx
Labels: QA Tier 1, Tested

#5104 fix(efb): state persistence update for landing perf
  package.json
  src/instruments/src/EFB/Components/Form/SelectInput/SelectInput.tsx
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx
  src/instruments/src/EFB/Store/performance-context.ts
Labels: QA Tier 1, Ready to Test

#4919 feat: EFB page with the list of ATCs from VATSIM and IVAO
  package.json
  src/instruments/src/EFB/ATC/ATC.tsx
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
  src/instruments/src/EFB/ToolBar/ToolBar.tsx
Labels: QA Tier 1, Tested

#5067 feat(eicas): Show ISA DEV on EICAS
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#5137 fix(aoc): WX Request airport list handling
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_AirportList.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested, True to Life

#5120 feat: added ECAM warning THR LEVERS NOT SET
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  src/fbw/src/FlightDataRecorder.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/model/AutopilotStateMachine.cpp
  src/fbw/src/model/AutopilotStateMachine.h
  src/fbw/src/model/Autothrust.cpp
  src/fbw/src/model/Autothrust.h
  src/fbw/src/model/Autothrust_data.cpp
  src/fbw/src/model/Autothrust_types.h
  src/fdr2csv/src/FlightDataRecorderConverter.cpp
  src/fdr2csv/src/main.cpp
Labels: QA Tier 1

#5146 feat(atsu): auto print when printer selected
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js
Labels: QA Tier 1, Tested

#4911 fix(hyd): blue epump override changed to momentary
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/systems/a320_systems/src/hydraulic.rs
  src/systems/systems/src/overhead/mod.rs
Labels: QA Tier 1

#5180 refactor(mcdu): remove simbrief username conversion
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Labels: QA Tier 1

#4902 feat(mcdu): qol improvement - keyboard input to mcdu scratchpad
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_MCDU_KB.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_REALISM.js
  src/behavior/src/A32NX_Interior_MCDU.xml
Labels: QA Tier 1, Tested

#5188 build(wasm): optimise in-game build time
  Cargo.toml
  igniter.config.mjs
  src/fadec/build.sh
  src/fbw/build.sh
Labels: QA Tier 1

#5115 feat(isis): ISIS auto brightness
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js
Labels: QA Tier 1, Testing Started

#5197 refactor(apu): move logic to rust
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_APU.js
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/mod.rs
  src/systems/systems_wasm/src/electrical.rs
  src/systems/systems_wasm/src/lib.rs
Labels: QA Tier 1

#5154 fix(fmgc): improve ils auto-tuning
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 2

#5192 refactor(mcdu): housekeeping
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Testing Started

#5143 fix(mcdu): multiple small changes for re-initialization
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#5170 feat(ecam): Show 'REV' in amber while reverser doors are in transit
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1

#5018 feat: chrono auto brightness
  .github/CHANGELOG.md
  src/instruments/src/Clock/index.tsx
  src/instruments/src/Clock/style.scss
Labels: QA Tier 1, Testing Started

#5236 fix(fmgc): flight phase initialization
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Testing Started
