Repository flybywiresim/aircraft, pull requests merged in 2021-05, with the labels that each got.

#4628 feat(elec): gen 1 line
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  src/systems/a320_systems/src/electrical/alternating_current.rs
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/a320_systems/src/lib.rs
Labels: QA Tier 1, Tested

#4544 feat(elec): ground service buses
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
  src/systems/a320_systems/src/electrical/alternating_current.rs
  src/systems/a320_systems/src/electrical/direct_current.rs
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/a320_systems/src/power_consumption.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/electrical/mod.rs
  src/systems/systems/src/electrical/transformer_rectifier.rs
Labels: QA Tier 1, Tested

#4678 feat: improved ROLLOUT and G/S laws
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/AutopilotLaws.h
  src/fbw/src/model/AutopilotLaws_data.cpp
Labels: QA Tier 2, Ready to Test

#4279 fix: TAS and Wind Info Behaviours on Take Off and inflight
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A320_Neo_MFD.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A32NX_NDInfo.js
Labels: QA Tier 1, Tested

#4658 fix(engine): fuel flow and fuel consumption model
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  src/fadec/src/EngineControl.h
  src/fadec/src/FadecGauge.h
  src/fadec/src/SimVars.h
Labels: QA Tier 2, Ready to Test

#4673 feat(sound): add wwise events to glareshield chrono buttons
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
Labels: QA Tier 1, Tested

#4629 fix(mcdu): empty atis request
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js
Labels: QA Tier 1, Tested

#4679 feat: added AOA and high-speed protection
  .github/CHANGELOG.md
  docs/README.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.xml
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Speeds.js
  src/fbw/src/FlightDataRecorder.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/SpoilersHandler.cpp
  src/fbw/src/SpoilersHandler.h
  src/fbw/src/interface/SimConnectData.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/interface/SimConnectInterface.h
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/AutopilotLaws.h
  src/fbw/src/model/AutopilotLaws_data.cpp
  src/fbw/src/model/AutopilotStateMachine.cpp
  src/fbw/src/model/AutopilotStateMachine.h
  src/fbw/src/model/AutopilotStateMachine_data.cpp
  src/fbw/src/model/Autothrust.cpp
  src/fbw/src/model/Autothrust.h
  src/fbw/src/model/Autothrust_data.cpp
  src/fbw/src/model/Autothrust_types.h
  src/fbw/src/model/FlyByWire.cpp
  src/fbw/src/model/FlyByWire.h
  src/fbw/src/model/FlyByWire_data.cpp
  src/fbw/src/model/FlyByWire_types.h
  src/fdr2csv/src/FlightDataRecorderConverter.cpp
  src/fdr2csv/src/main.cpp
  src/instruments/src/PFD/FMA.jsx
  src/instruments/src/PFD/SpeedIndicator.jsx
  src/instruments/src/PFD/animations.scss
  src/instruments/src/PFD/index.jsx
Labels: QA Tier 3, Testing Started

#4567 feat(checklist): add missing or fix incorrect highlights
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Airbus_A320neo_Checklist.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Library.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_ATC.xml
  src/behavior/src/A32NX_Interior_MCDU.xml
Labels: QA Tier 1, Tested

#4717 fix: removed unusable fuel from refueling
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
  src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
Labels: QA Tier 1, Ready to Test

#4732 fix: robustness of protection activation with engaged AP
  src/fbw/src/model/FlyByWire.cpp
  src/fbw/src/model/FlyByWire.h
  src/fbw/src/model/FlyByWire_data.cpp
Labels: QA Tier 1, Ready to Test

#4724 fix(elec): 2xb contactors closing condition
  src/systems/a320_systems/src/electrical/alternating_current.rs
  src/systems/a320_systems/src/electrical/direct_current.rs
  src/systems/a320_systems/src/electrical/mod.rs
Labels: QA Tier 1, Tested

#4746 fix: ensure that on_ground always inhibits alpha floor (e.g. after using slew)
  src/fbw/src/model/FlyByWire.cpp
Labels: QA Tier 1, Ready to Test

#4687 feat(fmgc): des init via fcu vs knob
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/behavior/src/A32NX_Interior_FCU.xml
Labels: QA Tier 2, Tested

#4702 refactor(ecam): convert elec page to react
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Library.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Elec.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Elec.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.css
  src/behavior/src/A32NX_Interior_Elec.xml
  src/instruments/rollup.config.js
  src/instruments/src/BAT/index.tsx
  src/instruments/src/SD/Common/PageTitle.scss
  src/instruments/src/SD/Common/PageTitle.tsx
  src/instruments/src/SD/Pages/Elec.jsx
  src/instruments/src/SD/Pages/Elec/Elec.scss
  src/instruments/src/SD/Pages/Elec/Elec.tsx
  src/instruments/src/SD/Pages/Elec/config.json
  src/instruments/src/SD/PagesContainer.jsx
  src/systems/a320_systems/src/electrical/direct_current.rs
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/systems/src/electrical/mod.rs
Labels: QA Tier 1, Ready to Test

#4748 feat: realistic rudder pedal animation
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_Handling.xml
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
Labels: QA Tier 2, Ready to Test

#4749 feat: added more events for better interface to FCU
  .github/CHANGELOG.md
  docs/FSUIPC/flybywire-aircraft-a320-neo.evt
  docs/SPAD.neXt/flybywire-aircraft-a320-neo.xml
  docs/a320-events.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/interface/SimConnectInterface.h
Labels: QA Tier 2, Ready to Test

#2854 feat: rework autobrake keybindings
  .github/CHANGELOG.md
  src/behavior/src/A32NX_Interior_Misc.xml
Labels: QA Tier 1, Tested

#4769 fix: make brakes available when engines are off
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
Labels: QA Tier 1, Tested

#4775 feat: improved and custom rudder and elevator trim
  .github/CHANGELOG.md
  src/behavior/src/A32NX_Interior_Handling.xml
  src/fbw/build.sh
  src/fbw/src/ElevatorTrimHandler.cpp
  src/fbw/src/ElevatorTrimHandler.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/RateLimiter.h
  src/fbw/src/RudderTrimHandler.cpp
  src/fbw/src/RudderTrimHandler.h
  src/fbw/src/interface/SimConnectData.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/interface/SimConnectInterface.h
  src/fbw/src/model/FlyByWire_data.cpp
  src/fdr2csv/src/FlightDataRecorderConverter.cpp
Labels: QA Tier 2, Testing Started

#4040 fix: seatbelt sign sync to fsuipc
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Library.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1, Tested

#3782 feat: First hydraulic system implementation
  .github/CHANGELOG.md
  .gitignore
  Cargo.lock
  Cargo.toml
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  src/systems/a320_hydraulic_simulation_graphs/Cargo.toml
  src/systems/a320_hydraulic_simulation_graphs/src/main.rs
  src/systems/a320_systems/Cargo.toml
  src/systems/a320_systems/src/hydraulic.rs
  src/systems/a320_systems/src/lib.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/apu/air_intake_flap.rs
  src/systems/systems/src/apu/aps3200.rs
  src/systems/systems/src/engine/leap_engine.rs
  src/systems/systems/src/engine/mod.rs
  src/systems/systems/src/hydraulic/brake_circuit.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/study/Docs/Knowledge_Data_Base.xlsx
  src/systems/systems/src/hydraulic/study/test_Hy_CompConcept.m
  src/systems/systems/src/hydraulic/study/test_Hy_CompConcept_V2.m
  src/systems/systems/src/overhead/mod.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/test.rs
  src/systems/systems/src/simulation/update_context.rs
Labels: QA Tier 2, Ready to Test

#4736 feat: ISIS brightness buttons push&hold
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js
Labels: QA Tier 1, Ready to Test

#4788 fix: remove invalid chars from atis report
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsMessage.js
Labels: QA Tier 1, Ready to Test

#4797 feat: ISIS brightness buttons push&hold #4736
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js
Labels: QA Tier 1, Tested

#4811 refactor(xml): small xml refactoring
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Exterior.xml
  src/behavior/src/A32NX_Interior_Generics.xml
Labels: QA Tier 1

#4807 fix: #4795 and other transition improvements
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  src/fbw/src/model/AutopilotStateMachine.cpp
  src/fbw/src/model/AutopilotStateMachine.h
Labels: QA Tier 1, Ready to Test

#4817 feat: allow V/S being pushed to level off in APPR
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  src/fbw/src/model/AutopilotStateMachine.cpp
Labels: QA Tier 1, Ready to Test

#4824 feat: improved speed control for OP CLB/DES and A/THR
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/Autothrust.cpp
  src/fbw/src/model/Autothrust.h
  src/fbw/src/model/Autothrust_data.cpp
Labels: QA Tier 1, Ready to Test

#4555 fix(fmgc): pre-selected speeds
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/instruments/src/PFD/index.jsx
Labels: QA Tier 2, Tested

#4647 fix(mcdu): empty weather request
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js
Labels: QA Tier 1, Tested

#4850 feat(elec): eng fire and gen buttons affect idg
  .github/CHANGELOG.md
  Cargo.lock
  src/systems/a320_systems/Cargo.toml
  src/systems/a320_systems/src/electrical/alternating_current.rs
  src/systems/a320_systems/src/electrical/direct_current.rs
  src/systems/a320_systems/src/electrical/galley.rs
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/a320_systems/src/hydraulic.rs
  src/systems/a320_systems/src/lib.rs
  src/systems/systems/src/apu/air_intake_flap.rs
  src/systems/systems/src/apu/electronic_control_box.rs
  src/systems/systems/src/apu/mod.rs
  src/systems/systems/src/electrical/battery.rs
  src/systems/systems/src/electrical/battery_charge_limiter.rs
  src/systems/systems/src/electrical/consumption.rs
  src/systems/systems/src/electrical/emergency_generator.rs
  src/systems/systems/src/electrical/engine_generator.rs
  src/systems/systems/src/electrical/external_power_source.rs
  src/systems/systems/src/electrical/mod.rs
  src/systems/systems/src/electrical/static_inverter.rs
  src/systems/systems/src/electrical/transformer_rectifier.rs
  src/systems/systems/src/engine/leap_engine.rs
  src/systems/systems/src/engine/mod.rs
  src/systems/systems/src/landing_gear/mod.rs
  src/systems/systems/src/pneumatic/mod.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/test.rs
Labels: QA Tier 1, Ready to Test

#4826 fix(fmgc): descent initiation and crz fl change
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 2, Testing Started

#4829 feat: improved OP CLB/DES, CLB/DES speed hold characteristic
  .github/CHANGELOG.md
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/AutopilotLaws.h
  src/fbw/src/model/AutopilotLaws_data.cpp
Labels: QA Tier 2, Testing Started

#4857 fix: model script issues
  src/model/brkfan/brkfan.gltf
  src/model/build.js
  src/model/onbat/onbat.gltf
Labels: QA Tier 1, Tested

#4864 fix(mcdu): sometimes bad crz fl validation
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Tested

#4739 refactor(ecam): f/ctl
  src/instruments/src/SD/Common/EcamPage.tsx
  src/instruments/src/SD/Common/SvgGroup.tsx
  src/instruments/src/SD/Pages/Elec/Elec.tsx
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
Labels: QA Tier 1, Tested

#4870 feat: F/CTL page hydraulic indications, small misc changes to F/CTL page
  .github/CHANGELOG.md
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
Labels: QA Tier 1, Tested

#4750 refactor: instruments build and framework cleanup
  .eslintignore
  .eslintrc
  .gitignore
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  igniter.config.mjs
  package.json
  src/.eslintrc.js
  src/instruments/buildSrc/browserBuild.mjs
  src/instruments/buildSrc/directories.mjs
  src/instruments/buildSrc/igniter/tasks.mjs
  src/instruments/buildSrc/igniter/worker.mjs
  src/instruments/buildSrc/plugins.mjs
  src/instruments/buildSrc/simulatorBuild.mjs
  src/instruments/buildSrc/templatePlugins.mjs
  src/instruments/devServer/index.html
  src/instruments/devServer/js/loader.js
  src/instruments/devServer/styles.css
  src/instruments/ecam-page-template/rollup.js
  src/instruments/ecam-page-template/template.html
  src/instruments/rollup.config.js
  src/instruments/src/ATC/index.tsx
  src/instruments/src/BAT/index.tsx
  src/instruments/src/Clock/Components/Clock.tsx
  src/instruments/src/Clock/Components/ElapsedTime.tsx
  src/instruments/src/Clock/index.tsx
  src/instruments/src/Common/defaults.ts
  src/instruments/src/Common/displayUnit.tsx
  src/instruments/src/Common/hooks.tsx
  src/instruments/src/Common/simVars.tsx
  src/instruments/src/EFB/Settings/sync.ts
  src/instruments/src/PFD/index.jsx
  src/instruments/src/RMP/Components/BaseRadioPanels.tsx
  src/instruments/src/util.js
  src/instruments/tsconfig.json
  src/shared/src/persistence.ts
  src/tsconfig.json
Labels: QA Tier 1, Ready to Test

#4892 feat(PFD): flashing of STD/QNH at TL/TA
  .github/CHANGELOG.md
  src/instruments/src/PFD/AltitudeIndicator.jsx
Labels: QA Tier 1, Testing Started

#4903 feat: aileron droop and anti-droop
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  src/behavior/src/A32NX_Exterior.xml
  src/fbw/build.sh
  src/fbw/src/AnimationAileronHandler.cpp
  src/fbw/src/AnimationAileronHandler.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/SpoilersHandler.cpp
  src/fbw/src/SpoilersHandler.h
  src/fbw/src/interface/SimConnectData.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
Labels: QA Tier 1, Ready to Test

#4847 feat(ecam): hydraulics page
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  src/instruments/buildSrc/igniter/tasks.mjs
  src/instruments/buildSrc/simulatorBuild.mjs
  src/instruments/src/SD/Pages/Hyd.jsx
  src/instruments/src/SD/Pages/Hyd/Hyd.scss
  src/instruments/src/SD/Pages/Hyd/Hyd.tsx
  src/instruments/src/SD/Pages/Hyd/common.tsx
  src/instruments/src/SD/Pages/Hyd/config.json
  src/instruments/src/SD/PagesContainer.jsx
Labels: Need in ME Fork, QA Tier 1, Ready to Test

#4909 fix: flap transition bounces in SU4
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
Labels: Need in ME Fork, QA Tier 1, Ready to Test

#4930 feat: force usage of modern flight model
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
Labels: Need in ME Fork, QA Tier 1, Tested

#4898 feat(lights): add ANN LT DIM functionality
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/A32NX_BaseAirliners.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  src/behavior/src/A32NX_Interior_Fire.xml
  src/behavior/src/A32NX_Interior_Generics.xml
  src/behavior/src/A32NX_Interior_Misc.xml
  src/behavior/src/A32NX_Interior_RMP.xml
  src/instruments/src/ATC/index.tsx
  src/instruments/src/BAT/index.tsx
  src/instruments/src/Clock/Components/Chrono.tsx
  src/instruments/src/Clock/Components/Clock.tsx
  src/instruments/src/Clock/Components/ElapsedTime.tsx
  src/instruments/src/Common/simVars.tsx
  src/instruments/src/RMP/Components/RadioPanelDisplay.tsx
  src/instruments/src/RTPI/index.tsx
Labels: QA Tier 1, Tested

#4783 refactor(ecam): wheel to react
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js
  src/instruments/buildSrc/igniter/tasks.mjs
  src/instruments/buildSrc/simulatorBuild.mjs
  src/instruments/src/SD/Common/ComponentPositionProps.ts
  src/instruments/src/SD/Common/ComponentSidePositionProps.ts
  src/instruments/src/SD/Common/HydraulicIndicator.scss
  src/instruments/src/SD/Common/HydraulicIndicator.tsx
  src/instruments/src/SD/Common/HydraulicSystem.ts
  src/instruments/src/SD/Common/HydraulicsProvider.tsx
  src/instruments/src/SD/Common/Spoilers.scss
  src/instruments/src/SD/Common/Spoilers.tsx
  src/instruments/src/SD/Common/SvgGroup.tsx
  src/instruments/src/SD/Pages/Elec/Elec.tsx
  src/instruments/src/SD/Pages/Fctl/Fctl.scss
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
  src/instruments/src/SD/Pages/Wheel.jsx
  src/instruments/src/SD/Pages/Wheel/Wheel.scss
  src/instruments/src/SD/Pages/Wheel/Wheel.tsx
  src/instruments/src/SD/Pages/Wheel/config.json
  src/instruments/src/SD/PagesContainer.jsx
Labels: QA Tier 1, Ready to Test

#4936 fix(adirs): ADIRUs not aligned starting on runway
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js
Labels: QA Tier 1, Tested

#4937 fix: pfd qnh flashing
  src/instruments/src/PFD/AltitudeIndicator.jsx
Labels: QA Tier 1, Tested

#4955 chore: replacing XML tooltips, missing id for seatbelt switch
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1, Tested

#4960 build: update to dev-env with SDK 0.13
  Cargo.lock
  scripts/build.sh
  scripts/dev-env/run.cmd
  scripts/dev-env/run.sh
  src/fadec/build.sh
  src/fbw/build.sh
  src/systems/a320_systems/src/lib.rs
  src/systems/systems/src/lib.rs
Labels: QA Tier 1, Ready to Test
