Repository flybywiresim/aircraft, pull requests merged in 2022-03, with the labels that each got.

#6626 fix: Improve frequency of Remote MCDU updates
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AirportsMonitor.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_GPSMonitor.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_IRSStatus.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PositionMonitorPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_FreeText.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_Init.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesReceived.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesSent.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
Labels: QA Tier 2

#6833 fix: Web MCDU Interface fullscreen mode showing background
  src/mcdu-server/client/src/App.jsx
Labels: QA Tier 1

#6837 feat: improved flare behavior in normal law
  src/fbw/src/model/FlyByWire_data.cpp
Labels: Available on Experimental

#6827 fix: path capture tad
  src/fmgc/src/guidance/lnav/transitions/FixedRadiusTransition.ts
  src/fmgc/src/guidance/lnav/transitions/PathCaptureTransition.ts
Labels: Available on Experimental

#6804 fix(fmgc): rebuild constraints
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/Adirs.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_ConstraintManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/flightplanning/WaypointBuilder.ts
  src/fmgc/src/guidance/Geometry.ts
  src/fmgc/src/guidance/lnav/LnavDriver.ts
Labels: QA Tier 2, Available on Experimental

#6790 feat(clk): add simvars for Clock CHR and ET
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/instruments/src/Clock/Components/Chrono.tsx
  src/instruments/src/Clock/Components/ElapsedTime.tsx
Labels: QA Tier 1

#6857 feat(efb): f/o flypad
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/model/efb/flypad.gltf
Labels: QA Tier 1

#6689 feat(hyd): aerodynamic model for moving parts
  .github/CHANGELOG.md
  Cargo.lock
  src/systems/a320_hydraulic_simulation_graphs/Cargo.toml
  src/systems/a320_systems/Cargo.toml
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/Cargo.toml
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/Cargo.toml
  src/systems/systems/src/apu/mod.rs
  src/systems/systems/src/hydraulic/aerodynamic_model.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/simulation/mod.rs
  src/systems/systems/src/simulation/update_context.rs
Labels: Available on Experimental

#6844 fix(fmgc): fix discontinuity guidance logic
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/guidance/lnav/LnavDriver.ts
Labels: QA Tier 1, Available on Experimental

#6887 feat(model): split master warning and caution
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/model/build.js
  src/model/master-warn/master-warn.bin
  src/model/master-warn/master-warn.gltf
  src/model/models.json
Labels: QA Tier 1, Available on Experimental

#6812 fix(fmgc): improve stringing logic
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/guidance/lnav/legs/IF.ts
  src/fmgc/src/types/fstypes/FSTypes.d.ts
Labels: QA Tier 2, Available on Experimental

#6832 feat(hyd): Hydraulic Elevator, Rudder and Spoiler control
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  src/behavior/src/A32NX_Exterior.xml
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/SpoilersHandler.cpp
  src/fbw/src/SpoilersHandler.h
  src/instruments/src/SD/Common/Spoilers.tsx
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
  src/model/models.json
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/src/elevators.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/a320_systems_wasm/src/rudder.rs
  src/systems/a320_systems_wasm/src/spoilers.rs
  src/systems/systems/src/hydraulic/aerodynamic_model.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
Labels: Available on Experimental

#6894 feat: increased resilience of FMGC main loop
  .github/CHANGELOG.md
  src/fmgc/src/guidance/GuidanceController.ts
Labels: QA Tier 1, Available on Experimental

#6876 fix(fuel): turnaround fuel used reset
  src/fadec/src/EngineControl.h
Labels: Available on Experimental

#6895 feat: autopilot improvements
  .github/CHANGELOG.md
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/AutopilotLaws.h
  src/fbw/src/model/AutopilotLaws_data.cpp
  src/fbw/src/model/AutopilotStateMachine.cpp
  src/fbw/src/model/FlyByWire.cpp
  src/fbw/src/model/FlyByWire.h
  src/fbw/src/model/FlyByWire_data.cpp
Labels: QA Tier 1, Available on Experimental

#6881 fix(engine): tuned FADEC Idle N1 calculation
  src/fadec/src/EngineControl.h
  src/fadec/src/Tables.h
Labels: Available on Experimental

#6636 feat(adirs): Improve ADIRS SSM and behaviours
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/instruments/src/PFD/AttitudeIndicatorFixed.tsx
  src/instruments/src/PFD/SpeedIndicator.tsx
  src/instruments/src/PFD/index.tsx
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/navigation/adirs.rs
  src/systems/systems/src/simulation/test.rs
Labels: QA Tier 1

#6877 feat(mcdu): h3 init/fuel pred pages
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MenuPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/CFDS/TEST_INST/EIS/A320_Neo_CDU_CFDS_Test_Inst_EIS_Menu.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/CFDS/TEST_INST/EIS/A320_Neo_CDU_CFDS_Test_Inst_EIS_Tests.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/CFDS/TEST_INST/EIS/A320_Neo_CDU_CFDS_Test_Inst_EIS_Tests_Display.js
Labels: QA Tier 1, Available on Experimental

#6780 feat(mcdu): init a ground temp
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/RawDataMapper.ts
Labels: QA Tier 1

#6891 feat(bleed): attach hydraulic reservoirs to both engine bleeds
  .github/CHANGELOG.md
  src/systems/a320_systems/src/pneumatic.rs
  src/systems/systems/src/simulation/test.rs
Labels: QA Tier 1

#6921 fix(cond): cabin temperature knobs center with scroll
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js
  src/instruments/src/SD/Pages/Cond/Cond.tsx
  src/systems/systems/src/air_conditioning/acs_controller.rs
  src/systems/systems/src/air_conditioning/mod.rs
Labels: QA Tier 1

#6880 fix(efb): metar parser error
  .github/CHANGELOG.md
  src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
  src/instruments/src/EFB/Utils/parseMetar.spec.ts
  src/instruments/src/EFB/Utils/parseMetar.tsx
Labels: EFB, QA Tier 1

#6930 fix(model): add custom cargo hinge model
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/TEXTURE/DECALS_DOOR_CARGO_HINGES_ALBD.PNG.DDS
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/TEXTURE/DECALS_DOOR_CARGO_HINGES_ALBD.PNG.DDS.json
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/TEXTURE/DECALS_DOOR_CARGO_HINGES_COMP.PNG.DDS
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/TEXTURE/DECALS_DOOR_CARGO_HINGES_COMP.PNG.DDS.json
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  src/model/cargo-hinge/cargo-hinge.bin
  src/model/cargo-hinge/cargo-hinge.gltf
  src/model/models.json
Labels: Texture, 3D Model, QA Tier 1

#6870 fix(misc): home cockpit backlight bleed PFD/ND self test
  .github/CHANGELOG.md
  src/instruments/src/Common/displayUnit.tsx
Labels: QA Tier 1

#6903 fix: Update flight model info in fmgc guidance
  .github/CHANGELOG.md
  src/fmgc/src/guidance/vnav/FlightModel.ts
Labels: Available on Experimental

#6701 feat: w&b integration with advanced Simbrief API
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Boarding.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Available on Experimental

#6958 fix: issue with page updating on OFP request
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
Labels: QA Tier 1

#6948 refactor: change ace detection
  src/instruments/buildSrc/plugins.mjs
  src/instruments/src/Common/simVars.tsx
  src/instruments/src/EFB/Components/Form/SimpleInput/SimpleInput.tsx
  typings/types.d.ts
Labels: Tested

#6933 fix(fmgc): handle precision faf constraints correctly
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_WaypointLoader.js
  src/fmgc/src/efis/EfisSymbols.ts
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/LegsProcedure.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/flightplanning/ProcedureDetails.ts
  src/fmgc/src/types/fstypes/FSEnums.ts
  src/fmgc/src/types/fstypes/FSTypes.d.ts
Labels: QA Tier 1, Available on Experimental

#6970 fix: FWC typo
  src/instruments/src/EWD/elements/PseudoFWC.tsx
Labels: QA Tier 1

#6967 fix(ewd): Landing memo no smoking sign logic
  src/instruments/src/EWD/elements/PseudoFWC.tsx
Labels: QA Tier 1, Available on Experimental
