Repository flybywiresim/aircraft, pull requests merged in 2022-06, with the labels that each got.

#7261 fix: same page tab redirection
  src/instruments/src/EFB/Utils/routing.tsx
Labels: QA Tier 1, Exp

#6969 refactor: W&B and boarding logic prep for EFB
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Boarding.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadConstructor.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXUnits.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fadec/src/EngineControl.h
  src/instruments/src/Common/fuel.tsx
  src/instruments/src/EFB/Ground/Pages/FuelPage.tsx
  src/instruments/src/SD/Common/FuelFunctions.tsx
  src/instruments/src/SD/Pages/Eng/Eng.tsx
  src/shared/src/units.ts
Labels: QA Tier 1

#7251 feat(ewd): various E/WD visual improvements
  src/instruments/src/Common/EWDMessageParser.tsx
  src/instruments/src/Common/gauges.tsx
  src/instruments/src/Common/utils.tsx
  src/instruments/src/EWD/elements/ADV.tsx
  src/instruments/src/EWD/elements/DownArrow.tsx
  src/instruments/src/EWD/elements/EGT.tsx
  src/instruments/src/EWD/elements/FF.tsx
  src/instruments/src/EWD/elements/FOB.tsx
  src/instruments/src/EWD/elements/N1.tsx
  src/instruments/src/EWD/elements/N1Limit.tsx
  src/instruments/src/EWD/elements/N2.tsx
  src/instruments/src/EWD/elements/STS.tsx
  src/instruments/src/EWD/elements/Slats.tsx
  src/instruments/src/EWD/elements/UpperDisplay.tsx
  src/instruments/src/EWD/index.tsx
  src/instruments/src/EWD/style.scss
Labels: QA Tier 1, Exp

#7277 fix: incorrect conversion in INIT B
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: QA Tier 1

#7256 fix: info disappearing on atc page when controllers list updates
  src/instruments/src/EFB/ATC/ATC.tsx
Labels: QA Tier 1, Exp

#7259 refactor(mcdu): improved departure/arrival pages
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
Labels: QA Tier 1, Exp

#7282 fix(fws): slats warning during flaps 3 takeoff
  .github/CHANGELOG.md
  src/instruments/src/EWD/elements/PseudoFWC.tsx
Labels: QA Tier 1, Exp

#7281 fix: conversion errors from outdated UI override code
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Boarding.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
  src/fadec/src/EngineControl.h
  src/fadec/src/SimVars.h
Labels: QA Tier 1, Exp

#7280 fix(ISIS): removes ability to change a bug if selected item is Off
  .github/CHANGELOG.md
  src/instruments/src/ISIS/index.tsx
Labels: QA Tier 1, Exp

#7288 feat(elec): make BAT voltmeters update one digit at a time
  .github/CHANGELOG.md
  src/instruments/src/BAT/index.tsx
Labels: Accuracy Checked, QA Tier 1, Exp

#7283 fix: aircraft States - fixed AUTOBRAKE setter LVAR name
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  src/flypad-backend/src/Aircraft/AircraftProcedures.h
  src/flypad-backend/src/Pushback/Pushback.cpp
  src/instruments/src/EFB/Checklists/Lists/Taxi.tsx
Labels: QA Tier 1, Exp

#7221 feat(sfcc): add SFCC output bus words
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/instruments/src/EWD/elements/Slats.tsx
  src/instruments/src/EWD/elements/UpperDisplay.tsx
  src/systems/a320_systems/src/hydraulic/flaps_computer.rs
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/shared/arinc429.rs
  src/systems/systems/src/simulation/mod.rs
Labels: QA Tier 1, Exp

#7275 feat: rnp at or below 0.3 step 1
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/index.ts
  src/fmgc/src/navigation/Navigation.ts
  src/fmgc/src/navigation/RequiredPerformance.ts
  src/instruments/src/ND/elements/CrossTrack.tsx
  src/instruments/src/ND/pages/ArcMode.tsx
  src/instruments/src/ND/pages/PlanMode.tsx
  src/instruments/src/ND/pages/RoseMode.tsx
  src/instruments/src/PFD/LandingSystemIndicator.tsx
  src/instruments/src/PFD/instrument.tsx
  src/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
Labels: QA Tier 2, Exp

#7297 fix: use visualframe to avoid msfs bug
  src/systems/systems_wasm/src/lib.rs
Labels: QA Tier 1, Exp

#7229 feat: improving flypadOS 3 Ground Service page
  src/instruments/src/EFB/Ground/Ground.tsx
  src/instruments/src/EFB/Ground/Pages/ServicesPage.tsx
  src/instruments/src/EFB/Localization/README.md
  src/instruments/src/EFB/Localization/en.json
  src/instruments/src/EFB/Store/features/buttons.ts
  src/instruments/src/EFB/Store/features/groundServicePage.ts
  src/instruments/src/EFB/Store/reducers.ts
  src/instruments/src/EFB/Store/store.ts
Labels: QA Tier 2, Exp

#7302 fix(flaps): reverse-apply FPPU LUTs to compensate for non-linear behaviour
  src/systems/systems/src/hydraulic/flap_slat.rs
Labels: QA Tier 1

#7298 feat(sd): Improve visuals of F/CTL and WHEEL pages
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.css
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.html
  src/instruments/src/SD/Common/CommonStyles.scss
  src/instruments/src/SD/Common/HydraulicIndicator.scss
  src/instruments/src/SD/Common/HydraulicIndicator.tsx
  src/instruments/src/SD/Common/Spoilers.scss
  src/instruments/src/SD/Common/Spoilers.tsx
  src/instruments/src/SD/Pages/Fctl/Fctl.scss
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
  src/instruments/src/SD/Pages/Wheel/Wheel.scss
  src/instruments/src/SD/Pages/Wheel/Wheel.tsx
Labels: QA Tier 1

#7294 feat(mcdu): page format helper
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Format.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MenuPage.js
Labels: QA Tier 1, Exp

#7303 fix(efb): default unit
  .github/CHANGELOG.md
  src/shared/src/units.ts
Labels: QA Tier 1, Exp
