Repository flybywiresim/aircraft, pull requests merged in 2022-02, with the labels that each got.

#6649 fix(fms): cruise alt message
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1

#6407 fix(api): DOME light switch doesn't move when set to "dim" via SimConnect
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1

#6650 feat(ecam): packs off abnormally warning
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Labels: QA Tier 1

#5934 feat(tcas): TCAS TA/RA logic and annunciations (ReactJS/TS)
  .github/CHANGELOG.md
  .gitignore
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/html_ui/Images/ND/TRAFFIC_NORMAL.svg
  flybywire-aircraft-a320-neo/html_ui/Images/ND/TRAFFIC_PROXIMITY.svg
  flybywire-aircraft-a320-neo/html_ui/Images/ND/TRAFFIC_RA.svg
  flybywire-aircraft-a320-neo/html_ui/Images/ND/TRAFFIC_TA.svg
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_SoundManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  package.json
  src/behavior/src/A32NX_Interior_ATC.xml
  src/instruments/src/ATC/index.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
  src/instruments/src/ND/elements/Traffic.tsx
  src/instruments/src/ND/elements/messages/NavigationDisplayMessages.tsx
  src/instruments/src/ND/elements/messages/TcasWxrMessages.tsx
  src/instruments/src/ND/index.tsx
  src/instruments/src/ND/pages/ArcMode.tsx
  src/instruments/src/ND/pages/RoseMode.tsx
  src/instruments/src/ND/utils/MapParameters.ts
  src/instruments/src/PFD/AltitudeIndicator.tsx
  src/instruments/src/PFD/VerticalSpeedIndicator.tsx
  src/instruments/src/PFD/style.scss
  src/shared/src/MathUtils.ts
  src/shared/src/NavigationDisplay.ts
  src/shared/src/UpdateThrottler.ts
  src/shared/src/simvar.ts
  src/tcas/rollup.config.js
  src/tcas/src/components/TcasComputer.ts
  src/tcas/src/components/TcasSoundManager.ts
  src/tcas/src/index.ts
  src/tcas/src/lib/TcasComponent.ts
  src/tcas/src/lib/TcasConstants.ts
  src/tcas/src/loop.ts
  src/tcas/tsconfig.json
  src/tsconfig.json
Labels: QA Tier 2

#6697 fix(atc): transponder auto logic and ident
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  src/behavior/src/A32NX_Interior_ATC.xml
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems/src/lib.rs
  src/systems/systems/src/landing_gear/mod.rs
Labels: QA Tier 1

#6714 fix(atsu): send ATIS to printer
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js
Labels: QA Tier 1

#6727 fix(atc): remove erroneous template
  docs/a320-simvars.md
  src/behavior/src/A32NX_Interior_ATC.xml
  src/tcas/src/components/TcasComputer.ts
Labels: QA Tier 1

#6694 feat: Button press sound for Remote MCDU clicks
  src/mcdu-server/client/public/button-click.mp3
  src/mcdu-server/client/src/App.jsx
  src/mcdu-server/client/src/McduButtons.jsx
  src/mcdu-server/index.js
Labels: QA Tier 1

#6620 feat: EFB Colored Metar and Baro Setting
  .github/CHANGELOG.md
  package.json
  src/instruments/src/Common/metarTypes.ts
  src/instruments/src/EFB/Dashboard/Widgets/ColorMetar.tsx
  src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
  src/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx
  src/instruments/src/EFB/Utils/parseMetar.spec.ts
  src/instruments/src/EFB/Utils/parseMetar.tsx
Labels: QA Tier 1

#6730 fix: Added check of ATIS Source for ATC API queries (sentry issue)
  src/instruments/src/EFB/ATC/ATC.tsx
Labels: EFB, QA Tier 1

#6756 fix(du): force css animations on
  .github/CHANGELOG.md
  src/instruments/src/Common/displayUnit.tsx
Labels: QA Tier 1

#6758 fix: misc fixes
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
  src/fmgc/src/flightphase/FlightPhaseManager.ts
  src/fmgc/src/flightphase/index.ts
  src/fmgc/src/guidance/lnav/legs/index.ts
  src/fmgc/src/index.ts
Labels: QA Tier 1

#6781 fix(mcdu): handle clr dir to wpt
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js
Labels: QA Tier 1

#6766 fix(tcas): TCAS critical hotfixes and improvements
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  src/behavior/src/A32NX_Interior_ATC.xml
  src/instruments/src/EFB/Settings/Settings.tsx
  src/tcas/src/components/TcasComputer.ts
Labels: QA Tier 1

#6800 fix(lnav): fix HX entry RAD, FC and FD legs, and enroute runway
  src/fmgc/src/efis/EfisSymbols.ts
  src/fmgc/src/flightplanning/LegsProcedure.ts
  src/fmgc/src/guidance/lnav/transitions/HoldEntryTransition.ts
  src/instruments/src/ND/elements/FlightPlan.tsx
Labels: QA Tier 1

#6640 fix: Remote MCDU CommandLine Improvements
  .github/CHANGELOG.md
  package.json
  src/mcdu-server/index.js
Labels: QA Tier 1

#6736 feat(navigation): add radio altimeter systems
  .github/CHANGELOG.md
  README.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FWC.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
  src/failures/src/a320.ts
  src/instruments/src/EFB/failures-orchestrator-provider.tsx
  src/instruments/src/PFD/AltitudeIndicator.tsx
  src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
  src/instruments/src/PFD/VerticalSpeedIndicator.tsx
  src/instruments/src/PFD/index.tsx
  src/systems/a320_systems/src/lib.rs
  src/systems/a320_systems/src/navigation.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/failures/mod.rs
  src/systems/systems/src/navigation/ala52b.rs
  src/systems/systems/src/navigation/mod.rs
  src/systems/systems/src/navigation/radio_altimeter.rs
  src/tcas/src/components/TcasComputer.ts
Labels: Tested
