Repository flybywiresim/aircraft, pull requests merged in 2022-11, with the labels that each got.

#7542 fix(engine): Engine primary parameters fine tuning – Part 1 of 2
  .github/CHANGELOG.md
  src/fadec/src/EngineControl.h
  src/fadec/src/RegPolynomials.h
Labels: QA Tier 2, Exp

#7565 fix: Engine Flex Calculations
  .github/CHANGELOG.md
  src/fadec/src/ThrustLimits.h
Labels: QA Tier 1, Exp

#7562 feat(bleed): Fixed anti-ice fault logic
  src/systems/a320_systems/src/pneumatic.rs
  src/systems/a320_systems/src/pneumatic/wing_anti_ice.rs
Labels: QA Tier 1, Exp

#7507 fix(cdu): MCDU fix TOGA Altitudes
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Labels: QA Tier 1, Exp

#7556 feat: Flight Model update
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
  src/fbw/src/FlyByWireInterface.cpp
  src/fmgc/src/guidance/vnav/FlightModel.ts
  src/systems/a320_systems_wasm/src/elevators.rs
Labels: QA Tier 2, Exp

#7581 fix(pfd): improve l/dev, v/dev appearance
  .github/CHANGELOG.md
  src/instruments/src/PFD/LandingSystemIndicator.tsx
  src/instruments/src/PFD/PFD.svg
Labels: QA Tier 1

#7468 feat: initial a380_systems modifications
  src/systems/a380_systems/src/electrical/mod.rs
  src/systems/a380_systems/src/hydraulic/mod.rs
  src/systems/a380_systems/src/lib.rs
  src/systems/a380_systems/src/pneumatic.rs
  src/systems/a380_systems/src/test/mod.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/pumps.rs
Labels: Needs Code Review

#7585 fix: pass an id to un/focus_input_field
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Scratchpad.js
  src/instruments/src/EFB/UtilComponents/Form/SimpleInput/SimpleInput.tsx
  src/instruments/src/EFB/react-app-env.d.ts
  typings/fs-base-ui/html_ui/JS/coherent.d.ts
Labels: QA Tier 1

#7595 fix: init order for scratchpad
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  src/instruments/src/EFB/UtilComponents/Form/SimpleInput/SimpleInput.tsx
Labels: QA Tier 1, Exp

#7567 refactor(tcas): fixed several issues with TCAS and traffic display
  src/instruments/src/ND/elements/Traffic.tsx
  src/shared/src/NavigationDisplay.ts
  src/tcas/src/components/TcasComputer.ts
Labels: QA Tier 2, Exp

#7554 feat(hyd): Electro Hydrostatic Actuator (E(B)HA)
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a380_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/landing_gear.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
Labels: Needs Code Review

#7593 fix(fms/mcdu): co-route fixes
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/simbridge-client/src/common.ts
  src/simbridge-client/src/components/Coroute.ts
Labels: QA Tier 1, Exp

#7588 chore: update dev-env to 0.20.3.0 and tool chain versions
  Cargo.toml
  igniter.config.mjs
  rust-toolchain.toml
  scripts/dev-env/run.cmd
  scripts/dev-env/run.sh
  src/flypad-backend/build.sh
  src/systems/a320_hydraulic_simulation_graphs/Cargo.toml
  src/systems/a320_hydraulic_simulation_graphs/src/main.rs
  src/systems/a320_systems/Cargo.toml
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/Cargo.toml
  src/systems/a380_systems/Cargo.toml
  src/systems/a380_systems/src/hydraulic/mod.rs
  src/systems/a380_systems_wasm/Cargo.toml
  src/systems/systems/Cargo.toml
  src/systems/systems/src/air_conditioning/acs_controller.rs
  src/systems/systems/src/apu/air_intake_flap.rs
  src/systems/systems/src/apu/electronic_control_box.rs
  src/systems/systems/src/apu/mod.rs
  src/systems/systems/src/electrical/mod.rs
  src/systems/systems/src/failures/mod.rs
  src/systems/systems/src/hydraulic/brake_circuit.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/trimmable_horizontal_stabilizer.rs
  src/systems/systems/src/landing_gear/mod.rs
  src/systems/systems/src/navigation/adirs.rs
  src/systems/systems/src/navigation/ala52b.rs
  src/systems/systems/src/pneumatic/mod.rs
  src/systems/systems/src/shared/arinc429.rs
  src/systems/systems/src/shared/low_pass_filter.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/mod.rs
  src/systems/systems/src/simulation/test.rs
  src/systems/systems/src/simulation/update_context.rs
  src/systems/systems_wasm/Cargo.toml
  src/systems/systems_wasm/src/aspects.rs
  src/systems/systems_wasm/src/lib.rs
Labels: QA Tier 2

#7512 feat(fac): Move speedscale computation to the FACs
  .github/CHANGELOG.md
  .vscode/settings.json
  docs/a320-simvars.md
  src/fbw/build.sh
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/model/ElacComputer.cpp
  src/fbw/src/model/ElacComputer_data.cpp
  src/fbw/src/model/ElacComputer_types.h
  src/fbw/src/model/FacComputer.cpp
  src/fbw/src/model/FacComputer.h
  src/fbw/src/model/FacComputer_data.cpp
  src/fbw/src/model/FacComputer_types.h
  src/fbw/src/model/SecComputer.cpp
  src/fbw/src/model/SecComputer_data.cpp
  src/fbw/src/model/SecComputer_types.h
  src/fbw/src/model/look2_pbinlxpw.cpp
  src/fbw/src/model/look2_pbinlxpw.h
  src/instruments/src/PFD/PFDUtils.tsx
  src/instruments/src/PFD/SpeedIndicator.tsx
  src/instruments/src/PFD/instrument.tsx
  src/instruments/src/PFD/shared/ArincValueProvider.ts
  src/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
Labels: Needs Code Review, Exp

#7604 feat: Added deboarding button to flyPad Payload page
  .github/CHANGELOG.md
  src/instruments/src/EFB/Ground/Ground.tsx
  src/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx
  src/instruments/src/EFB/Localization/en.json
Labels: QA Tier 1, Exp

#7605 feat: toogle switches with mousewheel
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_RMP.xml
Labels: QA Tier 1

#7596 refactor: Improving simbridge-client connection handling
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  src/instruments/src/EFB/Navigation/Pages/LocalFilesPage/LocalFileChartSelector.tsx
  src/instruments/src/EFB/Navigation/Pages/LocalFilesPage/LocalFileChartUI.tsx
  src/instruments/src/EFB/Navigation/Pages/LocalFilesPage/LocalFilesPage.tsx
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/simbridge-client/src/components/ClientState.ts
  src/simbridge-client/src/components/Coroute.ts
  src/simbridge-client/src/components/Health.ts
  src/simbridge-client/src/components/McduServerClient.ts
  src/simbridge-client/src/components/Terrain.ts
  src/simbridge-client/src/components/Viewer.ts
  src/simbridge-client/src/index.ts
  typings/types.d.ts
Labels: Exp

#7618 fix(#7614): mousewheel switches
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Labels: QA Tier 1
