Repository flybywiresim/aircraft, pull requests merged in 2022-12, with the labels that each got.

#7613 feat: added pretty release name to flyPad about page
  src/instruments/src/EFB/Settings/Pages/AboutPage.tsx
Labels: QA Tier 1, Exp

#7602 fix(adiru): wind velocity calculation
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/FansA/A320_Neo_CDU_ATC_PositionReport.js
  src/fbw/src/FlyByWireInterface.cpp
  src/instruments/src/ND/elements/WindIndicator.tsx
  src/systems/systems/src/navigation/adirs.rs
Labels: QA Tier 1, Exp

#7637 feat(fmgc): transition names and final approach slope
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  src/fmgc/src/flightplanning/LegsProcedure.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/flightplanning/RawDataMapper.ts
  src/fmgc/src/types/fstypes/FSTypes.d.ts
Labels: QA Tier 1

#7621 fix(fmgc): don't accept blank or / for hold dist/time
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_HoldAtPage.js
Labels: QA Tier 1

#7597 fix(fms): various small bugs or erroneous warnings
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fmgc/src/efis/NearbyFacilities.ts
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/LegsProcedure.ts
Labels: Exp

#7642 fix(atsu): LSK6L ATSU DLK return in ATC MENU
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Menu.js
Labels: QA Tier 1

#7608 feat(hyd): bigger planes may have tilting gears
  .github/CHANGELOG.md
  src/systems/a380_systems/src/hydraulic/mod.rs
  src/systems/systems/src/landing_gear/mod.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/update_context.rs
Labels: QA Tier 1

#7626 feat(atsu): Update LPPC FansB area
  src/atsu/src/com/FutureAirNavigationSystem.ts
Labels: QA Tier 1

#7430 feat(hyd): rudder mechanical control and yaw damper
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  src/behavior/src/A32NX_Exterior.xml
  src/fbw_a320/src/FlyByWireInterface.cpp
  src/fbw_a320/src/FlyByWireInterface.h
  src/fbw_a320/src/model/FacComputer.cpp
  src/fbw_a320/src/model/FacComputer.h
  src/fbw_a320/src/model/FacComputer_data.cpp
  src/instruments/src/RTPI/index.tsx
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/src/rudder.rs
  src/systems/systems/src/hydraulic/flap_slat.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/rudder_control.rs
  src/systems/systems/src/shared/low_pass_filter.rs
Labels: Needs Code Review, Exp

#7639 feat: Flight model update - reduce flap induced drag
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  src/fmgc/src/guidance/vnav/EngineModel.ts
  src/fmgc/src/guidance/vnav/FlightModel.ts
Labels: Exp

#7563 refactor: FADEC code for A32NX & A380X options
  src/fadec/README.md
  src/fadec/a320_fadec/src/EngineControl.h
  src/fadec/a320_fadec/src/FadecGauge.cpp
  src/fadec/a320_fadec/src/FadecGauge.h
  src/fadec/a320_fadec/src/RegPolynomials.h
  src/fadec/a320_fadec/src/SimVars.h
  src/fadec/a320_fadec/src/Tables.h
  src/fadec/a320_fadec/src/ThrustLimits.h
  src/fadec/a380_fadec/src/EngineControl.h
  src/fadec/a380_fadec/src/FadecGauge.cpp
  src/fadec/a380_fadec/src/FadecGauge.h
  src/fadec/a380_fadec/src/RegPolynomials.h
  src/fadec/a380_fadec/src/SimVars.h
  src/fadec/a380_fadec/src/Tables.h
  src/fadec/a380_fadec/src/ThrustLimits.h
  src/fadec/build.sh
  src/fadec/common/common.h
Labels: Exp

#7645 fix: pushback did not pause when leaving flyPad Pushback page
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/flypad-backend/src/Pushback/Pushback.cpp
  src/instruments/src/EFB/Ground/Pages/PushbackPage.tsx
  src/instruments/src/EFB/UtilComponents/BingMap.tsx
Labels: QA Tier 1, Exp

#7573 feat(hyd): Simple hydraulic temperature simulation
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/failures/src/a320.ts
  src/instruments/src/Common/EWDMessages.tsx
  src/instruments/src/EFB/failures-orchestrator-provider.tsx
  src/instruments/src/EWD/elements/PseudoFWC.tsx
  src/instruments/src/SD/Pages/Hyd/Hyd.tsx
  src/systems/a320_hydraulic_simulation_graphs/src/main.rs
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/a380_systems/src/hydraulic/mod.rs
  src/systems/systems/src/failures/mod.rs
  src/systems/systems/src/hydraulic/electrical_pump_physics.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/pumps.rs
  src/systems/systems/src/shared/mod.rs
Labels: Needs Code Review, Exp

#7668 fix: Fixed additional issues which prevented ACE to work
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  src/simbridge-client/src/components/McduServerClient.ts
Labels: QA Tier 1

#7390 feat(hyd): changed gear lever mechanism / added gear door drag
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Library.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_BrakeTemp.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FWC.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
  src/behavior/src/A32NX_Interior_Handling.xml
  src/behavior/src/A32NX_Interior_Misc.xml
  src/instruments/src/EWD/elements/PseudoFWC.tsx
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/src/gear.rs
  src/systems/systems/src/landing_gear/mod.rs
Labels: QA Tier 1, Exp

#7241 feat(rmp): RMP navigation tuning
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/en-US.locPak
  flybywire-aircraft-a320-neo/fr-FR.locPak
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_SelectedNavaids.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/behavior/src/A32NX_Interior_RMP.xml
  src/fmgc/src/radionav/NavRadioManager.ts
  src/instruments/src/ND/elements/RadioNavInfo.tsx
  src/instruments/src/ND/pages/RoseMode.tsx
  src/instruments/src/PFD/HeadingIndicator.tsx
  src/instruments/src/PFD/LandingSystemIndicator.tsx
  src/instruments/src/PFD/instrument.tsx
  src/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
  src/instruments/src/RMP/Components/BaseRadioPanels.tsx
  src/instruments/src/RMP/Components/NavRadioPanel.tsx
  src/instruments/src/RMP/Components/RadioPanelDisplay.tsx
  src/instruments/src/RMP/Components/StandbyCourse.tsx
  src/instruments/src/RMP/Components/StandbyFrequency.tsx
  src/instruments/src/RMP/Components/VhfRadioPanel.tsx
Labels: QA Tier 1, Exp

#7653 feat(sec): ground spoiler logic improvements
  .github/CHANGELOG.md
  src/fbw_a320/src/model/SecComputer.cpp
  src/fbw_a320/src/model/SecComputer.h
  src/fbw_a320/src/model/SecComputer_data.cpp
Labels: Exp

#7635 feat(hyd): faster core hydraulics solver
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a380_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/electrical_generator.rs
  src/systems/systems/src/hydraulic/electrical_pump_physics.rs
  src/systems/systems/src/hydraulic/flap_slat.rs
  src/systems/systems/src/hydraulic/landing_gear.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/trimmable_horizontal_stabilizer.rs
Labels: Needs Code Review, Exp

#7646 fix: Improve import flight plan from MSFS World Map
  .github/CHANGELOG.md
  src/fmgc/src/flightplanning/FlightPlanAsoboSync.ts
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/LegsProcedure.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/flightplanning/RawDataMapper.ts
Labels: Quality of Life, QA Tier 1, Exp
