Repository flybywiresim/aircraft, pull requests merged in 2022-08, with the labels that each got.

#7364 fix(hyd): reverting gravity extension causing gear impacting doors
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/landing_gear/mod.rs
Labels: QA Tier 1, Exp

#7369 fix: printer lag
  flybywire-aircraft-a320-neo/html_ui/Pages/VLivery/Liveries/Printer/Printer.js
Labels: QA Tier 1, Exp

#7385 fix: ctd when using gravity gear handle in lock mode
  src/behavior/src/A32NX_Interior_Handling.xml
Labels: QA Tier 1, Exp

#7371 fix(mcdu): hide stored elements on a/c status when empty
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_IdentPage.js
  src/fmgc/src/flightplanning/FlightPlanManager.ts
Labels: QA Tier 1, Exp

#7375 fix(fmgc): cd leg ident
  .github/CHANGELOG.md
  src/fmgc/src/flightplanning/LegsProcedure.ts
Labels: QA Tier 1, Exp

#7349 fix(hyd): all actuators controlled in angular reference
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/landing_gear.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
Labels: QA Tier 1, Exp

#7377 feat(hyd): asymetrical damping chambers
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/landing_gear.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
Labels: QA Tier 1, Exp

#7376 feat(model): separate gear door animations
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  src/model/a320-exterior/A320_NEO_LOD00.gltf
  src/systems/systems/src/hydraulic/landing_gear.rs
Labels: QA Tier 1, Exp

#7358 feat(hyd): aerodynamic forces affecting gear system
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/aerodynamic_model.rs
  src/systems/systems/src/hydraulic/landing_gear.rs
  src/systems/systems/src/shared/mod.rs
Labels: QA Tier 2, Exp

#7341 fix(fmgc): improve procedure loading perf
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_WaypointLoader.js
  src/fmgc/src/flightplanning/LegsProcedure.ts
  typings/asobo-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/FlightElements/WaypointLoader.d.ts
Labels: QA Tier 1, Exp

#7392 refactor(hyd): plane acceleration calculations moved to context
  .github/CHANGELOG.md
  src/systems/systems/src/hydraulic/linear_actuator.rs
  src/systems/systems/src/shared/low_pass_filter.rs
  src/systems/systems/src/simulation/update_context.rs
Labels: QA Tier 1

#7400 fix(model): gear xml issues
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
Labels: QA Tier 1, Exp

#7334 feat(efb): flypad weight and balance/payload loading page v1 🚀
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/instruments/src/Common/bitFlags.tsx
  src/instruments/src/EFB/Assets/GroundServiceOutline.tsx
  src/instruments/src/EFB/Assets/Plane.tsx
  src/instruments/src/EFB/Assets/Seat.tsx
  src/instruments/src/EFB/Assets/SeatOutlineBg.tsx
  src/instruments/src/EFB/Assets/seat.svg
  src/instruments/src/EFB/Ground/Ground.tsx
  src/instruments/src/EFB/Ground/Pages/Payload/Chart/ChartWidget.tsx
  src/instruments/src/EFB/Ground/Pages/Payload/Chart/Constants.ts
  src/instruments/src/EFB/Ground/Pages/Payload/Loadsheet/a20nv55.json
  src/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx
  src/instruments/src/EFB/Ground/Pages/Payload/Seating/CargoWidget.tsx
  src/instruments/src/EFB/Ground/Pages/Payload/Seating/Constants.ts
  src/instruments/src/EFB/Ground/Pages/Payload/Seating/SeatMapWidget.tsx
  src/instruments/src/EFB/Ground/Pages/ServicesPage.tsx
  src/instruments/src/EFB/Localization/en.json
  src/instruments/src/EFB/SimbriefApi/simbriefInterface.ts
  src/instruments/src/EFB/SimbriefApi/simbriefParser.ts
  src/instruments/src/EFB/Store/features/simBrief.ts
  src/instruments/src/EFB/UtilComponents/Form/SimpleInput/SimpleInput.tsx
  src/instruments/src/EFB/UtilComponents/KeyboardWrapper.tsx
  src/instruments/src/EFB/UtilComponents/TooltipWrapper.tsx
  src/shared/src/bitFlags.ts
  src/shared/src/units.ts
Labels: QA Tier 1, Exp

#7408 feat(sound): printer and paper sounds
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  src/behavior/src/A32NX_Interior_Printer.xml
Labels: QA Tier 1, Exp

#7338 fix(model): remove blue highlights in lock mode
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo-lock-highlight/ModelBehaviorDefs/A32NX/LockHighlight.xml
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/LockHighlight.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  manifest-base-lock-highlight.json
  scripts/build.js
Labels: QA Tier 1, Exp

#7378 feat(simbridge): simbridge client
  .gitignore
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  igniter.config.mjs
  package.json
  src/simbridge-client/rollup.config.js
  src/simbridge-client/src/Coroute/Airport.ts
  src/simbridge-client/src/Coroute/Fix.ts
  src/simbridge-client/src/Coroute/General.ts
  src/simbridge-client/src/Coroute/Navlog.ts
  src/simbridge-client/src/Coroute/coroute.ts
  src/simbridge-client/src/common.ts
  src/simbridge-client/src/components/Coroute.ts
  src/simbridge-client/src/components/Viewer.ts
  src/simbridge-client/src/index.ts
  src/simbridge-client/tsconfig.json
Labels: QA Tier 1, Exp

#7355 refactor(cond): merge air cond and pneumatic pack flow valve
  docs/a320-simvars.md
  src/instruments/src/SD/Pages/Bleed/elements/BleedGauge.tsx
  src/systems/a320_systems/src/air_conditioning.rs
  src/systems/a320_systems/src/lib.rs
  src/systems/a320_systems/src/pneumatic.rs
  src/systems/systems/src/air_conditioning/acs_controller.rs
  src/systems/systems/src/air_conditioning/mod.rs
  src/systems/systems/src/shared/mod.rs
Labels: QA Tier 2, Exp

#7105 fix(rmp): RMP behaviour and lights
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_RMP.xml
  src/instruments/src/Common/EWDMessages.tsx
  src/instruments/src/EWD/elements/PseudoFWC.tsx
  src/instruments/src/RMP/Components/RadioPanelDisplay.tsx
  src/instruments/src/RMP/Components/StandbyFrequency.tsx
  src/instruments/src/RMP/Components/VhfRadioPanel.tsx
Labels: QA Tier 1, Exp

#7388 feat(hyd): actuator randomized flow restriction
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
Labels: QA Tier 1, Exp

#7426 feat(pfd): Sync EFIS
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/fbw/src/AdditionalData.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/instruments/src/EFB/Settings/Pages/RealismPage.tsx
  src/instruments/src/EFB/Settings/sync.ts
Labels: QA Tier 1

#7423 fix(pfd): tweak TCAS fail position
  src/instruments/src/PFD/AltitudeIndicator.tsx
  src/instruments/src/PFD/PFD.svg
Labels: QA Tier 1, Exp

#7401 feat(pfd): mda/mdh indication
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
  msfs-avionics-mirror/src/sdk/data/Consumer.ts
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/instruments/src/PFD/AltitudeIndicator.tsx
  src/instruments/src/PFD/DigitalAltitudeReadout.tsx
  src/instruments/src/PFD/PFD.svg
  src/instruments/src/PFD/instrument.tsx
  src/instruments/src/PFD/shared/ArincValueProvider.ts
  src/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
  src/instruments/src/PFD/style.scss
  src/instruments/src/SD/Pages/Crz/Crz.tsx
  src/instruments/src/SD/Pages/Press/Press.tsx
  src/systems/systems/src/pressurization/mod.rs
Labels: QA Tier 1

#7314 feat(hyd): hydraulic actuator locking function
  .github/CHANGELOG.md
  Cargo.lock
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/landing_gear.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
Labels: QA Tier 1

#7444 fix(efb): rego setting
  src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
Labels: EFB, QA Tier 1

#7427 fix(efb): fix ground services page being blank
  src/instruments/src/EFB/Ground/Pages/PushbackMap.tsx
Labels: QA Tier 1

#7443 fix(efb): landing calculator autoland selection
  src/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx
Labels: QA Tier 1

#7415 feat(cond): connect air conditioning to electrical system
  .github/CHANGELOG.md
  src/systems/a320_systems/src/air_conditioning.rs
  src/systems/a320_systems/src/pneumatic.rs
  src/systems/systems/src/air_conditioning/acs_controller.rs
  src/systems/systems/src/air_conditioning/mod.rs
Labels: QA Tier 1

#7446 fix(elec): prevent power loss on runway spawn
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
Labels: QA Tier 1

#7402 feat: change prepare4takeoff announcement trigger
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
Labels: QA Tier 1, Exp

#6993 feat(api): add simbridge integration
  .github/CHANGELOG.md
  .gitignore
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  igniter.config.mjs
  package.json
  src/instruments/src/EFB/Localization/en.json
  src/instruments/src/EFB/Settings/Migration.tsx
  src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
  src/instruments/src/EFB/index.tsx
  src/mcdu-server/client/LICENSE-ROBOTO.txt
  src/mcdu-server/client/public/RobotoMono-Bold.ttf
  src/mcdu-server/client/public/android-chrome-192x192.png
  src/mcdu-server/client/public/android-chrome-512x512.png
  src/mcdu-server/client/public/apple-touch-icon-180x180.png
  src/mcdu-server/client/public/button-click.mp3
  src/mcdu-server/client/public/favicon.ico
  src/mcdu-server/client/public/index.html
  src/mcdu-server/client/public/manifest.json
  src/mcdu-server/client/public/mcdu-a32nx-dark.png
  src/mcdu-server/client/public/mcdu-a32nx.png
  src/mcdu-server/client/public/mcdu-r2-c.png
  src/mcdu-server/client/rollup.config.js
  src/mcdu-server/client/src/App.css
  src/mcdu-server/client/src/App.jsx
  src/mcdu-server/client/src/McduButtons.css
  src/mcdu-server/client/src/McduButtons.jsx
  src/mcdu-server/client/src/McduScreen.css
  src/mcdu-server/client/src/McduScreen.jsx
  src/mcdu-server/client/src/WebsocketContext.jsx
  src/mcdu-server/client/src/index.css
  src/mcdu-server/client/src/index.jsx
  src/mcdu-server/index.js
  src/mcdu-server/standalone-patch.js
Labels: QA Tier 1, Exp

#7454 fix(sound): fix typos in sound.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
Labels: QA Tier 1

#7416 feat(sd): HYD page improvements
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/instruments/src/SD/Common/CommonStyles.scss
  src/instruments/src/SD/Pages/Hyd/Hyd.scss
  src/instruments/src/SD/Pages/Hyd/Hyd.tsx
  src/instruments/src/SD/Pages/Hyd/common.tsx
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/mod.rs
Labels: QA Tier 1, Exp

#7347 feat(hyd): Added auxiliary section in core hydraulics
  .github/CHANGELOG.md
  src/systems/a320_hydraulic_simulation_graphs/src/main.rs
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/mod.rs
Labels: QA Tier 1
