Repository flybywiresim/aircraft, pull requests merged in 2022-04, with the labels that each got.

#6996 fix: SU9 issue with engine control
  src/fbw/src/FlyByWireInterface.cpp
Labels: QA Tier 1, Available on Experimental

#6988 fix(mcdu): vert rev at dest
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Labels: QA Tier 1, Available on Experimental

#6998 feat(ap/athr): improved LOC, GS, FLARE law and SOFT ALT engagement
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/AutopilotLaws.h
  src/fbw/src/model/AutopilotLaws_data.cpp
  src/fbw/src/model/AutopilotLaws_types.h
  src/fbw/src/model/Autothrust.cpp
  src/fbw/src/model/Autothrust.h
  src/fbw/src/model/Autothrust_data.cpp
Labels: QA Tier 1, Available on Experimental

#7004 fix(nd): correct track line logic
  src/instruments/src/ND/pages/RoseMode.tsx
Labels: QA Tier 1

#6960 fix(hyd): fixed visual range of spoiler animations
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
Labels: Available on Experimental

#7010 fix(ewd): Fix for wing anti-ice not appearing on EWD when using keyboard shortcut
  src/instruments/src/EWD/elements/PseudoFWC.tsx
  src/instruments/src/SD/Pages/Bleed/Bleed.tsx
Labels: QA Tier 1

#6997 fix: some small TCAS improvements
  src/tcas/src/components/TcasComputer.ts
Labels: QA Tier 1, Available on Experimental

#6990 feat(server): show the listening port when not connected
  src/mcdu-server/index.js
Labels: QA Tier 1, Available on Experimental

#6981 fix: improve overall brightness
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  src/behavior/src/A32NX_Interior_MCDU.xml
Labels: Displays, Extensive Testing Needed, QA Tier 1, Available on Experimental

#6940 feat: use flowevent to replace coherent events
  src/fmgc/src/efis/EfisSymbols.ts
  src/fmgc/src/efis/EfisVectors.ts
  src/instruments/src/Common/hooks.tsx
  src/instruments/src/ND/elements/FlightPlanVectors.tsx
  src/instruments/src/ND/elements/Traffic.tsx
  src/instruments/src/ND/index.tsx
  src/shared/src/FlowEventSync.ts
  src/tcas/src/components/TcasComputer.ts
Labels: Available on Experimental

#6808 feat(fmgc): coarse lnav speed prediction
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/guidance/Geometry.ts
  src/fmgc/src/guidance/lnav/legs/Leg.ts
  src/fmgc/src/guidance/lnav/legs/index.ts
  src/fmgc/src/guidance/vnav/AtmosphericConditions.ts
  src/fmgc/src/guidance/vnav/CoarsePredictions.ts
  src/fmgc/src/guidance/vnav/VnavDriver.ts
  src/fmgc/src/types/A32NX_Util.d.ts
Labels: QA Tier 2

#6342 feat(hyd): Hydraulic leak measurement valves
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  src/instruments/src/SD/Common/HydraulicsProvider.tsx
  src/systems/a320_hydraulic_simulation_graphs/src/main.rs
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/brake_circuit.rs
  src/systems/systems/src/hydraulic/electrical_generator.rs
  src/systems/systems/src/hydraulic/electrical_pump_physics.rs
  src/systems/systems/src/hydraulic/flap_slat.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/nose_steering.rs
  src/systems/systems/src/shared/mod.rs
Labels: QA Tier 1

#6545 feat(hyd): variables for sounds
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/mod.rs
Labels: QA Tier 1

#6995 feat(fmgc): runway-by-itself approaches
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Runway.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_WaypointLoader.js
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/LegsProcedure.ts
  src/fmgc/src/flightplanning/RawDataMapper.ts
  src/fmgc/src/guidance/GuidanceController.ts
  src/fmgc/src/types/fstypes/FSTypes.d.ts
Labels: QA Tier 1, Available on Experimental

#6989 feat(fmgc): automatic airway intersection
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js
Labels: QA Tier 1, Available on Experimental

#7033 fix(fmgc/mcdu): various small issues
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/guidance/lnav/LnavDriver.ts
Labels: QA Tier 1, Exp

#7045 fix: change sentry.io sample rate to 10%
  src/sentry-client/src/FbwAircraftSentryClient.ts
Labels: QA Tier 1

#6787 feat(atsu): VDL3 simulation
  .gitignore
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_ConnectionNotification.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_ConnectionStatus.js
  src/atsu/src/AOC.ts
  src/atsu/src/ATC.ts
  src/atsu/src/ATSU.ts
  src/atsu/src/com/Datalink.ts
  src/atsu/src/com/vhf/Common.ts
  src/atsu/src/com/vhf/VDL.ts
  src/atsu/src/com/vhf/VHF.ts
  src/atsu/src/com/webinterfaces/HoppieConnector.ts
  src/atsu/src/com/webinterfaces/NXApiConnector.ts
  src/atsu/src/components/DcduLink.ts
  src/instruments/src/EFB/ATC/ATC.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
Labels: MCDU, DCDU, QA Tier 1

#7058 fix(nd): tweak waypoint rendering
  src/fmgc/src/efis/EfisSymbols.ts
  src/instruments/src/ND/elements/CrossTrack.tsx
  src/instruments/src/ND/elements/FlightPlan.tsx
Labels: QA Tier 1, Exp

#7052 refactor(mcdu): keypad
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Keypad.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MenuPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Scratchpad.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_SecFplnMain.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Menu.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/CFDS/TEST_INST/EIS/A320_Neo_CDU_CFDS_Test_Inst_EIS_Menu.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/CFDS/TEST_INST/EIS/A320_Neo_CDU_CFDS_Test_Inst_EIS_Tests.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/CFDS/TEST_INST/EIS/A320_Neo_CDU_CFDS_Test_Inst_EIS_Tests_Display.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1

#7056 fix(mcdu): radnav manual ils freq entry no crs set
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
Labels: QA Tier 1

#7059 feat(engine): Realistic engine spool model
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
Labels: Exp

#7068 feat: added config parameter to change key increment for throttles
  .github/CHANGELOG.md
  docs/Configuration/ThrottleConfiguration.ini
  docs/a320-simvars.md
  src/fbw/src/ThrottleAxisMapping.cpp
  src/fbw/src/ThrottleAxisMapping.h
Labels: Exp

#7003 fix(fmgc): nat track and lat/lon improvements
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCDataManager.js
  src/instruments/src/EFB/Settings/Settings.tsx
Labels: QA Tier 1

#7027 fix(fmgc): rebuild whole arrival and approach
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
Labels: Extensive Testing Needed, QA Tier 1, Exp

#7029 fix(fmgc): map unimplemented VA legs to CA
  src/fmgc/src/efis/EfisSymbols.ts
  src/fmgc/src/guidance/GuidanceManager.ts
Labels: QA Tier 1, Exp

#7093 fix(fmgc): discontinuity when star/appr disconnected
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
Labels: QA Tier 1, Exp

#7090 fix(fmgc): tweak efis airport option criteria
  src/fmgc/src/efis/EfisSymbols.ts
Labels: QA Tier 1, Exp

#6850 fix: lnav improvements
  src/fmgc/src/efis/EfisSymbols.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/guidance/Geometry.ts
  src/fmgc/src/guidance/Guidable.ts
  src/fmgc/src/guidance/GuidanceController.ts
  src/fmgc/src/guidance/GuidanceManager.ts
  src/fmgc/src/guidance/LnavConfig.ts
  src/fmgc/src/guidance/lnav/CommonGeometry.ts
  src/fmgc/src/guidance/lnav/LnavDriver.ts
  src/fmgc/src/guidance/lnav/PseudoWaypoints.ts
  src/fmgc/src/guidance/lnav/Transition.ts
  src/fmgc/src/guidance/lnav/legs/AF.ts
  src/fmgc/src/guidance/lnav/legs/CA.ts
  src/fmgc/src/guidance/lnav/legs/CF.ts
  src/fmgc/src/guidance/lnav/legs/CI.ts
  src/fmgc/src/guidance/lnav/legs/CR.ts
  src/fmgc/src/guidance/lnav/legs/DF.ts
  src/fmgc/src/guidance/lnav/legs/HX.ts
  src/fmgc/src/guidance/lnav/legs/IF.ts
  src/fmgc/src/guidance/lnav/legs/Leg.ts
  src/fmgc/src/guidance/lnav/legs/TF.ts
  src/fmgc/src/guidance/lnav/legs/VM.ts
  src/fmgc/src/guidance/lnav/legs/XF.ts
  src/fmgc/src/guidance/lnav/transitions/CourseCaptureTransition.ts
  src/fmgc/src/guidance/lnav/transitions/DirectToFixTransition.ts
  src/fmgc/src/guidance/lnav/transitions/DmeArcTransition.ts
  src/fmgc/src/guidance/lnav/transitions/FixedRadiusTransition.ts
  src/fmgc/src/guidance/lnav/transitions/HoldEntryTransition.ts
  src/fmgc/src/guidance/lnav/transitions/PathCaptureTransition.ts
  src/fmgc/src/guidance/lnav/transitions/utilss/CourseChange.ts
  src/fmgc/src/guidance/vnav/CoarsePredictions.ts
  src/fmgc/src/utils/Geo.ts
  src/instruments/src/ND/elements/ToWaypointIndicator.tsx
Labels: Exp

#7057 fix(mcdu): f-pln page annotations
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  msfs-avionics-mirror/src/msfstypes/pages/vcockpit/instruments/shared/flightelements/flightplanmanager.d.ts
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/LegsProcedure.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/flightplanning/RawDataMapper.ts
  src/fmgc/src/guidance/GuidanceController.ts
  src/fmgc/src/index.ts
  src/shared/src/flightplan.ts
Labels: QA Tier 1, Exp

#7088 fix: fire handles can't be stowed
  .github/CHANGELOG.md
  src/behavior/src/A32NX_Interior_Fire.xml
  src/systems/systems/src/overhead/mod.rs
Labels: Needs Code Review

#7102 fix: reset display on HDG push in NAV and disarm NAV when flight plan is lost
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  src/fbw/src/model/AutopilotStateMachine.cpp
Labels: Needs Code Review, QA Tier 1, Exp

#7084 feat: add true heading and track
  docs/a320-simvars.md
  src/systems/systems/src/navigation/adirs.rs
Labels: QA Tier 1, Exp

#7100 fix(rmp): SEL indicator colour
  .github/CHANGELOG.md
  src/model/models.json
Labels: Needs Code Review, QA Tier 1, Exp

#7101 fix(fmgc): allow flight phase transition from APPR to CLB
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fmgc/src/flightphase/FlightPhaseManager.ts
  src/fmgc/src/flightphase/Phase.ts
Labels: Needs Code Review, QA Tier 1, Exp

#7094 feat(ap): improved LOC* to LOC transition and tuned GS law
  src/fbw/src/SpoilersHandler.cpp
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/AutopilotLaws.h
  src/fbw/src/model/AutopilotLaws_data.cpp
  src/fbw/src/model/AutopilotLaws_types.h
Labels: Needs Code Review, QA Tier 1, Exp

#7014 feat: use new steering axis for nosewheel
  scripts/dev-env/run.cmd
  scripts/dev-env/run.sh
  src/systems/a320_systems_wasm/src/nose_wheel_steering.rs
Labels: Needs Code Review

#7067 feat: improved initialization and custom SimConnect events for Autobrake
  .github/CHANGELOG.md
  docs/FSUIPC/flybywire-aircraft-a320-neo.evt
  docs/SPAD.neXt/flybywire-aircraft-a320-neo.xml
  docs/a320-events.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fmgc/src/components/EfisLabels.ts
  src/fmgc/src/components/FmgcComponent.ts
  src/fmgc/src/components/ReadySignal.ts
  src/fmgc/src/components/index.ts
  src/fmgc/src/index.ts
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/src/autobrakes.rs
  src/systems/systems/src/pneumatic/mod.rs
  src/systems/systems/src/pneumatic/valve.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/mod.rs
  src/systems/systems/src/simulation/test.rs
  src/systems/systems/src/simulation/update_context.rs
  src/systems/systems_wasm/src/lib.rs
Labels: Needs Code Review, QA Tier 1, Exp

#7123 feat: improved G/S capture law
  src/fbw/src/model/AutopilotLaws.cpp
  src/fbw/src/model/AutopilotLaws.h
  src/fbw/src/model/AutopilotLaws_data.cpp
Labels: Needs Code Review, QA Tier 1, Exp

#7113 fix: discontinuity in properly strung arrival
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_WaypointLoader.js
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
Labels: QA Tier 1, Exp

#7122 fix(fmgc): don't add legs to the empty segment
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
Labels: QA Tier 1, Exp

#7103 fix(isis): Brightness adjustment in home cockpit mode
  src/instruments/src/ISIS/AutoBrightness.tsx
  src/instruments/src/ISIS/ISISDisplayUnit.tsx
Labels: QA Tier 1, Exp

#7131 feat: HDG dashes variable and SimConnect chrono button events
  docs/FSUIPC/flybywire-aircraft-a320-neo.evt
  docs/SPAD.neXt/flybywire-aircraft-a320-neo.xml
  docs/a320-events.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/interface/SimConnectInterface.h
Labels: QA Tier 1

#7114 feat: direct to with anticipated turn
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fbw/src/model/AutopilotStateMachine.cpp
  src/fbw/src/model/AutopilotStateMachine.h
  src/fbw/src/model/AutopilotStateMachine_data.cpp
  src/fmgc/src/efis/EfisVectors.ts
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/flightplanning/WaypointBuilder.ts
  src/fmgc/src/guidance/GuidanceController.ts
  src/fmgc/src/guidance/lnav/TransitionPicker.ts
  src/fmgc/src/guidance/lnav/legs/DF.ts
  src/fmgc/src/guidance/lnav/legs/IF.ts
  src/fmgc/src/guidance/lnav/transitions/DirectToFixTransition.ts
Labels: Needs Code Review, QA Tier 1, Exp
