Repository flybywiresim/aircraft, pull requests merged in 2022-05, with the labels that each got.

#7120 fix(adirs): various IRS data fixes
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.js
  src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
  src/instruments/src/PFD/FlightPathDirector.tsx
  src/instruments/src/PFD/FlightPathVector.tsx
  src/instruments/src/PFD/PFD.tsx
  src/systems/systems/src/navigation/adirs.rs
Labels: QA Tier 1

#7137 fix(fwc): Visual and audible warning/caution fix
  src/instruments/src/EWD/elements/PseudoFWC.tsx
Labels: QA Tier 1

#7151 feat: disable all MSFS assistance settings
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
Labels: QA Tier 1

#7149 fix(sounds): Prevent autopilot sound on Cold and Dark spawn
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
Labels: QA Tier 1

#7160 fix(ci): GitHub workflows failing on old assets
  .github/workflows/experimental.yml
  .github/workflows/master.yml
  .github/workflows/release.yml
Labels: Critical Bug, CI

#7141 chore(fmgc): clean up unneeded changes from #7114
  src/fmgc/src/guidance/lnav/TransitionPicker.ts
  src/fmgc/src/guidance/lnav/legs/HX.ts
  src/fmgc/src/guidance/lnav/legs/IF.ts
  src/fmgc/src/guidance/lnav/transitions/DirectToFixTransition.ts
Labels: QA Tier 1

#6893 feat(hyd): hydraulic gear system
  .vscode/settings.json
  Cargo.lock
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  src/behavior/src/A32NX_Interior_Misc.xml
  src/failures/src/a320.ts
  src/instruments/src/Common/EWDMessages.tsx
  src/instruments/src/EFB/failures-orchestrator-provider.tsx
  src/instruments/src/EWD/elements/PseudoFWC.tsx
  src/systems/a320_systems/src/electrical/direct_current.rs
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems/src/lib.rs
  src/systems/a320_systems_wasm/src/gear.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/electrical/battery_charge_limiter.rs
  src/systems/systems/src/failures/mod.rs
  src/systems/systems/src/hydraulic/landing_gear.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/study/Docs/Knowledge_Data_Base.xlsx
  src/systems/systems/src/landing_gear/mod.rs
  src/systems/systems/src/navigation/adirs.rs
  src/systems/systems/src/shared/low_pass_filter.rs
  src/systems/systems/src/shared/mod.rs
Labels: Exp

#7128 fix(isis): force css animations
  src/instruments/src/ISIS/ISISDisplayUnit.tsx
Labels: QA Tier 1

#7062 ci: recognise external downloads in installer
  .github/workflows/experimental.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
  scripts/install-source.js
Labels: Needs Code Review

#7185 fix: initialize throttle position to IDLE
  src/fbw/src/ThrottleAxisMapping.cpp
Labels: QA Tier 1, Exp

#7117 fix(fmgc): remove TAKEOFF to PREFLIGHT transition
  .github/CHANGELOG.md
  src/fmgc/src/flightphase/FlightPhaseManager.ts
  src/fmgc/src/flightphase/Phase.ts
  src/shared/src/flightphase.ts
Labels: QA Tier 1, Exp

#7140 fix(fmgc): robust comparison of legs
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  src/fmgc/src/flightplanning/LegsProcedure.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/guidance/GuidanceManager.ts
  src/fmgc/src/guidance/lnav/LnavDriver.ts
  src/fmgc/src/guidance/lnav/legs/CA.ts
  src/fmgc/src/guidance/lnav/legs/CF.ts
  src/fmgc/src/guidance/lnav/legs/CI.ts
  src/fmgc/src/guidance/lnav/legs/CR.ts
  src/fmgc/src/guidance/lnav/legs/RF.ts
  src/fmgc/src/guidance/lnav/legs/VM.ts
Labels: Needs Code Review, QA Tier 1, Exp

#7194 fix(fms): fix sync of origin runway when loading from MSFS World Map
  src/fmgc/src/flightplanning/FlightPlanManager.ts
Labels: QA Tier 1, Exp

#7170 fix: fuel persistency
  .github/CHANGELOG.md
  src/fadec/build.sh
  src/fadec/src/EngineControl.h
  src/fadec/src/FadecGauge.cpp
  src/fadec/src/FadecGauge.h
  src/fadec/src/SimVars.h
  src/fbw/src/inih/ini.h
Labels: QA Tier 1

#7189 feat(hyd): unlock ability to reset gravity gear extension
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
Labels: QA Tier 1, Exp

#7201 fix(tcas): hotfix for TCAS standby bug
  .github/CHANGELOG.md
  src/tcas/src/components/TcasComputer.ts
Labels: Exp

#7203 fix(gpws): altitude callouts now on time
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Labels: QA Tier 1, Exp

#7202 perf: reduce variable access time
  src/systems/systems/src/simulation/mod.rs
  src/systems/systems_wasm/src/aspects.rs
  src/systems/systems_wasm/src/lib.rs
Labels: QA Tier 1, Exp

#7200 fix: Engine TOGA model matching Thrust Limits
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
Labels: QA Tier 1, Exp

#7198 fix: Improve pitch trim & manual braking level
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
Labels: QA Tier 1, Exp

#7173 feat(lgciu/sd): add LGCIU bus output, modify WHEEL page for LGCIUs
  docs/a320-simvars.md
  src/instruments/src/SD/Pages/Wheel/Wheel.tsx
  src/shared/src/arinc429.ts
  src/systems/systems/src/landing_gear/mod.rs
  src/systems/systems/src/shared/arinc429.rs
  src/systems/systems/src/simulation/mod.rs
Labels: QA Tier 1

#7193 fix(fmgc): use station declination where required
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/fmgc/src/flightplanning/LegsProcedure.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/guidance/GuidanceManager.ts
  typings/fs-base-ui/html_ui/JS/SimPlane.d.ts
Labels: QA Tier 1, Exp

#7180 perf: improved simulation variable hooks
  src/instruments/src/ATC/index.tsx
  src/instruments/src/Common/displayUnit.tsx
  src/instruments/src/Common/index.tsx
  src/instruments/src/Common/simVars.tsx
  src/instruments/src/DCDU/elements/AffirmNegativeButtons.tsx
  src/instruments/src/DCDU/elements/DatalinkMessage.tsx
  src/instruments/src/DCDU/elements/MessageVisualization.tsx
  src/instruments/src/DCDU/elements/OutputButtons.tsx
  src/instruments/src/DCDU/elements/RogerButtons.tsx
  src/instruments/src/DCDU/elements/WilcoUnableButtons.tsx
  src/instruments/src/DCDU/index.tsx
  src/instruments/src/SD/Pages/Cond/Cond.tsx
  src/instruments/src/SD/Pages/Crz/Crz.tsx
  src/instruments/src/SD/Pages/Door/Door.tsx
  src/instruments/src/SD/Pages/Elec/Elec.tsx
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
  src/instruments/src/SD/Pages/Fuel/Fuel.tsx
  src/instruments/src/SD/Pages/Hyd/Hyd.tsx
  src/instruments/src/SD/Pages/Wheel/Wheel.tsx
Labels: Do Not Merge, Exp

#7222 fix(lights): Remove infinitive emitter in ambient logo light.
  flybywire-aircraft-a320-neo/effects/LIGHT_A32NX_LogoLightAmbient.fx
Labels: Performance, Lighting

#7218 feat(hyd): add spawning gear up, and correct surface positions at init
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/landing_gear/mod.rs
  src/systems/systems/src/simulation/mod.rs
Labels: Exp

#7227 feat(fms): correct hw dept/arr page scrolling
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
Labels: QA Tier 1

#7238 perf: reduce fuel persistency update rate and enable clang optimizations
  src/fadec/build.sh
  src/fadec/src/EngineControl.h
  src/fbw/build.sh
Labels: QA Tier 1

#7249 fix: cockpit door video priority
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
Labels: QA Tier 1

#7252 fix: incorrect scroll behavior on failures page (comfort view)
  src/instruments/src/EFB/Failures/Failures.tsx
Labels: QA Tier 1

#7253 fix(notif): passthrough pause events
  flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js
Labels: QA Tier 1, Exp
