Repository flybywiresim/aircraft, pull requests merged in 2022-01, with the labels that each got.

#6317 fix(efb): landing calculator
  .github/CHANGELOG.md
  src/instruments/src/EFB/Components/Form/SelectInput/SelectInput.tsx
  src/instruments/src/EFB/Performance/Calculators/LandingCalculator.ts
  src/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx
  src/instruments/src/EFB/Store/performance-context.ts
Labels: QA Tier 2

#6479 fix(fmgc): parse decimal point for PBD input
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: Bug, QA Tier 1

#6522 fix(atsu): don't include airport as waypoint in route uplink
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
Labels: Bug, QA Tier 1

#6376 feat(pfd): Improve behaviour of the speed trend on the PFD
  src/instruments/src/PFD/index.tsx
Labels: QA Tier 1

#6537 fix(efb): fix faa taf option to match fbw api
  .github/CHANGELOG.md
  src/instruments/src/EFB/Settings/Settings.tsx
Labels: QA Tier 1

#6525 fix: Fixed input for ICAO on EFB dashboard to avoid key press leaks to sim
  src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
Labels: QA Tier 1

#5829 feat(hyd): hydraulic emergency generator
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/systems/a320_systems/src/electrical/mod.rs
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/electrical/emergency_generator.rs
  src/systems/systems/src/hydraulic/electrical_generator.rs
  src/systems/systems/src/hydraulic/electrical_pump_physics.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/landing_gear/mod.rs
  src/systems/systems/src/shared/mod.rs
  src/systems/systems/src/simulation/mod.rs
Labels: QA Tier 1

#6521 fix: update cargo hold limits to standard A320Neo configuration
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadConstructor.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js
Labels: QA Tier 1

#6529 feat: EFB Dashboard Weather Info With Full METAR
  src/instruments/src/EFB/Dashboard/Dashboard.tsx
  src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
Labels: QA Tier 1

#6159 feat(misc): Animation speed/behaviors for button, switches and knobs
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_ATC.xml
  src/behavior/src/A32NX_Interior_Generics.xml
  src/behavior/src/A32NX_Interior_Handling.xml
  src/behavior/src/A32NX_Interior_MCDU.xml
  src/behavior/src/A32NX_Interior_RMP.xml
  src/model/models.json
Labels: Quality of Life

#6460 feat(misc): Home cockpit mode
  .github/CHANGELOG.md
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.js
  src/instruments/src/Common/displayUnit.tsx
  src/instruments/src/EFB/Settings/Settings.tsx
  src/instruments/src/EFB/Settings/sync.ts
  src/instruments/src/ISIS/AutoBrightness.tsx
Labels: QA Tier 1
