Repository flybywiresim/aircraft, pull requests merged in 2022-07, with the labels that each got.

#7310 fix(mcdu): fix scrolling behaviour on arrivals page
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
Labels: QA Tier 1, Exp

#7305 feat(mcdu-client): 4:3 aspect ratio compatibility
  .github/CHANGELOG.md
  src/mcdu-server/client/src/App.css
  src/mcdu-server/client/src/App.jsx
  src/mcdu-server/client/src/McduScreen.jsx
Labels: Remote MCDU

#7291 fix: update gross weight logic across FM and monitoring systems
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadManager.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Speeds.js
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  src/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
Labels: QA Tier 1, Exp

#7318 fix(fmgc): improve ils auto-tune robustness
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 2, Exp

#7327 fix(isis): updated ECAM font for ISIS
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Fonts/ISISFontTemporary.ttf
  src/fonts/ISISFontTemporary_Source.sfd
  src/instruments/src/ISIS/style.scss
Labels: Fonts, QA Tier 1, Exp

#7337 feat: persistent dev state
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
Labels: Waiting on Core Decision

#7313 feat(hyd): new gear failures
  .github/CHANGELOG.md
  src/failures/src/a320.ts
  src/instruments/src/EFB/failures-orchestrator-provider.tsx
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/systems/src/failures/mod.rs
  src/systems/systems/src/hydraulic/landing_gear.rs
  src/systems/systems/src/shared/mod.rs
Labels: QA Tier 1, Exp

#7335 feat(pfd): Improve barberpole rendering on the PFD
  .github/CHANGELOG.md
  src/instruments/src/PFD/SpeedIndicator.tsx
Labels: Exp

#7197 feat(hyd): control surfaces position impacts flight model
  docs/a320-simvars.md
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/interface/SimConnectData.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/interface/SimConnectInterface.h
  src/systems/a320_systems/src/hydraulic/flaps_computer.rs
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/src/ailerons.rs
  src/systems/a320_systems_wasm/src/elevators.rs
  src/systems/a320_systems_wasm/src/flaps.rs
  src/systems/a320_systems_wasm/src/gear.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/a320_systems_wasm/src/rudder.rs
  src/systems/systems/src/hydraulic/landing_gear.rs
  src/systems/systems/src/hydraulic/linear_actuator.rs
  src/systems/systems_wasm/src/aspects.rs
Labels: Exp

#7333 fix(fmgc): no decel without approach
  .github/CHANGELOG.md
  src/fmgc/src/guidance/lnav/PseudoWaypoints.ts
  src/fmgc/src/guidance/vnav/VnavDriver.ts
  src/fmgc/src/guidance/vnav/descent/DescentBuilder.ts
Labels: QA Tier 1

#7343 fix(mcdu): xx arc is space padded
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Labels: QA Tier 1

#7332 fix(fmgc): string stars with non-runway-specific approaches
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
Labels: QA Tier 1, Exp

#7321 feat(sd): cond page visual improvements
  .github/CHANGELOG.md
  src/instruments/src/SD/Common/CommonStyles.scss
  src/instruments/src/SD/Pages/Cond/Cond.scss
  src/instruments/src/SD/Pages/Cond/Cond.tsx
  src/instruments/src/SD/Pages/Cond/Valve.tsx
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
  src/instruments/src/SD/Pages/Wheel/Wheel.tsx
Labels: Exp

#7279 feat(hyd): Trim wheels control
  .github/CHANGELOG.md
  Cargo.lock
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_Handling.xml
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/interface/SimConnectData.h
  src/fbw/src/interface/SimConnectInterface.cpp
  src/fbw/src/interface/SimConnectInterface.h
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/a320_systems_wasm/src/trimmable_horizontal_stabilizer.rs
  src/systems/systems/src/hydraulic/electrical_generator.rs
  src/systems/systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/trimmable_horizontal_stabilizer.rs
Labels: QA Tier 1, Exp

#7336 fix(fmgc): forced turn for path and course capture transition
  .github/CHANGELOG.md
  src/fmgc/src/guidance/lnav/transitions/CourseCaptureTransition.ts
  src/fmgc/src/guidance/lnav/transitions/PathCaptureTransition.ts
Labels: QA Tier 2, Exp

#7352 feat(fmgc): pi leg (procedure turns)
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  src/fmgc/src/components/fms-messages/FmsMessages.ts
  src/fmgc/src/components/fms-messages/TurnAreaExceedance.ts
  src/fmgc/src/efis/EfisSymbols.ts
  src/fmgc/src/flightplanning/LegsProcedure.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
  src/fmgc/src/guidance/GuidanceManager.ts
  src/fmgc/src/guidance/lnav/TransitionPicker.ts
  src/fmgc/src/guidance/lnav/legs/Leg.ts
  src/fmgc/src/guidance/lnav/legs/PI.ts
  src/fmgc/src/guidance/lnav/legs/index.ts
  src/fmgc/src/guidance/lnav/transitions/FixedRadiusTransition.ts
  src/fmgc/src/guidance/lnav/transitions/PathCaptureTransition.ts
  src/fmgc/src/navigation/Navigation.ts
  src/fmgc/src/utils/Geo.ts
  src/shared/src/FmMessages.ts
  typings/fs-base-ui/html_ui/JS/Avionics.d.ts
Labels: QA Tier 1, Exp

#7365 fix(eis): move ewd to correct ac bus
  .github/CHANGELOG.md
  src/instruments/src/EWD/index.tsx
Labels: QA Tier 1, Exp

#7342 fix(fmgc): hold leg length
  .github/CHANGELOG.md
  src/fmgc/src/guidance/lnav/legs/HX.ts
Labels: QA Tier 1, Exp
