Repository flybywiresim/aircraft, pull requests merged in 2022-10, with the labels that each got.

#7451 feat: flyPad Local Files via SimBridge
  .github/CHANGELOG.md
  src/instruments/src/EFB/ChartsApi/Navigraph.tsx
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Localization/en.json
  src/instruments/src/EFB/Navigation/Navigation.tsx
  src/instruments/src/EFB/Navigation/Pages/LocalFilesPage/LocalFileChartSelector.tsx
  src/instruments/src/EFB/Navigation/Pages/LocalFilesPage/LocalFileChartUI.tsx
  src/instruments/src/EFB/Navigation/Pages/LocalFilesPage/LocalFilesPage.tsx
  src/instruments/src/EFB/Navigation/Pages/NavigraphPage/NavigraphChartUI.tsx
  src/instruments/src/EFB/Navigation/Pages/PinnedChartsPage.tsx
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/instruments/src/EFB/UtilComponents/DrawableCanvas.tsx
  src/simbridge-client/src/components/Viewer.ts
Labels: QA Tier 2

#7528 fix(efb): use a32nx build info file
  src/instruments/src/EFB/Settings/Pages/AboutPage.tsx
Labels: QA Tier 1

#7503 fix(fms): improve alt prediction robustness
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, Exp

#7544 fix: flyPad ground services page fix overlapping divs
  src/instruments/src/EFB/Ground/Pages/ServicesPage.tsx
Labels: QA Tier 1, Exp

#7543 fix: Increased overall max brightness of instruments
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  src/behavior/src/A32NX_Interior_MCDU.xml
Labels: Lighting, Displays, QA Tier 1, Exp

#7538 fix: repair fdr data for support analysis
  .github/CHANGELOG.md
  src/fbw/src/AdditionalData.h
  src/fbw/src/FlightDataRecorder.h
  src/fbw/src/FlyByWireInterface.cpp
  src/fbw/src/FlyByWireInterface.h
  src/fbw/src/failures/FailuresConsumer.cpp
  src/fbw/src/failures/FailuresConsumer.h
  src/fdr2csv/src/FlightDataRecorderConverter.cpp
  src/fdr2csv/src/main.cpp
Labels: QA Tier 1, Exp

#7511 refactor: aircraft presets reordering based on pilot feedback and sop
  .github/CHANGELOG.md
  docs/a320-simvars.md
  src/flypad-backend/src/Aircraft/AircraftPreset.h
  src/flypad-backend/src/Aircraft/AircraftProcedures.h
  src/flypad-backend/src/FlyPadBackend.cpp
  src/flypad-backend/src/Lighting/LightPreset.h
  src/flypad-backend/src/Lighting/LightingSimVars.h
  src/flypad-backend/src/Pushback/Pushback.h
  src/instruments/src/EFB/Localization/en.json
  src/instruments/src/EFB/Presets/Widgets/AircraftPresets.tsx
  src/instruments/src/EFB/Presets/Widgets/Procedures.tsx
Labels: Needs Code Review, QA Tier 1

#7529 fix(fmgc): make des spd lim available prior to descent
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
Labels: QA Tier 1

#7458 feat(adir): correct default value for speeds discrete signals
  .github/CHANGELOG.md
  src/systems/systems/src/navigation/adirs.rs
Labels: QA Tier 1

#7551 fix(fmgc): f-pln departure pages
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  src/fmgc/src/flightplanning/FlightPlanManager.ts
  src/fmgc/src/flightplanning/ManagedFlightPlan.ts
Labels: QA Tier 2, Exp

#6411 feat(mcdu): Company Routes Implementation
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableFlightPlanPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  scripts/local-api-build.sh
  src/simbridge-client/rollup.config.js
  src/simbridge-client/src/Coroute/coroute.ts
  src/simbridge-client/src/components/Coroute.ts
Labels: MCDU, Exp

#7568 fix(hyd): Autobrake tuning
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/hydraulic/brake_circuit.rs
Labels: QA Tier 1, Exp
