Repository flybywiresim/aircraft, pull requests merged in 2022-09, with the labels that each got.

#7445 feat: re-activated EFB status bar SimBridge health check icon
  .github/CHANGELOG.md
  src/instruments/src/EFB/Localization/en.json
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/simbridge-client/src/components/Health.ts
  src/simbridge-client/src/components/Terrain.ts
  src/simbridge-client/src/index.ts
Labels: QA Tier 1

#7452 chore: bump igniter to 1.2.2
  package-lock.json
  package.json
Labels: Exp

#7461 fix(hyd): gear extending when dual lgciu fault
  .github/CHANGELOG.md
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/systems/src/landing_gear/mod.rs
Labels: QA Tier 1

#7462 feat: switch to turn on/off input from controller for pushback
  .github/CHANGELOG.md
  src/instruments/src/EFB/Ground/Pages/PushbackPage.tsx
  src/instruments/src/EFB/Localization/en.json
Labels: EFB, QA Tier 1, Exp

#7495 fix: ACE fix - refactored simbridgeUrl to function call
  src/simbridge-client/src/common.ts
  src/simbridge-client/src/components/Coroute.ts
  src/simbridge-client/src/components/Health.ts
  src/simbridge-client/src/components/Terrain.ts
  src/simbridge-client/src/components/Viewer.ts
Labels: Needs Code Review, QA Tier 1

#7474 fix(hyd): gear door opened keeps wobbling
  .github/CHANGELOG.md
  src/systems/systems/src/hydraulic/landing_gear.rs
Labels: QA Tier 1

#7485 feat: flyPad ATC view filter for controller frequencies
  src/instruments/src/EFB/ATC/ATC.tsx
  src/instruments/src/EFB/UtilComponents/Form/SimpleInput/SimpleInput.tsx
Labels: EFB, QA Tier 1

#7393 feat(hyd): fluid dynamics in reservoirs
  .github/CHANGELOG.md
  src/systems/systems/src/hydraulic/mod.rs
Labels: QA Tier 1, Exp

#7476 feat: Incorporate SU10 flight model crosswind parameters
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
Labels: QA Tier 1

#7497 feat: aircraft Presets - added conditional step to wait for FWC initialization
  docs/a320-simvars.md
  src/flypad-backend/src/Aircraft/AircraftPreset.cpp
  src/flypad-backend/src/Aircraft/AircraftPreset.h
  src/flypad-backend/src/Aircraft/AircraftProcedures.h
  src/flypad-backend/src/Lighting/LightPreset.h
  src/flypad-backend/src/Lighting/LightingSimVars.h
  src/flypad-backend/src/Pushback/InertialDampener.h
  src/flypad-backend/src/Pushback/Pushback.cpp
  src/flypad-backend/src/Pushback/Pushback.h
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Presets/Widgets/AircraftPresets.tsx
  src/instruments/src/EFB/Presets/Widgets/LightPresets.tsx
  src/instruments/src/EFB/Presets/Widgets/Procedures.tsx
Labels: QA Tier 1

#7489 feat: Realistic DCDU visualization
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/FansA/A320_Neo_CDU_ATC_PositionReport.js
  src/atsu/src/ATC.ts
  src/atsu/src/ATSU.ts
  src/atsu/src/components/FlightStateObserver.ts
  src/instruments/src/DCDU/elements/AffirmNegativeButtons.tsx
  src/instruments/src/DCDU/elements/AtcStatus.tsx
  src/instruments/src/DCDU/elements/DatalinkMessage.tsx
  src/instruments/src/DCDU/elements/MessageVisualization.tsx
  src/instruments/src/DCDU/elements/OutputButtons.tsx
  src/instruments/src/DCDU/elements/RogerButtons.tsx
  src/instruments/src/DCDU/elements/SemanticResponseButtons.tsx
  src/instruments/src/DCDU/elements/WilcoUnableButtons.tsx
  src/instruments/src/DCDU/index.tsx
Labels: QA Tier 1

#7502 fix(pfd): re-add smaller font for armed A/THR FMA message
  src/instruments/src/PFD/FMA.tsx
Labels: QA Tier 1

#7500 chore: remove unused files
  flybywire-aircraft-a320-neo/Business.json
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/1380x1302.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/1856x485.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/AOCMSG.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/COCKPITNIGHT.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/CockpitDay.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/ContentInfo_Thumbnail.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/DOORECAM.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/EFB-New.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/EFB.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/ELEC.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/INIT.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/METARRQ.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/Marketplace.json
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/Not-Aligned.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/PAPER.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/PFDND.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/Printer.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/SELFTEST1.jpg
  flybywire-aircraft-a320-neo/MarketplaceData/flybywire-aircraft-a320-neo/Thumbnail.jpg
  flybywire-aircraft-a320-neo/html_ui/Fonts/LiberationMono.ttf
  flybywire-aircraft-a320-neo/html_ui/Fonts/LiberationMono.ttf.birdfont
  flybywire-aircraft-a320-neo/html_ui/Fonts/LiberationMonoOriginal.ttf
  scripts/fragment.js
  src/svg/ecam/bleed.svg
  src/svg/ecam/cabpress.svg
  src/svg/ecam/cond.svg
  src/svg/ecam/hyd.svg
  src/svg/efb/AircraftConfig.svg
  src/svg/efb/Performance-Landing.svg
  src/svg/efb/Performance-Takeoff.svg
  src/svg/nd/chrono.svg
  src/svg/nd/rangeChange.svg
  src/svg/pfd/flightControlCursor.svg
  src/svg/pfd/fpv.svg
  src/svg/pfd/nmlLawEqualSign.svg
  src/svg/tcas/tcasDiamonds.svg
Labels: QA Tier 1
