Repository flybywiresim/aircraft, pull requests merged in 2023-10, with the labels that each got.

#8226 fix: wheels and chocks element clash
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Services/A320_251N/A320Services.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Services/A380_842/A380Services.tsx
Labels: QA Passed

#8243 fix(cond): Fixing Temp-Zone-Vars in CRZ-Page
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Crz/Crz.tsx
Labels: QA Passed

#8254 feat(fm): ils freq/ident on arrival page
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
Labels: QA Tier 1

#8216 fix(apu): Added xfeed APU capabilities
  .github/CHANGELOG.md
  fbw-a32nx/src/wasm/fadec_a320/src/EngineControl.h
Labels: QA Tier 1

#8262 feat: aviationweather.gov(noaa) metar source and efb fixes
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/AtsuAocPage.tsx
  fbw-common/src/systems/datalink/router/src/webinterfaces/NXApiConnector.ts
  fbw-common/src/systems/shared/src/config.ts
  fbw-common/src/systems/shared/src/index.ts
Labels: QA Tier 1, QA Passed

#8263 chore: upgrade msfssdk to v0.6.0
  package-lock.json
  package.json
Labels: QA Tier 2

#8205 fix(mcdu): improve PERF pages
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/VerticalProfileComputationParameters.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/climb/SpeedProfile.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/profile/BaseGeometryProfile.ts
  fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
Labels: QA Passed

#8267 fix(fwc): Fixes the Master Warning on startup
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Labels: QA Passed

#8270 fix: capt nd shows VOR1
  fbw-a32nx/src/systems/instruments/src/ND/ND.tsx
Labels: QA Tier 1

#8271 fix(pfd): show ils frequency when loc not received
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
Labels: QA Tier 1, QA Passed

#8258 fix: checklist fuel mode selector
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Library.xml
Labels: QA Tier 1, QA Passed
