Repository flybywiresim/aircraft, pull requests merged in 2023-05, with the labels that each got.

#7975 fix(sim): only shown nav radio tip once
  fbw-a32nx/src/systems/fmgc/src/navigation/NavaidTuner.ts
Labels: QA Tier 1

#8029 fix(sd): fuel xfr valve amber logic
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Fuel/Fuel.tsx
Labels: QA Tier 1

#7989 fix(efb): simbridge remote setting fix
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/simbridge-client/src/common.ts
  fbw-a32nx/src/systems/simbridge-client/src/components/ClientState.ts
  fbw-a32nx/src/systems/simbridge-client/src/components/McduServerClient.ts
Labels: Needs Changelog, QA Tier 1

#8017 fix(fms): use fqi fob after engine start for to speeds
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1

#7993 fix(nd): ROSE VOR/LS conditions and ILS course
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/ND/pages/RoseMode.tsx
Labels: QA Tier 1

#7946 feat(elec): First A380 electrical system implementation
  fbw-a32nx/src/wasm/systems/a320_systems/src/electrical/alternating_current.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/electrical/mod.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/lib.rs
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/alternating_current.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/direct_current.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/galley.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/lib.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/apu/mod.rs
  fbw-common/src/wasm/systems/systems/src/electrical/battery_charge_rectifier_unit.rs
  fbw-common/src/wasm/systems/systems/src/electrical/external_power_source.rs
  fbw-common/src/wasm/systems/systems/src/electrical/mod.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
Labels: Needs Code Review, Electrical
