Repository flybywiresim/aircraft, pull requests merged in 2023-03, with the labels that each got.

#7803 fix(pfd): Fix PFD altitude indications
  fbw-a32nx/src/systems/instruments/src/PFD/AltitudeIndicator.tsx
Labels: QA Tier 1

#7766 fix: make a429 binary format compatible with SimVar.SetSimVarValue
  .vscode/launch.json
  .vscode/tasks.json
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/arinc429.js
  fbw-a32nx/src/systems/instruments/src/Common/arinc429.tsx
  fbw-a32nx/src/systems/instruments/src/ND/elements/TerrainMap.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/shared/ArincValueProvider.ts
  fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
  fbw-a32nx/src/systems/shared/src/arinc429.ts
  fbw-a32nx/src/wasm/fbw_a320/src/Arinc429.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/Arinc429Utils.cpp
  fbw-a380x/src/wasm/fbw_a380/src/Arinc429Utils.cpp
  fbw-common/src/wasm/systems/systems/src/shared/arinc429.rs
Labels: QA Tier 1

#7652 feat(fwc): add takeoff surveillance 1 warnings and various other improvements
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FWC.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSpeeds.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/arinc429.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  fbw-a32nx/src/systems/fmgc/src/flightplanning/RawDataMapper.ts
  fbw-a32nx/src/systems/fmgc/src/types/fstypes/FSTypes.d.ts
  fbw-a32nx/src/systems/instruments/src/Common/EWDMessages.tsx
  fbw-a32nx/src/systems/instruments/src/Common/NXLogic.ts
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
  fbw-a32nx/src/systems/instruments/src/EWD/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/AdirsValueProvider.tsx
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/SimVarTypes.ts
  fbw-a32nx/src/systems/instruments/src/PFD/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/shared/AdirsValueProvider.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/shared/ArincValueProvider.ts
  fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
  fbw-a32nx/src/systems/instruments/src/SD/PagesContainer.tsx
  fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx
  fbw-a32nx/src/systems/shared/src/arinc429.ts
  fbw-a32nx/src/systems/tcas/src/components/TcasComputer.ts
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/lib.rs
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs
  fbw-common/msfs-avionics-mirror/src/sdk/index.ts
  fbw-common/msfs-avionics-mirror/src/sdk/utils/DebounceTimer.ts
  fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
  fbw-common/src/wasm/systems/systems/src/pneumatic/mod.rs
  fbw-common/src/wasm/systems/systems/src/pneumatic/valve.rs
  fbw-common/src/wasm/systems/systems/src/simulation/test.rs
  fbw-common/src/wasm/systems/systems/src/simulation/update_context.rs
Labels: QA Tier 1

#7814 refactor: update Simbridge Client fetching and State checking
  fbw-a32nx/src/systems/simbridge-client/src/components/Coroute.ts
  fbw-a32nx/src/systems/simbridge-client/src/components/Health.ts
  fbw-a32nx/src/systems/simbridge-client/src/components/Terrain.ts
  fbw-a32nx/src/systems/simbridge-client/src/components/Viewer.ts
Labels: QA Tier 1

#7847 fix(nd): plane icon
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/ND/pages/ArcMode.tsx
  fbw-a32nx/src/systems/instruments/src/ND/pages/PlanMode.tsx
  fbw-a32nx/src/systems/instruments/src/ND/pages/RoseMode.tsx
Labels: QA Tier 1

#7841 fix(nd): approach name format
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  fbw-a32nx/src/systems/fmgc/src/flightplanning/RawDataMapper.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts
  fbw-a32nx/src/systems/fmgc/src/index.ts
  fbw-a32nx/src/systems/fmgc/src/types/fstypes/FSTypes.d.ts
  fbw-a32nx/src/systems/shared/src/ApproachUtils.ts
  fbw-a32nx/src/systems/shared/src/flightplan.ts
Labels: QA Tier 1

#7843 fix(fm/pfd): rnp <= 0.3 conditions
  fbw-a32nx/src/systems/fmgc/src/navigation/RequiredPerformance.ts
  fbw-a32nx/src/systems/instruments/src/ND/elements/CrossTrack.tsx
Labels: QA Tier 1

#7842 fix(isis): show baro correction while initialising
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/ISIS/ISISDisplayUnit.tsx
Labels: QA Tier 1

#7806 refactor(efb): restructuring the apis folder structure and Navigraph Charts API update
  .github/workflows/experimental.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  fbw-a32nx/src/systems/instruments/buildSrc/plugins.mjs
  fbw-a32nx/src/systems/instruments/src/EFB/Apis/Navigraph/Components/Authentication.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Apis/Navigraph/Navigraph.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Apis/Simbrief/index.ts
  fbw-a32nx/src/systems/instruments/src/EFB/Apis/Simbrief/simbriefInterface.ts
  fbw-a32nx/src/systems/instruments/src/EFB/Apis/Simbrief/simbriefParser.ts
  fbw-a32nx/src/systems/instruments/src/EFB/ChartsApi/ChartFox.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Efb.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Navigation/Navigation.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Navigation/Pages/NavigraphPage/NavigraphChartSelector.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Navigation/Pages/NavigraphPage/NavigraphChartUI.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Navigation/Pages/NavigraphPage/NavigraphPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Store/features/navigationPage.ts
  fbw-a32nx/src/systems/instruments/src/EFB/Store/features/simBrief.ts
Labels: Exp

#7858 fix: mitigate flyPad fuel page issue for very long translations
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
Labels: QA Tier 1

#7863 feat(fwc): add landing warnings
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/systems/instruments/src/Common/EWDMessages.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
  fbw-a32nx/src/systems/shared/src/arinc429.ts
Labels: QA Tier 1

#7694 feat(egpws): Introduce first system for the EGPWS
  .vscode/settings.json
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  fbw-a32nx/src/systems/instruments/src/ND/elements/TerrainMap.tsx
  fbw-a32nx/src/systems/instruments/src/ND/elements/TerrainMapThresholds.tsx
  fbw-a32nx/src/systems/instruments/src/ND/index.tsx
  fbw-a32nx/src/systems/instruments/src/ND/pages/ArcMode.tsx
  fbw-a32nx/src/systems/instruments/src/ND/pages/RoseMode.tsx
  fbw-a32nx/src/systems/instruments/src/ND/styles.scss
  fbw-a32nx/src/systems/simbridge-client/src/components/Terrain.ts
  fbw-a32nx/src/systems/simbridge-client/src/index.ts
  fbw-a32nx/src/wasm/systems/a320_systems/src/lib.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/enhanced_gpwc/mod.rs
  fbw-common/src/wasm/systems/systems/src/enhanced_gpwc/navigation_display.rs
  fbw-common/src/wasm/systems/systems/src/landing_gear/mod.rs
  fbw-common/src/wasm/systems/systems/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
  fbw-common/src/wasm/systems/systems/src/simulation/mod.rs
  fbw-common/src/wasm/terronnd/build.sh
  fbw-common/src/wasm/terronnd/src/base/callback.hpp
  fbw-common/src/wasm/terronnd/src/base/changeable.hpp
  fbw-common/src/wasm/terronnd/src/helper/math.hpp
  fbw-common/src/wasm/terronnd/src/helper/stringconcat.hpp
  fbw-common/src/wasm/terronnd/src/main.cpp
  fbw-common/src/wasm/terronnd/src/main.h
  fbw-common/src/wasm/terronnd/src/nanovg/nanovg.cpp
  fbw-common/src/wasm/terronnd/src/navigationdisplay/collection.cpp
  fbw-common/src/wasm/terronnd/src/navigationdisplay/collection.h
  fbw-common/src/wasm/terronnd/src/navigationdisplay/configuration.h
  fbw-common/src/wasm/terronnd/src/navigationdisplay/display.h
  fbw-common/src/wasm/terronnd/src/navigationdisplay/displaybase.cpp
  fbw-common/src/wasm/terronnd/src/simconnect/clientdataarea.hpp
  fbw-common/src/wasm/terronnd/src/simconnect/connection.cpp
  fbw-common/src/wasm/terronnd/src/simconnect/connection.hpp
  fbw-common/src/wasm/terronnd/src/simconnect/lvarobject.hpp
  fbw-common/src/wasm/terronnd/src/simconnect/simobject.hpp
  fbw-common/src/wasm/terronnd/src/types/arinc429.hpp
  fbw-common/src/wasm/terronnd/src/types/quantity.hpp
  fbw-common/src/wasm/terronnd/src/types/simbridge.h
  igniter.config.mjs
Labels: Waiting for PR merge, QA Tier 2

#7872 fix(fms): no to speed check without valid data
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1

#7876 fix: increase timeout for simbridge healthcheck
  fbw-a32nx/src/systems/simbridge-client/src/common.ts
  fbw-a32nx/src/systems/simbridge-client/src/components/Health.ts
Labels: QA Tier 1

#7864 fix: Mitigation of long transaltions on flyPad fuel page 2
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
Labels: QA Tier 1

#7880 fix(fms): approach names
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
  fbw-a32nx/src/systems/fmgc/src/flightplanning/RawDataMapper.ts
  fbw-a32nx/src/systems/shared/src/ApproachUtils.ts
  fbw-a32nx/src/systems/shared/src/RunwayUtils.ts
Labels: QA Tier 1

#7881 fix(mcdu): fix negative efob on flight plan page
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Labels: QA Tier 1

#7883 fix(press): cabin pressure when starting in the air
  fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_air.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_pressure_controller.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/pressure_valve.rs
Labels: QA Tier 1

#7830 feat(fwc): A32nx minimums exposed by fmgc
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1

#7889 fix(fwc): idle tolerance for engine
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Labels: QA Tier 1

#7886 fix(sd): ISA deviation fix
  fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx
Labels: QA Tier 1

#7890 fix(fms): lat/lon close to zero on DUPLICATE NAMES page
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_SelectWptPage.js
Labels: QA Tier 1

#7888 fix: placement of "5" and "10" scale on EWD N1 gauges (#7849)
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/EWD/N1.tsx
Labels: QA Tier 1

#7884 fix(mcdu): EFOB and FUEL PRED get dashed out at decent
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: QA Tier 1

#7882 fix(nd): Update ND symbol flags of pseudowaypoints
  fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
  fbw-a32nx/src/systems/instruments/src/ND/elements/FlightPlan.tsx
  fbw-a32nx/src/systems/shared/src/NavigationDisplay.ts
Labels: QA Tier 1

#7852 feat(elec): More accurate tr and inverter
  .github/CHANGELOG.md
  fbw-common/src/wasm/systems/systems/src/electrical/static_inverter.rs
  fbw-common/src/wasm/systems/systems/src/electrical/transformer_rectifier.rs
Labels: QA Tier 1

#7856 feat: extras-host instrument for non-aircraft non-wasm functionality
  .github/CHANGELOG.md
  .gitignore
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/A32NX/ExtrasHost/extras-host.html
  fbw-a32nx/src/systems/extras-host/README.md
  fbw-a32nx/src/systems/extras-host/index.tsx
  fbw-a32nx/src/systems/extras-host/modules/common/AircraftPresetsList.ts
  fbw-a32nx/src/systems/extras-host/modules/key_interceptor/KeyInterceptor.ts
  fbw-a32nx/src/systems/extras-host/modules/version_check/VersionCheck.ts
  fbw-a32nx/src/systems/extras-host/rollup.config.js
  fbw-a32nx/src/systems/extras-host/style.scss
  fbw-a32nx/src/systems/extras-host/tsconfig.json
  fbw-a32nx/src/systems/instruments/src/EFB/Efb.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/AboutPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/index.tsx
  fbw-a32nx/src/systems/sentry-client/src/FbwAircraftSentryClient.ts
  fbw-a32nx/src/systems/shared/src/AircraftVersionChecker.ts
  fbw-a32nx/src/systems/shared/src/popup.ts
  igniter.config.mjs
  package.json
Labels: QA Tier 1

#7829 feat(efcs): add ELAC 2 emergency powersupply switching
  .github/CHANGELOG.md
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.h
Labels: QA Tier 2

#7831 feat(hyd): Realistic RAT aerodynamic model and anti stall valve
  .github/CHANGELOG.md
  Cargo.toml
  fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/mod.rs
  fbw-common/src/wasm/systems/systems/src/electrical/mod.rs
  fbw-common/src/wasm/systems/systems/src/electrical/ram_air_turbine.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/electrical_generator.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/mod.rs
  fbw-common/src/wasm/systems/systems/src/simulation/test.rs
  fbw-common/src/wasm/systems/systems/src/wind_turbine/mod.rs
Labels: QA Tier 2

#7896 fix(mcdu): fuelpred running when inputting weights after engine start
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: QA Tier 1

#7901 feat(dmc): add DMC maintenance and engineering test modes (including DMC switching)
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Images/fbw-a32nx/Common/thalesTest.svg
  fbw-a32nx/src/systems/instruments/src/Common/common.scss
  fbw-a32nx/src/systems/instruments/src/Common/displayUnit.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/EWD.tsx
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/SimVarTypes.ts
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/common.scss
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/displayUnit.tsx
  fbw-a32nx/src/systems/instruments/src/ND/index.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/PFD.tsx
  fbw-a32nx/src/systems/instruments/src/SD/index.tsx
Labels: QA Tier 1
