Repository flybywiresim/aircraft, pull requests merged in 2023-02, with the labels that each got.

#7761 fix(nd): loc deviation scaling
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/ND/pages/RoseMode.tsx
Labels: QA Tier 1

#7599 feat(cond): mixer unit and trim air system
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  fbw-a32nx/src/systems/instruments/src/EWD/elements/PseudoFWC.tsx
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Cond/Cond.tsx
  fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/lib.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/pneumatic.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/pneumatic.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/acs_controller.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_air.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/mod.rs
  fbw-common/src/wasm/systems/systems/src/overhead/mod.rs
  fbw-common/src/wasm/systems/systems/src/pressurization/mod.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
Labels: QA Tier 2, Exp

#7751 fix(EFB): offscreen menu caused by OFP layouts
  fbw-a32nx/src/systems/instruments/src/EFB/Efb.tsx
Labels: QA Tier 1

#7705 refactor(clock): Port Clock to MSFS Avionics Framework
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/A32NX/Clock/clock.html
  fbw-a32nx/src/systems/instruments/src/Clock/.eslintrc.js
  fbw-a32nx/src/systems/instruments/src/Clock/Clock.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/Components/Chrono.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/Components/Clock.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/Components/ElapsedTime.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/config.json
  fbw-a32nx/src/systems/instruments/src/Clock/index.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/rollup.config.js
  fbw-a32nx/src/systems/instruments/src/Clock/shared/ClockSimvarPublisher.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/shared/Utils.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/tsconfig.json
  igniter.config.mjs
  package.json
Labels: QA Tier 1

#7758 fix(fmgc): no constraints behind plane, only predict 2
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
Labels: QA Tier 1, Exp

#7695 feat: GSX Integration
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/GSX.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Boarding.js
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/ThirdPartyOptionsPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Settings.tsx
Labels: QA Tier 2, Exp

#7785 fix(fmgc): erroneous call
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1

#7736 refactor(fws): Port PseudoFWC to non-React framework
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
  fbw-a32nx/src/systems/instruments/src/EWD/elements/PseudoFWC.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/index.tsx
Labels: QA Tier 2

#7783 fix(aoc): Update unread message count when messages are deleted
  fbw-a32nx/src/systems/atsu/src/AOC.ts
Labels: QA Tier 1

#7693 feat(hyd): randomization of brake accumulator
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/systems/failures/src/a320.ts
  fbw-a32nx/src/systems/instruments/src/EFB/failures-orchestrator-provider.tsx
  fbw-a32nx/src/wasm/systems/a320_hydraulic_simulation_graphs/src/main.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/lib.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
  fbw-common/src/wasm/systems/systems/src/failures/mod.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/brake_circuit.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/mod.rs
Labels: QA Tier 1

#7708 feat(efb): Custom SimBridge IP Address
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
  fbw-a32nx/src/systems/simbridge-client/src/common.ts
  fbw-a32nx/src/systems/simbridge-client/src/components/McduServerClient.ts
Labels: QA Tier 1

#7786 fix(fuel): eliminates inner tank zeroing when re/de-fueling
  fbw-a32nx/src/wasm/fadec_a320/src/EngineControl.h
Labels: QA Tier 1

#7717 feat(hyd): Refactor the THS to work with both mechanical and electrical control
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/trimmable_horizontal_stabilizer.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/trimmable_horizontal_stabilizer.rs
Labels: QA Tier 1

#7698 feat(ewd): Port EWD to MSFS Avionics framework
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/A32NX/EWD/ewd.html
  fbw-a32nx/src/systems/instruments/src/EWD/.eslintrc.js
  fbw-a32nx/src/systems/instruments/src/EWD/AFloor.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/EGT.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/EWD.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/FF.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/FOB.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/FormattedFwcText.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/Idle.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/LowerLeftDisplay.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/LowerRightDisplay.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/N1.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/N1Limit.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/N2.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/PacksNaiWai.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/Slats.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/UpperDisplay.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/config.json
  fbw-a32nx/src/systems/instruments/src/EWD/elements/ADV.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/DownArrow.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/EGT.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/FF.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/FOB.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/Idle.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/LowerLeftDisplay.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/LowerRightDisplay.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/N1.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/N1Limit.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/N2.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/PacksNaiWai.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/STS.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/Slats.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/elements/UpperDisplay.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/index.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/rollup.config.js
  fbw-a32nx/src/systems/instruments/src/EWD/shared/ArincValueProvider.ts
  fbw-a32nx/src/systems/instruments/src/EWD/shared/EwdSimvarPublisher.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/style.scss
  fbw-a32nx/src/systems/instruments/src/EWD/tsconfig.json
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/displayUnit.tsx
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/gauges.scss
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/gauges.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/PFD.tsx
  fbw-a32nx/src/systems/shared/src/autopilot.ts
  igniter.config.mjs
  package.json
Labels: QA Tier 2

#7782 fix: Annunciator Test Function now has no effect without DC BUS 2
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/A32NX_BaseAirliners.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  fbw-a32nx/src/behavior/src/A32NX_Interior_EFIS.xml
  fbw-a32nx/src/behavior/src/A32NX_Interior_Fire.xml
  fbw-a32nx/src/behavior/src/A32NX_Interior_Generics.xml
  fbw-a32nx/src/behavior/src/A32NX_Interior_MCDU.xml
  fbw-a32nx/src/behavior/src/A32NX_Interior_Misc.xml
  fbw-a32nx/src/behavior/src/A32NX_Interior_RMP.xml
  fbw-a32nx/src/systems/instruments/src/ATC/index.tsx
  fbw-a32nx/src/systems/instruments/src/BAT/index.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/Components/Chrono.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/Components/Clock.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/Components/ElapsedTime.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/Clock/shared/ClockSimvarPublisher.tsx
  fbw-a32nx/src/systems/instruments/src/RMP/Components/RadioPanelDisplay.tsx
Labels: QA Tier 1

#7795 feat(fws): Add fuel low warnings
  fbw-a32nx/src/systems/instruments/src/Common/EWDMessages.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Labels: QA Tier 1

#7791 feat(mcdu): Remove INOP W&B from AOC Menu
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_Menu.js
Labels: Waiting on Core Decision

#7748 build: use mach for instruments build
  .github/workflows/experimental.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .gitignore
  fbw-a32nx/.env
  fbw-a32nx/mach.config.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Images/SD/DoorVideoResources/empty.png
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/A32NX/Clock/clock.html
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/A32NX/EWD/ewd.html
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/A32NX/PFD/pfd.html
  fbw-a32nx/src/systems/instruments/README.md
  fbw-a32nx/src/systems/instruments/buildSrc/browserBuild.mjs
  fbw-a32nx/src/systems/instruments/buildSrc/igniter/tasks.mjs
  fbw-a32nx/src/systems/instruments/buildSrc/igniter/worker.mjs
  fbw-a32nx/src/systems/instruments/buildSrc/simulatorBuild.mjs
  fbw-a32nx/src/systems/instruments/buildSrc/templatePlugins.mjs
  fbw-a32nx/src/systems/instruments/src/Clock/config.json
  fbw-a32nx/src/systems/instruments/src/DCDU/pages/SelfTest.tsx
  fbw-a32nx/src/systems/instruments/src/DCDU/pages/WaitingForData.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/ATC/ATC.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Checklists/Checklists.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Checklists/ChecklistsPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Dashboard/Widgets/Reminders/ChecklistsReminder.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Dashboard/Widgets/Reminders/PinnedChartsReminder.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Failures/Pages/Comfort/index.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Failures/Pages/Compact.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Chart/ChartWidget.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/PushbackPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Navigation/Pages/PinnedChartsPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Presets/Widgets/AircraftPresets.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/AircraftOptionsPinProgramsPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/AtsuAocPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/FlyPadPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/RealismPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Settings.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/TODCalculator/Data/Data.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/TODCalculator/Result/Result.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/UtilComponents/Form/SelectInput/SelectInput.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/UtilComponents/TooltipWrapper.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Utils/routing.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/tailwind.config.js
  fbw-a32nx/src/systems/instruments/src/EFB/vite.config.ts
  fbw-a32nx/src/systems/instruments/src/EWD/config.json
  fbw-a32nx/src/systems/instruments/src/EWD/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/style.scss
  fbw-a32nx/src/systems/instruments/src/ISIS/style.scss
  fbw-a32nx/src/systems/instruments/src/ND/styles.scss
  fbw-a32nx/src/systems/instruments/src/PFD/config.json
  fbw-a32nx/src/systems/instruments/src/PFD/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Status/Status.scss
  fbw-a32nx/src/systems/instruments/src/SD/style.scss
  fbw-common/msfs-avionics-mirror/src/sdk/components/FSComponent.ts
  igniter.config.mjs
  package-lock.json
  package.json
Labels: QA Tier 1

#7781 feat: add reset flight plan on DB switch
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_IdentPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  fbw-a32nx/src/systems/fmgc/src/flightplanning/FlightPlanManager.ts
  fbw-a32nx/src/systems/fmgc/src/navigation/Navigation.ts
Labels: QA Tier 1

#7818 feat: automatic brightness and lighting
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Core.js
  fbw-a32nx/src/behavior/src/A32NX_Interior_ISIS.xml
  fbw-a32nx/src/systems/instruments/src/EFB/Efb.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/StatusBar/QuickControls.tsx
  fbw-a32nx/src/systems/instruments/src/ISIS/AutoBrightness.tsx
  fbw-a32nx/src/systems/instruments/src/ISIS/index.tsx
Labels: QA Tier 1

#7834 fix: increase outer to inner tank transfer rate
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
Labels: QA Tier 1
