Repository flybywiresim/aircraft, pull requests merged in 2023-11, with the labels that each got.

#8279 fix(atsu): Departure request page not updating after successful station insert
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_DepartReq.js
Labels: QA Tier 1, QA Passed

#8242 chore: update rust version + disable unsupported optimizations
  Cargo.lock
  Cargo.toml
  fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/structural_flex.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/payload.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_pressure_controller.rs
  fbw-common/src/wasm/systems/systems/src/apu/mod.rs
  fbw-common/src/wasm/systems/systems/src/payload/mod.rs
  fbw-common/src/wasm/systems/systems/src/shared/can_bus.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
  fbw-common/src/wasm/systems/systems/src/structural_flex/mod.rs
  fbw-common/src/wasm/systems/systems_wasm/src/msfs.rs
  igniter.config.mjs
  package.json
  rust-toolchain.toml
  scripts/dev-env/run-local.cmd
  scripts/dev-env/run-local.sh
  scripts/dev-env/run.cmd
  scripts/dev-env/run.sh
Labels: QA Tier 2, QA Passed

#8273 fix(mcdu): Disable alternate time predictions if fuel manually specified
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, QA Passed

#8240 feat(bleed): Ground air start
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_APU.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Core.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FADEC.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  fbw-a32nx/src/behavior/src/A32NX_Interior_Misc.xml
  fbw-a32nx/src/localization/flypad/en.json
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Services/A320_251N/A320Services.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Store/features/groundServicePage.ts
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Apu/Apu.tsx
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Eng/Eng.tsx
  fbw-a32nx/src/wasm/fadec_a320/CMakeLists.txt
  fbw-a32nx/src/wasm/fadec_a320/build.sh
  fbw-a32nx/src/wasm/fadec_a320/src/Arinc429.cpp
  fbw-a32nx/src/wasm/fadec_a320/src/Arinc429.h
  fbw-a32nx/src/wasm/fadec_a320/src/Arinc429Utils.cpp
  fbw-a32nx/src/wasm/fadec_a320/src/Arinc429Utils.h
  fbw-a32nx/src/wasm/fadec_a320/src/EngineControl.h
  fbw-a32nx/src/wasm/fadec_a320/src/FadecGauge.h
  fbw-a32nx/src/wasm/fadec_a320/src/SimVars.h
  fbw-a32nx/src/wasm/systems/a320_systems/src/lib.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/pneumatic.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/pneumatic/wing_anti_ice.rs
  fbw-common/src/wasm/fbw_common/src/inih/ini_type_conversion.h
  fbw-common/src/wasm/systems/systems/src/air_starter_unit/mod.rs
  fbw-common/src/wasm/systems/systems/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/pneumatic/valve.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
  fbw-common/src/wasm/systems/systems_wasm/src/electrical.rs
Labels: QA Tier 1, QA Passed

#8295 fix(MCDU): Fuel Prediction page Layout
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, QA Passed

#8272 feat(efcs): add precontrol to roll angle controller
  .github/CHANGELOG.md
  fbw-a32nx/docs/Configuration/ModelConfiguration.ini
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.h
  fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/LateralNormalLaw.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/LateralNormalLaw.h
Labels: Needs Accuracy Check, QA Tier 2

#8296 fix(hoppie): Remove ATSU/AOC source checks
  .github/CHANGELOG.md
  fbw-common/src/systems/datalink/router/src/webinterfaces/HoppieConnector.ts
Labels: Needs Changelog

#8283 fix(hoppie): Updated Hoppie Poll rate
  fbw-common/src/systems/datalink/router/src/webinterfaces/HoppieConnector.ts
Labels: QA Passed, QA Ready to Test
