Repository flybywiresim/aircraft, pull requests merged in 2023-04, with the labels that each got.

#7715 refactor(w&b): rust refactor of payload management
  .github/CHANGELOG.md
  .gitignore
  Cargo.lock
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Boarding.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Core.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadManager.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/bitFlags.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  fbw-a32nx/src/systems/instruments/src/Common/bitFlags.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Chart/ChartWidget.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Loadsheet/a20nv55.json
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Seating/Constants.ts
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Seating/SeatMapWidget.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/sync.ts
  fbw-a32nx/src/systems/shared/src/bitFlags.ts
  fbw-a32nx/src/wasm/fadec_a320/src/EngineControl.h
  fbw-a32nx/src/wasm/fadec_a320/src/SimVars.h
  fbw-a32nx/src/wasm/systems/a320_systems/Cargo.toml
  fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/lib.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/payload/mod.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/payload/test.rs
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/lib.rs
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/payload.rs
  fbw-a380x/src/wasm/fadec_a380/src/SimVars.h
  fbw-common/src/wasm/systems/systems/Cargo.toml
  fbw-common/src/wasm/systems/systems/src/air_conditioning/acs_controller.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_air.rs
  fbw-common/src/wasm/systems/systems/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/payload/Payload.md
  fbw-common/src/wasm/systems/systems/src/payload/mod.rs
  fbw-common/src/wasm/systems/systems_wasm/src/electrical.rs
  fbw-common/src/wasm/systems/systems_wasm/src/lib.rs
  package.json
Labels: Exp

#7906 fix: update cg for ELAC 103
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadManager.js
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Loadsheet/a20nv55.json
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx
Labels: QA Tier 1

#7817 fix: update fuel system to include center tank transfer and crossfeed capability
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  fbw-a32nx/src/behavior/src/A32NX_Interior_Misc.xml
  fbw-a32nx/src/localization/msfs/de-DE.locPak
  fbw-a32nx/src/localization/msfs/en-US.locPak
  fbw-a32nx/src/localization/msfs/es-ES.locPak
  fbw-a32nx/src/localization/msfs/es-MX.locPak
  fbw-a32nx/src/localization/msfs/fi-FI.locPak
  fbw-a32nx/src/localization/msfs/fr-FR.locPak
  fbw-a32nx/src/localization/msfs/it-IT.locPak
  fbw-a32nx/src/localization/msfs/ja-JP.locPak
  fbw-a32nx/src/localization/msfs/nb-NO.locPak
  fbw-a32nx/src/localization/msfs/nl-NL.locPak
  fbw-a32nx/src/localization/msfs/pl-PL.locPak
  fbw-a32nx/src/localization/msfs/pt-BR.locPak
  fbw-a32nx/src/localization/msfs/pt-PT.locPak
  fbw-a32nx/src/localization/msfs/ru-RU.locPak
  fbw-a32nx/src/localization/msfs/sv-SE.locPak
  fbw-a32nx/src/localization/msfs/zh-CN.locPak
  fbw-a32nx/src/systems/instruments/src/SD/Common/Shapes.tsx
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Fuel/Fuel.tsx
  fbw-a32nx/src/wasm/fadec_a320/src/EngineControl.h
  fbw-a32nx/src/wasm/fadec_a320/src/SimVars.h
Labels: Waiting for PR merge, QA Tier 1

#7929 fix(model): add collision mesh for fire button guards
  .github/CHANGELOG.md
  fbw-a32nx/src/behavior/src/A32NX_Interior_Fire.xml
  fbw-a32nx/src/model/fire-button/fire-button.bin
  fbw-a32nx/src/model/fire-button/fire-button.gltf
  fbw-a32nx/src/model/models.json
Labels: QA Tier 1

#7910 fix(fms): send tuned ndb symbols and nav vor/dme auto
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_SelectedNavaids.js
  fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
  fbw-a32nx/src/systems/fmgc/src/navigation/Navigation.ts
Labels: QA Tier 1

#7931 fix(mode): neo pitch scale
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Checklist/Library.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/behavior/src/A32NX_Interior_Handling.xml
  fbw-a32nx/src/model/models.json
  fbw-a32nx/src/model/trim-decals/trim-decals.bin
  fbw-a32nx/src/model/trim-decals/trim-decals.gltf
Labels: QA Tier 1

#7904 feat(fms): handle non-msfs approach transition coding
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  fbw-a32nx/src/systems/fmgc/src/flightplanning/RawDataMapper.ts
Labels: QA Tier 1

#7927 fix(mcdu): no overfly when forced turn, return to f-pln on tmpy insert
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Labels: QA Tier 1

#7893 fix(press): departing elevation calculation in cpc
  fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_pressure_controller.rs
Labels: QA Tier 1

#7921 fix: only update ewd memo lines on change
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Labels: QA Tier 1

#7952 feat(model): windshield wipers
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Exterior/A32NX_Exterior_Includes.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/behavior/src/A32NX_Windshield.xml
  fbw-a32nx/src/model/models.json
  fbw-a32nx/src/model/wipers/exterior-wipers.bin
  fbw-a32nx/src/model/wipers/exterior-wipers.gltf
  fbw-a32nx/src/model/wipers/flight-deck-wipers.bin
  fbw-a32nx/src/model/wipers/flight-deck-wipers.gltf
Labels: QA Tier 1

#7943 feat(bleed): Implement pressure sensors in bleed system
  .github/CHANGELOG.md
  .gitignore
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Bleed/elements/EngineBleed.tsx
  fbw-a32nx/src/wasm/systems/a320_systems/src/pneumatic.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/pneumatic/wing_anti_ice.rs
  fbw-a380x/docs/a380-simvars.md
  fbw-common/src/wasm/systems/systems/src/apu/mod.rs
Labels: QA Tier 1

#7919 feat(fadec): Impl FADEC GND PWR buttons + corrected Igniter logic
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FADEC.js
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Eng/Eng.tsx
Labels: QA Tier 1

#7962 chore: small changes after msfs sdk update
  fbw-a32nx/mach.config.js
  fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
  fbw-a32nx/src/systems/fmgc/src/efis/EfisVectors.ts
  fbw-a32nx/src/systems/instruments/src/Common/hooks.tsx
  fbw-a32nx/src/systems/shared/src/FlowEventSync.ts
  fbw-a32nx/src/systems/shared/src/GenericDataListenerSync.ts
  fbw-a32nx/src/systems/tcas/src/components/TcasComputer.ts
Labels: QA Tier 1

#7926 feat(hyd): Low speed pump efficiency and refactor cargo door for all planes
  .github/CHANGELOG.md
  Cargo.lock
  fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/cargo_doors.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/cargo_doors.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/mod.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/pumps.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/pushback.rs
Labels: QA Tier 1

#7964 fix(model): windshield detail map
  fbw-a32nx/src/model/wipers/exterior-wipers.bin
  fbw-a32nx/src/model/wipers/flight-deck-wipers.bin
Labels: QA Tier 1

#7958 fix(sd): cab press page limits
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Press/Press.tsx
Labels: QA Tier 1

#7957 fix: off-by-one error in truncateWaypoints
  fbw-a32nx/src/systems/fmgc/src/flightplanning/FlightPlanManager.ts
Labels: QA Tier 1

#7966 feat(efb): Added rounding up to nearest 100 for simbrief fuel auto fill
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
Labels: QA Tier 1

#7887 feat(fmgc): minimums exposed by fmgc
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  fbw-a32nx/src/systems/instruments/src/PFD/AltitudeIndicator.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/DigitalAltitudeReadout.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/shared/ArincValueProvider.ts
  fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
Labels: QA Tier 1

#7982 fix(fmgc): no vapp addition without wind entry
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSpeeds.js
Labels: QA Tier 1
