Repository flybywiresim/aircraft, pull requests merged in 2023-01, with the labels that each got.

#7583 feat(efb): Add estimated boarding time
  .github/CHANGELOG.md
  src/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx
  src/instruments/src/EFB/Localization/de.json
Labels: QA Tier 1, Exp

#7674 fix(efb): landing calculator widget runway shows correct runway heading
  .github/CHANGELOG.md
  src/instruments/src/EFB/Performance/Widgets/RunwayVisualizationWidget.tsx
Labels: QA Tier 1

#7689 fix: Fixed sound, cones and chocks which depend on LIGHT BEACON (ON)) var
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  src/behavior/src/A32NX_Exterior.xml
  src/behavior/src/A32NX_Interior_Handling.xml
  src/systems/a320_systems/src/hydraulic/mod.rs
  src/systems/a320_systems_wasm/src/lib.rs
  src/systems/a380_systems/src/hydraulic/mod.rs
  src/systems/a380_systems_wasm/src/lib.rs
Labels: Exp

#7345 refactor: port SD to full react-based instrument
  flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/A32NX_BaseAirliners.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.js
  src/behavior/src/A32NX_Interior_Misc.xml
  src/instruments/buildSrc/igniter/tasks.mjs
  src/instruments/buildSrc/simulatorBuild.mjs
  src/instruments/buildSrc/templatePlugins.mjs
  src/instruments/ecam-page-template/rollup.js
  src/instruments/ecam-page-template/template.html
  src/instruments/ecam-page-template/template.js
  src/instruments/src/Common/NXUnits.ts
  src/instruments/src/Common/defaults.ts
  src/instruments/src/EWD/index.tsx
  src/instruments/src/SD/DoorVideoResources/empty.png
  src/instruments/src/SD/Pages/Apu/Apu.tsx
  src/instruments/src/SD/Pages/Apu/config.json
  src/instruments/src/SD/Pages/Bleed/Bleed.tsx
  src/instruments/src/SD/Pages/Bleed/config.json
  src/instruments/src/SD/Pages/Cond/Cond.tsx
  src/instruments/src/SD/Pages/Cond/config.json
  src/instruments/src/SD/Pages/Crz/Crz.tsx
  src/instruments/src/SD/Pages/Crz/config.json
  src/instruments/src/SD/Pages/Door/Door.tsx
  src/instruments/src/SD/Pages/Door/config.json
  src/instruments/src/SD/Pages/Elec/Elec.scss
  src/instruments/src/SD/Pages/Elec/Elec.tsx
  src/instruments/src/SD/Pages/Elec/config.json
  src/instruments/src/SD/Pages/Eng/Eng.tsx
  src/instruments/src/SD/Pages/Eng/config.json
  src/instruments/src/SD/Pages/Fctl/Fctl.tsx
  src/instruments/src/SD/Pages/Fctl/config.json
  src/instruments/src/SD/Pages/Fuel/Fuel.tsx
  src/instruments/src/SD/Pages/Fuel/config.json
  src/instruments/src/SD/Pages/Hyd/Hyd.tsx
  src/instruments/src/SD/Pages/Hyd/config.json
  src/instruments/src/SD/Pages/Press/Press.tsx
  src/instruments/src/SD/Pages/Press/config.json
  src/instruments/src/SD/Pages/Status/Status.tsx
  src/instruments/src/SD/Pages/Status/config.json
  src/instruments/src/SD/Pages/Wheel/Wheel.tsx
  src/instruments/src/SD/Pages/Wheel/config.json
  src/instruments/src/SD/PagesContainer.jsx
  src/instruments/src/SD/PagesContainer.tsx
  src/instruments/src/SD/StatusArea/StatusArea.jsx
  src/instruments/src/SD/StatusArea/StatusArea.scss
  src/instruments/src/SD/StatusArea/StatusArea.tsx
  src/instruments/src/SD/Text/Text.scss
  src/instruments/src/SD/Text/Text.tsx
  src/instruments/src/SD/config.json
  src/instruments/src/SD/index.jsx
  src/instruments/src/SD/index.tsx
  src/instruments/src/SD/style.scss
Labels: Exp

#7633 feat: polar heading/track part 1
  .github/CHANGELOG.md
  .vscode/launch.json
  .vscode/tasks.json
  Cargo.lock
  docs/a320-simvars.md
  flybywire-aircraft-a320-neo/html_ui/Fonts/ECAMFontRegular.ttf
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
  src/fmgc/src/components/FcuSync.ts
  src/fmgc/src/components/index.ts
  src/fmgc/src/guidance/lnav/LnavDriver.ts
  src/fonts/ECAMFontRegular_Source.sfd
  src/instruments/src/Common/utils.tsx
  src/instruments/src/ND/elements/ApproachMessage.tsx
  src/instruments/src/ND/elements/RadioNavInfo.tsx
  src/instruments/src/ND/elements/RadioNeedles.tsx
  src/instruments/src/ND/elements/ToWaypointIndicator.tsx
  src/instruments/src/ND/elements/TopMessages.tsx
  src/instruments/src/ND/index.tsx
  src/instruments/src/ND/pages/ArcMode.tsx
  src/instruments/src/ND/pages/PlanMode.tsx
  src/instruments/src/ND/pages/RoseMode.tsx
  src/instruments/src/ND/styles.scss
  src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
  src/instruments/src/PFD/HeadingIndicator.tsx
  src/instruments/src/PFD/HorizontalTape.tsx
  src/instruments/src/PFD/LandingSystemIndicator.tsx
  src/instruments/src/PFD/PFD.svg
  src/instruments/src/PFD/PFD.tsx
  src/instruments/src/PFD/animations.scss
  src/instruments/src/PFD/instrument.tsx
  src/instruments/src/PFD/shared/AdirsValueProvider.tsx
  src/instruments/src/PFD/shared/ArincValueProvider.ts
  src/instruments/src/PFD/shared/DisplayManagementComputer.tsx
  src/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
  src/instruments/src/PFD/shared/SimplaneValueProvider.ts
  src/systems/systems/Cargo.toml
  src/systems/systems/src/navigation/adirs.rs
  src/systems/systems/src/pneumatic/mod.rs
  src/systems/systems/src/pneumatic/valve.rs
  src/systems/systems/src/simulation/test.rs
  src/systems/systems/src/simulation/update_context.rs
Labels: QA Tier 1, Exp

#7630 fix: enable parking brake so aircraft won't move during pre flight
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
Labels: QA Tier 1

#7691 fix: Move cg further aft
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_PayloadManager.js
  src/instruments/src/EFB/Ground/Pages/Payload/Loadsheet/a20nv55.json
  src/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx
Labels: QA Tier 1

#7656 feat(atsu): Coupled atsu and DATALINK STATUS page
  flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATSU_DatalinkStatus.js
  src/atsu/src/ATSU.ts
  src/atsu/src/DatalinkStatusCodes.ts
  src/atsu/src/com/Datalink.ts
Labels: QA Tier 1

#7655 feat: Add aircraft version check and user message when using old version
  .github/CHANGELOG.md
  package-lock.json
  package.json
  scripts/metadata.js
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Localization/de.json
  src/instruments/src/EFB/Localization/en.json
  src/instruments/src/EFB/Settings/Pages/AboutPage.tsx
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/instruments/src/EFB/Utils/AircraftVersionChecker.ts
  src/instruments/src/EFB/index.tsx
  src/instruments/src/EFB/translation.ts
  src/shared/src/popup.ts
Labels: QA Tier 1, Exp

#7716 fix(fmgc): station declination used wrong leg
  src/fmgc/src/flightplanning/LegsProcedure.ts
Labels: QA Tier 1

#7669 feat: Quick Control Panel for the flyPad Status bar
  .github/CHANGELOG.md
  src/instruments/src/EFB/Dashboard/Widgets/FlightWidget.tsx
  src/instruments/src/EFB/Efb.tsx
  src/instruments/src/EFB/Localization/en.json
  src/instruments/src/EFB/Navigation/Navigation.tsx
  src/instruments/src/EFB/Settings/Pages/RealismPage.tsx
  src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
  src/instruments/src/EFB/StatusBar/QuickControls.tsx
  src/instruments/src/EFB/StatusBar/StatusBar.tsx
  src/instruments/src/EFB/UtilComponents/TooltipWrapper.tsx
  src/simbridge-client/src/components/ClientState.ts
  src/simbridge-client/src/components/McduServerClient.ts
  src/systems/systems/src/navigation/adirs.rs
Labels: Quality of Life, EFB, Exp

#7706 fix: PA announcement playing twice and without power to PA
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
Labels: Audio, QA Tier 1

#7730 fix(fuel): Dev States effect on fuel management
  src/fadec/a320_fadec/src/EngineControl.h
  src/fadec/a320_fadec/src/SimVars.h
  src/fadec/a320_fadec/src/ThrustLimits.h
Labels: QA Tier 1

#7714 build: improve c/c++ build for debugging
  .vscode/launch.json
  src/fadec/build.sh
  src/fbw_a320/build.sh
  src/fbw_a380/build.sh
  src/flypad-backend/build.sh
Labels: QA Tier 1, Exp

#7724 fix(eng): oil pressure table
  .github/CHANGELOG.md
  flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
Labels: QA Tier 1, Exp

#7664 feat: option to use 2 independent axis for rudder
  .github/CHANGELOG.md
  fbw-a32nx/docs/Configuration/ModelConfiguration.ini
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.h
  fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.h
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.h
  fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp
  fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.h
Labels: QA Tier 1
