Repository flybywiresim/aircraft, pull requests merged in 2024-04, with the labels that each got.

#8592 feat(fwc): overspeed vmo/mmo
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  fbw-a32nx/src/systems/instruments/src/Common/EWDMessages.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
  fbw-a32nx/src/wasm/systems/a320_systems/src/lib.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
Labels: QA Passed

#8548 chore(efb): Move Auto-Simbrief Import to 3rd party
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/AtsuAocPage.tsx
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/ThirdPartyOptionsPage.tsx
Labels: Do Not Merge, QA Passed

#8583 fix(reverser): Fix wrong MSFS plane acceleration seen from systems wasm
  .github/CHANGELOG.md
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/reversers.rs
  fbw-common/src/wasm/systems/systems/src/engine/reverser_thrust.rs
  fbw-common/src/wasm/systems/systems/src/simulation/update_context.rs
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8573 fix(efb): fuel EFB page visual glitches
  fbw-common/src/systems/instruments/src/EFB/Assets/FuelOutline.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A380_842/A380Fuel.tsx
Labels: QA A380 Only

#8602 fix: boarding rate and align time defaults
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/EFB/Settings/sync.ts
Labels: QA Not Required

#8603 fix: Add missing localization in efb
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8601 fix: lvar for brightness offset of ISIS for it support light presets
  fbw-a32nx/src/systems/instruments/src/ISIS/AutoBrightness.tsx
  fbw-a32nx/src/wasm/extra-backend-a32nx/src/LightingPresets/LightingPresets_A32NX.cpp
  fbw-a32nx/src/wasm/extra-backend-a32nx/src/LightingPresets/LightingPresets_A32NX.h
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8604 feat(fwc): non-cancellable warnings
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FWC.js
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Labels: QA Tier 2, QA Passed

#8593 feat: flyPad Checklists refactor and adaption to A380X
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/config/a32nx_checklists.json5
  fbw-a32nx/src/systems/instruments/src/EFB/index.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/tsconfig.json
  fbw-a380x/src/base/flybywire-aircraft-a380-842/config/a380x_checklists.json5
  fbw-a380x/src/systems/instruments/src/EFB/index.tsx
  fbw-a380x/src/systems/instruments/src/EFB/tsconfig.json
  fbw-common/src/systems/instruments/src/EFB/Checklists/ChecklistItemComponent.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Checklists.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/ChecklistsPage.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/CompletionButton.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/AfterLanding.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/AfterStart.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/Approach.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/BeforeStart.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/CockpitPreparation.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/Landing.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/LineUp.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/Parking.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/SecuringAircraft.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/Taxi.tsx
  fbw-common/src/systems/instruments/src/EFB/Checklists/Lists/index.tsx
  fbw-common/src/systems/instruments/src/EFB/Dashboard/Widgets/Reminders/ChecklistsReminder.tsx
  fbw-common/src/systems/instruments/src/EFB/Efb.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Pushback/PushbackMap.tsx
  fbw-common/src/systems/instruments/src/EFB/StatusBar/StatusBar.tsx
  fbw-common/src/systems/instruments/src/EFB/Store/features/checklists.ts
  fbw-common/src/systems/shared/src/checklists/CheckItemStates.ts
  fbw-common/src/systems/shared/src/checklists/ChecklistInterfaces.ts
  fbw-common/src/systems/shared/src/checklists/ChecklistProvider.ts
  fbw-common/src/systems/shared/src/checklists/index.ts
  fbw-common/src/systems/shared/src/index.ts
  fbw-common/src/systems/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: QA Tier 1, QA Passed, A32NX, A380X

#8606 feat(nws): add better NWS hacks
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/nose_wheel_steering.rs
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/flight_model.cfg
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/nose_wheel_steering.rs
Labels: QA Tier 1, QA Ready to Test

#8614 ci: Rename workflows from 'PR' to more descriptive names
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-build.yml
  .github/workflows/pr-semantics.yml
Labels: QA Not Required

#8554 feat(flight_model): Add drag from landing lights
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/gear.rs
Labels: QA Passed

#8615 fix: Fixed bug in checklist to not display previous checklists as completed
  fbw-common/src/systems/instruments/src/EFB/Checklists/Checklists.tsx
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8565 feat(athr/fadec): improved reverse thrust limit based on TOGA limit
  .github/CHANGELOG.md
  fbw-a32nx/docs/Configuration/ModelConfiguration.ini
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
  fbw-a32nx/src/systems/instruments/src/EWD/N1Limit.tsx
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/Autothrust_data.cpp
  fbw-common/src/wasm/systems/systems/src/engine/reverser_thrust.rs
Labels: QA Tier 1, QA Ready to Test

#8626 fix: Fixing Center Tank transfer
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FADEC.js
  fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/EngineControlA32NX.cpp
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8628 fix: Changing A380X LVar units used in fadec to Number
  fbw-a32nx/src/behavior/src/A32NX_Exterior.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/engines.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Exterior.xml
  fbw-a380x/src/systems/instruments/src/EWD/elements/EGT.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/IgnitionBorder.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/N1.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/ThrustGauge.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Engine/elements/EngineColumn.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Engine/elements/IgnitionBorder.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Engine/elements/StartValve.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Hyd/HydPage.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Hyd/elements/Engine.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Hyd/elements/HydraulicSystem.tsx
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FadecSimData_A380X.hpp
Labels: QA Ready to Test, QA A380 Only, A380X

#8632 docs(fcu): vs/fpa state
  fbw-a32nx/docs/a320-simvars.md
Labels: QA Not Required

#8624 feat(a380-sd): add COND page
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Images/SD_COND.png
  fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedHotAir.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cond/CondPage.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cond/elements/A380Cond.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cond/elements/AvionicsVentilation.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cond/elements/CabinTemperatures.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cond/elements/CargoTemperatures.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cond/elements/CondFan.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cond/elements/CondHotAir.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cond/elements/CondPack.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/CondPage.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cruise/elements/CruiseCond.tsx
  fbw-a380x/src/systems/instruments/src/SD/SystemDisplay.tsx
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning/local_controllers/trim_air_drive_device.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning/local_controllers/ventilation_control_module.rs
Labels: QA Passed, QA Ready to Test, QA A380 Only

#8620 fix(efcs): fix ground spoiler thrust lever idle condition threshold
  .github/CHANGELOG.md
  fbw-a32nx/src/wasm/fbw_a320/src/model/SecComputer.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/SecComputer_data.cpp
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8623 feat(fwc): Link landing light memo to light position
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8511 feat(press): pressurization failures
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  fbw-a32nx/src/systems/failures/src/a320.ts
  fbw-a32nx/src/systems/instruments/src/Common/EWDMessages.tsx
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Crz/Crz.tsx
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Press/Press.tsx
  fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/lib.rs
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_air.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_pressure_controller.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/pressure_valve.rs
  fbw-common/src/wasm/systems/systems/src/failures/mod.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
Labels: QA Tier 2, QA Passed, QA Ready to Test

#8629 refactor(efb): check simbrief a/c type against build
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/EFB/Apis/Simbrief/simbriefInterface.ts
  fbw-common/src/systems/instruments/src/EFB/Apis/Simbrief/simbriefParser.ts
  fbw-common/src/systems/instruments/src/EFB/Dashboard/Widgets/FlightWidget.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A380_842/A380Fuel.tsx
  fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json
  fbw-common/src/systems/instruments/src/EFB/Store/features/simBrief.ts
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8635 build: fixed igniter cache config for cpp wasm
  fbw-common/src/wasm/cpp-msfs-framework/cmake/TargetDefinition.cmake
  igniter.config.mjs
Labels: Waiting on Core Decision, QA Not Required

#8636 fix(fadec): fuel consumption at higher simrates
  .vscode/c_cpp_properties.json
  CMakeLists.txt
  fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/EngineControlA32NX.cpp
  fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/EngineControlA32NX.h
  fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/Fadec_A32NX.cpp
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/EngineControl_A380X.cpp
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/EngineControl_A380X.h
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/Fadec_A380X.cpp
  fbw-common/src/wasm/cpp-msfs-framework/MsfsHandler/MsfsHandler.cpp
  fbw-common/src/wasm/cpp-msfs-framework/MsfsHandler/MsfsHandler.h
  scripts/build-cmake.sh
Labels: QA Tier 1, QA Passed, QA Ready to Test
