Repository flybywiresim/aircraft, pull requests merged in 2024-02, with the labels that each got.

#8454 fix(flight model / bleed air / ice prot): Restore wing anti-ice functionality and simplify bleed air
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  fbw-a32nx/src/behavior/src/A32NX_Interior_Misc.xml
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/lib.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs
  fbw-common/src/wasm/systems/systems_wasm/src/anti_ice.rs
  fbw-common/src/wasm/systems/systems_wasm/src/engines.rs
  fbw-common/src/wasm/systems/systems_wasm/src/lib.rs
Labels: QA Passed

#8437 fix(GSX/Refuel): Allow Refuel Process to finish when GSX L-Vars go 0 due to SimConnect Issues
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
Labels: QA Tier 2, QA Passed

#8408 feat(fbw): reworked flare law
  .github/CHANGELOG.md
  fbw-a32nx/src/wasm/fbw_a320/CMakeLists.txt
  fbw-a32nx/src/wasm/fbw_a320/build.sh
  fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotLaws.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotLaws.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotLaws_data.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotLaws_types.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotStateMachine.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotStateMachine.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/Autothrust.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/Autothrust.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/ElacComputer.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/ElacComputer.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/ElacComputer_types.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/FacComputer.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/FacComputer_types.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/LateralDirectLaw_types.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/LateralNormalLaw.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/LateralNormalLaw.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/PitchAlternateLaw_types.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/PitchDirectLaw_types.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/PitchNormalLaw.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/PitchNormalLaw.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/SecComputer.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/SecComputer_types.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/mod_2RcCQkwc.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/mod_2RcCQkwc.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/mod_Mu9grHF5.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/rt_modd.cpp
Labels: QA Passed

#8447 feat(efb): auto unfocus inputs when camera leaves
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cameras.cfg
  fbw-a32nx/src/systems/instruments/src/EFB/UtilComponents/Form/SimpleInput/SimpleInput.tsx
Labels: QA Tier 1

#8482 fix: Fixed calibration with 2 axes for A380
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/ThrottleConfig/BaseThrottleConfig.tsx
Labels: QA A380 Only

#8486 fix(refuel): fix instant refueling when engines or APU is running
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
Labels: QA Passed

#8484 feat(a380x/fcu): Implement QNH pre-selection; various FCU improvements
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/fcu.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_FCU.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Fonts/NDChrono.ttf
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Pages/VCockpit/Instruments/LegacyA380X/FCU/A380_FCU.css
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Pages/VCockpit/Instruments/LegacyA380X/FCU/A380_FCU.html
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Pages/VCockpit/Instruments/LegacyA380X/FCU/A380_FCU.js
  fbw-a380x/src/fonts/A380X_FCU.sfd
Labels: QA Not Required

#8252 fix: fix ETA of TO waypoint display on ND
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/lnav/LnavDriver.ts
  fbw-common/src/systems/instruments/src/ND/ND.tsx
Labels: QA Tier 1, QA Failed

#8330 refactor(efb/fuel): refueling system changes for future airframe systems
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
  fbw-a32nx/src/systems/instruments/src/EFB/Assets/A380X_Front_Side_Profile_A380_Side_Profile.svg
  fbw-a32nx/src/systems/instruments/src/EFB/Assets/FuelOutline.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Assets/NoseOutline.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Assets/top_down_fueltanks_fill.svg
  fbw-a32nx/src/systems/instruments/src/EFB/Dashboard/Widgets/FlightWidget.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Dispatch/Pages/Overview/A320_251N/A320Overview.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Dispatch/Pages/Overview/A380_842/A380Overview.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Enum/Airframe.ts
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Ground.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A320_251N/A320Fuel.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A380_842/A380Fuel.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Fuel/Fuel.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/sync.ts
  fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp
  fbw-a32nx/src/wasm/systems/a320_systems/src/fuel/mod.rs
  fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp
  fbw-a380x/src/wasm/systems/a380_systems/src/fuel/fuel_quantity_management_system.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/fuel/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/fuel/test.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/lib.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/fuel.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/fuel/mod.rs
Labels: QA Tier 1

#8465 refactor: Refactor pushback for multi aircraft and tune for A320/A380
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/PushbackMap.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/PushbackPage.tsx
  fbw-a32nx/src/wasm/extra-backend-a32nx/CMakeLists.txt
  fbw-a32nx/src/wasm/extra-backend-a32nx/src/Gauge_Extra_Backend.cpp
  fbw-a32nx/src/wasm/extra-backend-a32nx/src/Pushback/Pushback_A32NX.cpp
  fbw-a32nx/src/wasm/extra-backend-a32nx/src/Pushback/Pushback_A32NX.h
  fbw-a380x/src/wasm/extra-backend-a380x/CMakeLists.txt
  fbw-a380x/src/wasm/extra-backend-a380x/src/Gauge_Extra_Backend.cpp
  fbw-a380x/src/wasm/extra-backend-a380x/src/Pushback/Pushback_A380X.cpp
  fbw-a380x/src/wasm/extra-backend-a380x/src/Pushback/Pushback_A380X.h
  fbw-common/src/wasm/cpp-msfs-framework/MsfsHandler/DataManager.h
  fbw-common/src/wasm/cpp-msfs-framework/MsfsHandler/DataTypes/DataDefinitionVariable.hpp
  fbw-common/src/wasm/cpp-msfs-framework/lib/math_utils.hpp
  fbw-common/src/wasm/extra-backend/Pushback/Pushback.cpp
  fbw-common/src/wasm/extra-backend/Pushback/Pushback.h
Labels: QA Tier 1, QA Ready to Test

#8481 feat(efb): update normal checklists with latest airbus changes
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/EFB/Checklists/Lists/Landing.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Checklists/Lists/Parking.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Checklists/Lists/SecuringAircraft.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Checklists/Lists/Taxi.tsx
Labels: QA Tier 1

#8492 feat(a380x): Basic control of auto brake
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/mip.xml
Labels: Do Not Merge, QA Not Required

#8439 feat(a380x): Add legacy FWS, GPWS from A32NX implementation
  fbw-a380x/src/systems/systems-host/index.ts
  fbw-a380x/src/systems/systems-host/systems/LegacyFwc.ts
  fbw-a380x/src/systems/systems-host/systems/LegacyGpws.ts
  fbw-a380x/src/systems/systems-host/systems/LegacySoundManager.ts
  fbw-a380x/src/systems/systems-host/tsconfig.json
Labels: QA Not Required

#8485 fix: Remove old EICAS files
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.css
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.css
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.css
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.html
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.js
Labels: QA Tier 1, QA Ready to Test

#8474 fix(TCAS/ND): TCAS targets disappearing
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/ND/shared/map/CanvasMap.tsx
Labels: QA Tier 1, QA Ready to Test

#8517 fix(a380x/press): landing elevation incorrectly displayed
  fbw-a380x/src/systems/instruments/src/EWD/elements/PseudoFWC.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Cruise/elements/CruisePressure.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Press/elements/LandingElevation.tsx
Labels: QA A380 Only

#8495 refactor: A32NX BatDisplay to fbw-common / add A380 separate BAT instrument
  fbw-a32nx/src/systems/instruments/src/BAT/index.tsx
  fbw-a32nx/src/systems/tsconfig.json
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/mach.config.js
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/Climb.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/approach.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/apron.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/cruise.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/final.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/hangar.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/overhead/electrical.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/overhead/ovhd-inputs.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/runway.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/taxi.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/de-DE.locPak
  fbw-a380x/src/base/flybywire-aircraft-a380-842/en-US.locPak
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Fonts/AirbusBAT.ttf
  fbw-a380x/src/systems/instruments/src/BAT/config.json
  fbw-a380x/src/systems/instruments/src/BAT/index.tsx
  fbw-a380x/src/systems/instruments/src/BAT/style.scss
  fbw-a380x/src/systems/instruments/src/BAT/tsconfig.json
  fbw-a380x/src/systems/tsconfig.json
  fbw-common/src/systems/instruments/src/BAT/BatDisplay.tsx
  fbw-common/src/systems/instruments/src/BAT/index.ts
  fbw-common/src/systems/instruments/src/Clock/style.scss
Labels: Needs Code Review, QA A380 Only

#8504 feat: Added Localazy translation process to A380X locPak
  .gitignore
  fbw-a380x/src/base/flybywire-aircraft-a380-842/es-ES.locPak
  fbw-a380x/src/base/flybywire-aircraft-a380-842/fr-FR.locPak
  fbw-a380x/src/base/flybywire-aircraft-a380-842/it-IT.locPak
  fbw-a380x/src/base/flybywire-aircraft-a380-842/pl-PL.locPak
  fbw-a380x/src/base/flybywire-aircraft-a380-842/pt-BR.locPak
  fbw-a380x/src/base/flybywire-aircraft-a380-842/ru-RU.locPak
  fbw-a380x/src/base/flybywire-aircraft-a380-842/zh-CN.locPak
  fbw-a380x/src/localization/README.md
  fbw-a380x/src/localization/build-locPak-translation.js
  fbw-a380x/src/localization/msfs/README.md
  fbw-a380x/src/localization/msfs/de-DE.locPak
  fbw-a380x/src/localization/msfs/downloaded/.keep
  fbw-a380x/src/localization/msfs/en-US.locPak
  fbw-a380x/src/localization/msfs/es-ES.locPak
  fbw-a380x/src/localization/msfs/es-MX.locPak
  fbw-a380x/src/localization/msfs/fi-FI.locPak
  fbw-a380x/src/localization/msfs/fr-FR.locPak
  fbw-a380x/src/localization/msfs/it-IT.locPak
  fbw-a380x/src/localization/msfs/ja-JP.locPak
  fbw-a380x/src/localization/msfs/localazy-locPak-download-config.json
  fbw-a380x/src/localization/msfs/localazy-locPak-upload-config.json
  fbw-a380x/src/localization/msfs/localazy-locPak-upload-deprecate-config.json
  fbw-a380x/src/localization/msfs/nb-NO.locPak
  fbw-a380x/src/localization/msfs/nl-NL.locPak
  fbw-a380x/src/localization/msfs/pl-PL.locPak
  fbw-a380x/src/localization/msfs/pt-BR.locPak
  fbw-a380x/src/localization/msfs/pt-PT.locPak
  fbw-a380x/src/localization/msfs/ru-RU.locPak
  fbw-a380x/src/localization/msfs/sv-SE.locPak
  fbw-a380x/src/localization/msfs/zh-CN.locPak
  igniter.config.mjs
  package.json
Labels: QA Not Required, QA A380 Only

#8507 fix(elec): always have the apu dc bus powered
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/direct_current.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/mod.rs
Labels: QA A380 Only

#8522 feat(a380-elec): more accurate dc ess behavior
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/CdsDisplayUnit.tsx
  fbw-a380x/src/systems/shared/src/electrical.ts
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
  fbw-a380x/src/wasm/systems/a380_systems/src/avionics_data_communication_network.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/direct_current.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/mod.rs
Labels: QA A380 Only

#8514 fix: QFE text missing
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
Labels: QA Tier 1

#8527 fix(fcu): disable qfe mode
  .github/CHANGELOG.md
  fbw-a32nx/src/behavior/src/A32NX_Interior_FCU.xml
Labels: QA Tier 1

#8502 fix(fuel): Lowered C/D spawn fuel, fixed center tank refueling
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
  fbw-a32nx/src/wasm/fadec_a320/src/EngineControl.h
  fbw-a32nx/src/wasm/fadec_a320/src/SimVars.h
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A320_251N/A320Fuel.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A380_842/A380Fuel.tsx
Labels: QA Tier 2, QA Failed

#8526 fix(A380X): Show 3D Throttles at 0 when IDLE
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
Labels: QA A380 Only
