Repository flybywiresim/aircraft, pull requests merged in 2024-05, with the labels that each got.

#8643 fix(a380x): PFD lint, PFD speed tape Vfe, Vmo, Mmo, Vle
  .eslintrc.js
  fbw-a32nx/docs/a320-simvars.md
  fbw-a380x/src/systems/instruments/src/PFD/.eslintrc.js
  fbw-a380x/src/systems/instruments/src/PFD/AltitudeIndicator.tsx
  fbw-a380x/src/systems/instruments/src/PFD/AttitudeIndicatorFixed.tsx
  fbw-a380x/src/systems/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
  fbw-a380x/src/systems/instruments/src/PFD/DigitalAltitudeReadout.tsx
  fbw-a380x/src/systems/instruments/src/PFD/FMA.tsx
  fbw-a380x/src/systems/instruments/src/PFD/FlightPathDirector.tsx
  fbw-a380x/src/systems/instruments/src/PFD/FlightPathVector.tsx
  fbw-a380x/src/systems/instruments/src/PFD/HeadingIndicator.tsx
  fbw-a380x/src/systems/instruments/src/PFD/HorizontalTape.tsx
  fbw-a380x/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
  fbw-a380x/src/systems/instruments/src/PFD/LowerArea.tsx
  fbw-a380x/src/systems/instruments/src/PFD/PFD.tsx
  fbw-a380x/src/systems/instruments/src/PFD/PFDUtils.tsx
  fbw-a380x/src/systems/instruments/src/PFD/SpeedIndicator.tsx
  fbw-a380x/src/systems/instruments/src/PFD/VerticalSpeedIndicator.tsx
  fbw-a380x/src/systems/instruments/src/PFD/VerticalTape.tsx
  fbw-a380x/src/systems/instruments/src/PFD/instrument.tsx
  fbw-a380x/src/systems/instruments/src/PFD/shared/AdirsValueProvider.tsx
  fbw-a380x/src/systems/instruments/src/PFD/shared/ArincValueProvider.ts
  fbw-a380x/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
  fbw-a380x/src/systems/instruments/src/PFD/shared/SimplaneValueProvider.ts
  fbw-a380x/src/systems/instruments/src/PFD/shared/pixels.scss
  fbw-a380x/src/wasm/fbw_a380/src/model/FacComputer_data.cpp
Labels: QA Not Required, QA A380 Only, A380X

#8655 fix(a380x): disable lower ISIS temporarily
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg
Labels: QA Not Required, A380X

#8653 fix: improved conditions for plane symbol on plan page
  fbw-common/src/systems/instruments/src/ND/pages/plan/index.tsx
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8648 fix(press): delta pressure calculation before adirs on
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Press/Press.tsx
  fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning/local_controllers/outflow_valve_control_module.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning/mod.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_pressure_controller.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/pressure_valve.rs
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8663 fix(a380x): mfd uv map
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg
Labels: QA Not Required

#8662 fix: typescript type resolution
  fbw-a32nx/mach.config.js
  fbw-a32nx/src/systems/atsu/fmsclient/tsconfig.json
  fbw-a32nx/src/systems/instruments/src/DCDU/index.tsx
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Eng/Eng.tsx
  fbw-a32nx/src/systems/sentry-client/tsconfig.json
  fbw-a32nx/src/systems/simbridge-client/tsconfig.json
  fbw-a32nx/src/systems/tcas/tsconfig.json
  fbw-a32nx/src/systems/tsconfig.json
  fbw-a380x/mach.config.js
  fbw-a380x/src/systems/atsu/tsconfig.json
  fbw-a380x/src/systems/fmgc/tsconfig.json
  fbw-a380x/src/systems/tcas/tsconfig.json
  fbw-a380x/src/systems/tsconfig.json
  fbw-common/src/systems/datalink/aoc/tsconfig.json
  fbw-common/src/systems/datalink/atc/tsconfig.json
  fbw-common/src/systems/datalink/router/tsconfig.json
  fbw-common/src/systems/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: QA Not Required
