Repository flybywiresim/aircraft, pull requests merged in 2024-03, with the labels that each got.

#8525 fix(a380x): Latest sound.xml from Boris, FWS callout adaptions
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
  fbw-a380x/src/systems/systems-host/systems/LegacySoundManager.ts
Labels: QA A380 Only

#8470 feat(EFB/SimBrief): Automatically import SimBrief Fuel & Payload (2nd Attempt)
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/EFB/Apis/Simbrief/simbriefParser.ts
  fbw-common/src/systems/instruments/src/EFB/Dashboard/Widgets/FlightWidget.tsx
  fbw-common/src/systems/instruments/src/EFB/Dispatch/Pages/LoadsheetPage.tsx
  fbw-common/src/systems/instruments/src/EFB/Efb.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A320_251N/A320Fuel.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/A320_251N/A320Payload.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/A380_842/A380Payload.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/PayloadElements.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/PayloadPage.tsx
  fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json
  fbw-common/src/systems/instruments/src/EFB/Store/features/simBrief.ts
  fbw-common/src/systems/instruments/src/EFB/UtilComponents/Form/SimpleInput/SimpleInput.tsx
  fbw-common/src/systems/instruments/src/EFB/index.ts
Labels: QA Tier 2, QA Passed, QA Ready to Test

#8440 fix: Crosswind issues
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
Labels: QA Tier 2, QA Ready to Test

#8551 fix: mach and trk text missing in fcu
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
Labels: QA Not Required

#8553 fix(lights): Landing Light movement now only possible with power + position LVAR
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  fbw-a32nx/src/behavior/src/A32NX_Exterior.xml
Labels: QA Tier 1, QA Passed

#8524 fix(efb): pax changes
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/flight_model.cfg
  fbw-a380x/src/wasm/systems/a380_systems/src/payload/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/payload/test.rs
  fbw-common/src/systems/instruments/src/EFB/Dispatch/Pages/Overview/A380_842/A380Overview.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/A320_251N/A320Payload.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/A320_251N/a20nv55.json
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/A380_842/A380Payload.tsx
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/A380_842/a380v3.json
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/Seating/Constants.ts
Labels: QA Tier 1, QA Passed

#8538 docs(github templates): Update PR template wording for A380
  .github/PULL_REQUEST_TEMPLATE.md
Labels: QA Not Required

#8540 feat(hyd): Gravity gear extension switch working for A380X
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
Labels: QA Ready to Test, QA A380 Only

#8513 feat(a380-efcs): various updates
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
  fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp
  fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380LateralDirectLaw.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380LateralDirectLaw_private.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380LateralDirectLaw_types.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380LateralNormalLaw.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380LateralNormalLaw.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchAlternateLaw.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchAlternateLaw.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchAlternateLaw_private.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchAlternateLaw_types.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchDirectLaw.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchDirectLaw_private.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchDirectLaw_types.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchNormalLaw.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchNormalLaw.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchNormalLaw_private.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchNormalLaw_types.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer_data.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer_types.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380SecComputer.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380SecComputer.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380SecComputer_data.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380SecComputer_private.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380SecComputer_types.h
  fbw-a380x/src/wasm/fbw_a380/src/prim/Prim.cpp
Labels: Do Not Merge, QA A380 Only

#8558 fix(CDU): auto weight import in MCDU uses target values with gsx now
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8568 fix(a380): make elec pmp ON p/b momentary, and OFF p/b non-momentary
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
Labels: QA A380 Only

#8534 docs: repo branches
  docs/README.md
Labels: QA Not Required

#8563 fix(a380x/air cond): default start state of air cond system
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/Climb.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/approach.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/apron.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/cruise.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/final.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/hangar.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_Generics.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/runway.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/taxi.flt
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning/cpiom_b.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning/mod.rs
Labels: QA Ready to Test, QA A380 Only

#8574 fix(fma): V/S not properly aligned when value is 0
  fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8557 feat(fac): improve beta estimation
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
  fbw-a32nx/src/wasm/fbw_a320/src/model/FacComputer.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/FacComputer.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/FacComputer_data.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/FacComputer_types.h
  fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8531 feat: Aircraft Presets improvements for A32NX and A380X
  fbw-a32nx/src/wasm/extra-backend-a32nx/src/AircraftPresets/AircraftPresetProcedures_A32NX.h
  fbw-a32nx/src/wasm/fadec_a320/build.sh
  fbw-a32nx/src/wasm/fadec_a320/src/Arinc429.cpp
  fbw-a32nx/src/wasm/fadec_a320/src/Arinc429.h
  fbw-a32nx/src/wasm/fadec_a320/src/Arinc429Utils.cpp
  fbw-a32nx/src/wasm/fadec_a320/src/Arinc429Utils.h
  fbw-a32nx/src/wasm/fadec_a320/src/EngineControl.h
  fbw-a32nx/src/wasm/fadec_a320/src/SimVars.h
  fbw-a32nx/src/wasm/fadec_a320/src/Tables.h
  fbw-a32nx/src/wasm/fadec_a320/src/ThrustLimits.h
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_Misc.xml
  fbw-a380x/src/wasm/extra-backend-a380x/src/AircraftPresets/AircraftPresetProcedures_A380X.h
  fbw-a380x/src/wasm/fadec_a380/CMakeLists.txt
  fbw-a380x/src/wasm/fadec_a380/src/EngineControl.h
  fbw-a380x/src/wasm/fadec_a380/src/SimVars.h
  fbw-a380x/src/wasm/fadec_a380/src/Tables.h
  fbw-a380x/src/wasm/fadec_a380/src/ThrustLimits.h
  fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json
  fbw-common/src/systems/instruments/src/EFB/Presets/Widgets/AircraftPresets.tsx
  fbw-common/src/systems/instruments/src/EFB/Presets/Widgets/Procedures.tsx
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/AboutPage.tsx
  fbw-common/src/systems/instruments/src/EFB/Utils/listener.tsx
  fbw-common/src/wasm/cpp-msfs-framework/MsfsHandler/DataTypes/ManagedDataObjectBase.hpp
  fbw-common/src/wasm/extra-backend/AircraftPresets/AircraftPresets.cpp
  fbw-common/src/wasm/extra-backend/AircraftPresets/AircraftPresets.h
  fbw-common/src/wasm/extra-backend/AircraftPresets/ProcedureStep.h
  fbw-common/src/wasm/extra-backend/LightingPresets/LightingPresets.cpp
  fbw-common/src/wasm/fadec_common/src/common.h
Labels: QA Tier 1, QA Passed, QA Ready to Test, A32NX, A380X

#8570 docs: Fix readme typo
  fbw-a32nx/src/README.md
  fbw-a380x/src/README.md
Labels: QA Not Required

#8552 feat(pfd): add true bearing flag & refactor init
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/providers/DmcPublisher.tsx
  fbw-a32nx/src/systems/instruments/src/ND/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/instrument.tsx
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/providers/DmcPublisher.tsx
  fbw-a380x/src/systems/instruments/src/ND/instrument.tsx
  fbw-a380x/src/systems/instruments/src/PFD/HeadingIndicator.tsx
  fbw-a380x/src/systems/instruments/src/PFD/config.json
  fbw-a380x/src/systems/instruments/src/PFD/instrument.tsx
  fbw-a380x/src/systems/instruments/src/PFD/shared/AdirsValueProvider.tsx
  fbw-a380x/src/systems/instruments/src/PFD/shared/ArincValueProvider.ts
  fbw-a380x/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
  fbw-a380x/src/systems/instruments/src/PFD/shared/SimplaneValueProvider.ts
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8566 feat(efcs-a380): inhibit E(B)HA when on ground and no hydraulics
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchNormalLaw.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchNormalLaw.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer_data.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer_types.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380SecComputer.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380SecComputer.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380SecComputer_data.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380SecComputer_types.h
Labels: QA Tier 1, QA Ready to Test, QA A380 Only

#8516 feat(hyd): A380 auto brakes
  fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/Climb.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_FCU.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/mip.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/runway.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/taxi.flt
  fbw-a380x/src/localization/msfs/en-US.locPak
  fbw-a380x/src/systems/instruments/src/PFD/FMA.tsx
  fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/autobrakes.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/lib.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/autobrakes.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/brake_circuit.rs
  fbw-common/src/wasm/systems/systems/src/structural_flex/wing_flex.rs
Labels: QA Ready to Test, QA A380 Only

#8587 fix: Fixed input parser for ICAO for weather widget
  fbw-common/src/systems/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8586 build: enable mem info for su15
  fbw-a32nx/src/wasm/fadec_a320/build.sh
  fbw-a32nx/src/wasm/fbw_a320/build.sh
  fbw-a380x/src/wasm/fadec_a380/build.sh
  fbw-a380x/src/wasm/fbw_a380/build.sh
  fbw-common/src/wasm/cpp-msfs-framework/cmake/TargetDefinition.cmake
  fbw-common/src/wasm/terronnd/build.sh
Labels: QA Not Required

#8582 fix(fms): pd format accepts sign
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8597 fix(a380x/model): by repsol: lights, model & texture changes
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_EXTERIOR.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/engines.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/systems.cfg
Labels: QA Not Required, QA A380 Only
