Repository flybywiresim/aircraft, pull requests merged in 2024-07, with the labels that each got.

#8493 feat(fms): fms-v2 aircraft specific config / VNAV parameters
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/A320AircraftConfig.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/A380AircraftConfig.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/AircraftConfigTypes.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/DataManager.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/FlightPlanService.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/WaypointEntryUtils.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/interface/DisplayInterface.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/plans/FlightPlan.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/plans/performance/FlightPlanPerformanceData.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/lnav/LnavDriver.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/CostIndex.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/CruiseToDescentCoordinator.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/EngineModel.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/FlightModel.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/Predictions.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/VerticalProfileManager.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/VnavDriver.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/climb/ClimbPathBuilder.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/climb/ClimbStrategy.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/cruise/CruisePathBuilder.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/ApproachPathBuilder.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/DescentPathBuilder.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/DescentStrategy.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/GeometricPathBuilder.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/TacticalDescentPathBuilder.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/takeoff/TakeoffPathBuilder.ts
  fbw-a32nx/src/systems/fmgc/src/index.ts
  fbw-a32nx/src/systems/fmgc/src/navigation/Navigation.ts
Labels: QA Passed, QA Ready to Test, A32NX, A380X

#8735 fix: check for null for perf data
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Labels: QA Tier 1, QA Passed

#8737 fix(efb): fix invisible text with light theme
  fbw-common/src/systems/instruments/src/EFB/Performance/Widgets/TakeoffWidget.tsx
Labels: QA Passed

#8641 feat(efb): Simrate and Pause at T/D in EFB Quick Settings
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/TodGuidance.ts
  fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/RealismPage.tsx
  fbw-common/src/systems/instruments/src/EFB/StatusBar/QuickControls.tsx
  fbw-common/src/systems/instruments/src/EFB/StatusBar/StatusBar.tsx
  fbw-common/src/systems/instruments/src/react/persistence.tsx
  package.json
  pnpm-lock.yaml
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8733 feat(pfd): (a32nx, third try): Add vertical deviation indicator, ROW/ROP/OANS warnings v3
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
  fbw-a32nx/src/systems/instruments/src/EWD/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/PFD.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/SpeedIndicator.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/animations.scss
  fbw-a32nx/src/systems/instruments/src/PFD/config.json
  fbw-a32nx/src/systems/instruments/src/PFD/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/shared/ArincValueProvider.ts
  fbw-a32nx/src/systems/instruments/src/PFD/shared/SimplaneValueProvider.ts
  fbw-a32nx/src/systems/instruments/src/PFD/tsconfig.json
  fbw-a32nx/src/systems/tsconfig.json
Labels: QA Tier 2, QA Passed

#8704 fix(fms): fix uplink crash for airway terminations not on airways
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/plans/BaseFlightPlan.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/uplink/CoRouteUplinkAdapter.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/uplink/SimBriefUplinkAdapter.ts
Labels: QA Passed

#8745 feat(fms): implement intercepts of track-to-fix legs
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/plans/BaseFlightPlan.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/Geometry.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/geometry/GeometryFactory.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/lnav/TransitionPicker.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/lnav/legs/IF.ts
Labels: QA Passed

#8644 fix(FMA): LVR CLB not showing when preselected speed becomes active
  fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8666 fix: AOC INIT/REVIEW page - ON and OFF time logic.
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_Init.js
Labels: QA Passed

#8714 feat(a380x): PFD THS indicator
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Images/TRIM_INDICATOR.png
  fbw-a380x/src/systems/instruments/src/PFD/.eslintrc.js
  fbw-a380x/src/systems/instruments/src/PFD/LowerArea.tsx
  fbw-a380x/src/systems/instruments/src/PFD/PFD.tsx
  fbw-a380x/src/systems/instruments/src/PFD/PitchTrimIndicator.tsx
  fbw-a380x/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
  fbw-a380x/src/systems/instruments/src/PFD/style.scss
Labels: QA Not Required, A380X

#8757 fix(efb): display local charts when selected through pinned charts menu
  fbw-common/src/systems/instruments/src/EFB/Navigation/Pages/PinnedChartsPage.tsx
Labels: QA Tier 1, QA Passed

#8760 fix(mcdu): INIT B page - ZFW autofill unit conversion while boarding
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Labels: QA Passed

#8769 fix: ini library folder creation
  fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/FuelConfiguration_A32NX.cpp
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FuelConfiguration_A380X.cpp
  fbw-common/src/wasm/cpp-msfs-framework/CMakeLists.txt
  fbw-common/src/wasm/cpp-msfs-framework/lib/inih/ini_fbw.h
  fbw-common/src/wasm/cpp-msfs-framework/lib/inih/ini_type_conversion.h
  fbw-common/src/wasm/extra-backend/LightingPresets/LightingPresets.h
Labels: QA Passed

#8741 chore(a380x): Update Memos of ATA 24, 29 & 32 to reflect A380
  fbw-a380x/src/systems/instruments/src/Common/EWDMessages.tsx
  fbw-a380x/src/systems/systems-host/systems/PseudoFWC.ts
Labels: QA Not Required, A380X

#8771 feat(pfd): 380 vertical fma improvements
  fbw-a380x/src/systems/instruments/src/PFD/FMA.tsx
Labels: QA Not Required, A380X

#8747 fix(fwc): NW STRG DISC color fix
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Labels: QA Passed

#8765 fix(a380x): fix ISIS brightness plus/minus buttons
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_ISIS.xml
Labels: QA Not Required, A380X

#8766 fix(fms): fix vnav crash on steep approaches
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/ApproachPathBuilder.ts
Labels: QA Tier 2, QA Passed

#8778 feat(a380x): TERR ON ND
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/efis-cp.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg
  fbw-a380x/src/systems/instruments/src/Common/definitions.scss
  fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx
  fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay.tsx
  fbw-a380x/src/systems/instruments/src/ND/instrument.tsx
  fbw-a380x/src/wasm/systems/a380_systems/src/lib.rs
Labels: QA Not Required, A380X
