Repository flybywiresim/aircraft, pull requests merged in 2024-06, with the labels that each got.

#8585 build: bump fbw dev env
  CMakeLists.txt
  fbw-a32nx/src/wasm/fbw_a320/build.sh
  fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/fuel/mod.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/payload/mod.rs
  fbw-a380x/src/wasm/fbw_a380/build.sh
  fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/fuel/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/payload/mod.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/acs_controller.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/mod.rs
  fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
  fbw-common/src/wasm/terronnd/build.sh
  rust-toolchain.toml
  scripts/dev-env/run-local.cmd
  scripts/dev-env/run-local.sh
  scripts/dev-env/run.cmd
  scripts/dev-env/run.sh
Labels: QA Tier 1, QA Passed, QA Ready to Test, SU15

#8627 chore: adapt rust build to SU15
  .cargo/config.toml
  fbw-a32nx/src/wasm/fbw_a320/build.sh
  fbw-a380x/src/wasm/fbw_a380/build.sh
Labels: QA Tier 1, QA Passed, QA Ready to Test, SU15

#8651 fix(a380x): Correct flap/slats positions
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/systems/instruments/src/PFD/.eslintrc.js
  fbw-a380x/src/systems/instruments/src/PFD/LowerArea.tsx
  fbw-a380x/src/systems/instruments/src/PFD/style.scss
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/flaps_computer.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
  fbw-common/src/wasm/systems/systems/src/enhanced_gpwc/mod.rs
  fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
Labels: QA A380 Only, A380X

#7787 fix(lg): nose gear park brake light
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/behavior/src/A32NX_Exterior.xml
  fbw-a32nx/src/behavior/src/A32NX_Interior_Generics.xml
Labels: QA Tier 1, QA Passed

#8684 fix(charts): plane symbol not visible
  .github/workflows/pr-build.yml
  fbw-common/src/systems/instruments/src/EFB/Navigation/Navigation.tsx
  fbw-common/src/systems/instruments/src/EFB/Navigation/Pages/NavigraphPage/NavigraphChartSelector.tsx
Labels: QA Passed

#8672 feat(elac): enable use of both FMGC bus inputs for AP
  fbw-a32nx/src/wasm/fbw_a320/src/model/ElacComputer.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/ElacComputer.h
  fbw-a32nx/src/wasm/fbw_a320/src/model/ElacComputer_data.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/model/ElacComputer_types.h
Labels: QA Passed

#8670 feat: localiser backbeam approaches
  .github/CHANGELOG.md
  .vscode/c_cpp_properties.json
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/plans/performance/FlightPlanPerformanceData.ts
  fbw-a32nx/src/systems/fmgc/src/navigation/LandingSystemSelectionManager.ts
  fbw-a32nx/src/systems/fmgc/src/navigation/NavaidTuner.ts
  fbw-a32nx/src/systems/instruments/src/ISIS/LandingSystem.tsx
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/providers/FMBusPublisher.ts
  fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/HeadingIndicator.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Press/Press.tsx
  fbw-a32nx/src/wasm/fbw_a320/build.sh
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.h
  fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Pushback/PushbackPage.tsx
  fbw-common/src/systems/instruments/src/ND/pages/rose/Glideslope.tsx
  fbw-common/src/systems/instruments/src/ND/pages/rose/RoseLSPage.tsx
  fbw-common/src/systems/instruments/src/ND/style.scss
  fbw-common/src/systems/instruments/src/ND/types/GenericFlightManagementBusEvents.ts
  fbw-common/src/systems/shared/src/ApproachUtils.ts
  fbw-common/src/systems/shared/src/MathUtils.spec.ts
  fbw-common/src/systems/shared/src/MathUtils.ts
  fbw-common/src/wasm/utils/MathUtils.h
Labels: QA Tier 1, QA Passed

#8702 fix(build): a380x experimental build fix
  .github/workflows/a380x-exp.yml
Labels: QA Not Required

#8700 fix: airplane symbol with offsets
  fbw-common/src/systems/instruments/src/EFB/Navigation/Navigation.tsx
Labels: QA Passed

#8696 fix(nd): fix active leg navaid color
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/ND/shared/map/WaypointLayer.ts
Labels: QA Passed

#8703 fix: telex reporting of origin/dest
  fbw-a32nx/src/systems/fmgc/src/flightplanning/new/FlightPlanService.ts
Labels: QA Passed

#8693 feat(a380x): true/mag button
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/fcu.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Pages/VCockpit/Instruments/LegacyA380X/FCU/A380_FCU.js
Labels: QA Not Required, A380X

#8694 feat(a380x): split out aco configs and implement a380
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
  fbw-a32nx/src/systems/instruments/src/EFB/Pages/AutomaticCallOutsPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/index.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/settingsSync.ts
  fbw-a32nx/src/systems/shared/src/AutoCallOuts.ts
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
  fbw-a380x/src/systems/instruments/src/EFB/Pages/AutomaticCallOutsPage.tsx
  fbw-a380x/src/systems/instruments/src/EFB/index.tsx
  fbw-a380x/src/systems/instruments/src/EFB/settingsSync.ts
  fbw-a380x/src/systems/shared/src/AutoCallOuts.ts
  fbw-a380x/src/systems/systems-host/systems/LegacyGpws.ts
  fbw-a380x/src/systems/systems-host/systems/LegacySoundManager.ts
  fbw-common/src/systems/instruments/src/EFB/AircraftContext.ts
  fbw-common/src/systems/instruments/src/EFB/Efb.tsx
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/AircraftOptionsPinProgramsPage.tsx
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/AudioPage.tsx
  fbw-common/src/systems/instruments/src/EFB/Settings/sync.ts
  fbw-common/src/systems/instruments/src/EFB/index.ts
  fbw-common/src/systems/shared/src/index.ts
Labels: QA Tier 1

#8690 fix(press): excess residual pressure warning with adirs off
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
  fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs
  fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_pressure_controller.rs
Labels: QA Tier 1, QA Passed

#8678 feat(a32nx): takeoff performance calculator
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/EFB/config.json
  fbw-a32nx/src/systems/instruments/src/EFB/index.tsx
  fbw-a32nx/src/systems/shared/src/performance/a32nx_landing.ts
  fbw-a32nx/src/systems/shared/src/performance/a32nx_takeoff.ts
  fbw-a32nx/src/systems/shared/src/performance/tsconfig.json
  fbw-a380x/src/systems/instruments/src/EFB/index.tsx
  fbw-common/src/systems/instruments/src/EFB/AircraftContext.ts
  fbw-common/src/systems/instruments/src/EFB/Assets/Efb.scss
  fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json
  fbw-common/src/systems/instruments/src/EFB/Performance/Calculators/CommonCalculations.ts
  fbw-common/src/systems/instruments/src/EFB/Performance/Data/Runways.ts
  fbw-common/src/systems/instruments/src/EFB/Performance/Performance.tsx
  fbw-common/src/systems/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx
  fbw-common/src/systems/instruments/src/EFB/Performance/Widgets/TakeoffWidget.tsx
  fbw-common/src/systems/instruments/src/EFB/Store/features/performance.ts
  fbw-common/src/systems/instruments/src/EFB/UtilComponents/Form/SelectInput/SelectInput.tsx
  fbw-common/src/systems/instruments/src/EFB/UtilComponents/Form/SimpleInput/SimpleInput.tsx
  fbw-common/src/systems/navdata/client/backends/Msfs/Mapping.ts
  fbw-common/src/systems/shared/src/index.ts
  fbw-common/src/systems/shared/src/performance/index.ts
  fbw-common/src/systems/shared/src/performance/landing.ts
  fbw-common/src/systems/shared/src/performance/takeoff.ts
  fbw-common/src/typings/flybywire-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/FlightElements/navdata.d.ts
Labels: QA Tier 2, QA Passed

#8707 chore: bump typescript to 5.5
  package.json
  pnpm-lock.yaml
Labels: QA Tier 2, QA Passed

#8712 fix(mcdu): remove v-speed auto-fill
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSpeeds.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, QA Passed

#8708 chore: bump msfs-sdk to v0.8.0 (su15)
  package.json
  pnpm-lock.yaml
Labels: QA Tier 2, QA Passed
