Repository flybywiresim/aircraft, pull requests merged in 2024-01, with the labels that each got.

#8336 fix(lights): Fixed Lighting Auto Config on spawn
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Core.js
  fbw-a32nx/src/systems/systems-host/index.ts
Labels: QA Tier 1

#8347 fix: Pitch trim on approach
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
Labels: QA Passed

#8352 fix(model): add missing window views
  fbw-a32nx/src/model/models.json
  fbw-a32nx/src/model/modelsv2.json
Labels: QA Tier 1, QA Passed

#8314 fix(apu/gpws/fms): stop using sim altimeters
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_GPSMonitor.js
  fbw-common/src/wasm/systems/systems/src/apu/electronic_control_box.rs
  fbw-common/src/wasm/systems/systems/src/apu/mod.rs
Labels: QA Tier 1, QA Passed

#8384 fix(build): nd dependencies
  fbw-a32nx/src/systems/instruments/buildSrc/igniter/tasks.mjs
  fbw-a32nx/src/systems/instruments/src/ND/config.json
  fbw-a380x/src/systems/instruments/buildSrc/igniter/tasks.mjs
  fbw-a380x/src/systems/instruments/src/ND/config.json
Labels: QA Not Required

#8344 fix: ground track bug out of bounds
  fbw-a32nx/src/systems/instruments/src/PFD/HeadingIndicator.tsx
Labels: QA Tier 1, QA Passed

#8016 fix(system): origin/dest not reported to API
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/fmgc/src/flightplanning/FlightPlanManager.ts
  fbw-common/src/systems/datalink/router/src/webinterfaces/NXApiConnector.ts
Labels: FPM, QA Tier 1, QA Passed

#8328 fix(fma): continuation of presel text fix
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Fonts/fbw-a32nx/ECAMFontRegular.ttf
  fbw-a32nx/src/fonts/ECAMFontRegular_Source.sfd
  fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx
Labels: QA Tier 1, QA Passed

#8327 fix: inhibit PACKS indication when FADECS are off
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/EWD/PacksNaiWai.tsx
Labels: QA Tier 1, QA Passed

#8383 fix(nd): chrono rendering bug hack
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/ND/Chrono.tsx
Labels: QA Tier 1, QA Passed

#8303 feat(nxapi): Decrease TELEX API poll rate to random number 45-75.
  .github/CHANGELOG.md
  fbw-common/src/systems/datalink/router/src/webinterfaces/NXApiConnector.ts
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8395 fix(autoflight): engage managed speed after v2 confirm
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, QA Passed

#8400 fix: remove upload of fragments to github
  .github/workflows/master.yml
Labels: QA Not Required

#8404 fix(efcs): fix blue hyd condition for ELAC 2 standby elec supply
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
Labels: QA Passed

#8405 feat(GSX): GSX Integration for Chocks and Cones
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/GSX.cfg
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
  fbw-a32nx/src/behavior/src/A32NX_Exterior.xml
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/ThirdPartyOptionsPage.tsx
Labels: QA Tier 1, QA Passed

#8403 fix(GSX): Fixed GSX pin not actually disabling NWS
  .github/CHANGELOG.md
  fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/lib.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/bypass_pin.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/mod.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/nose_steering.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/pushback.rs
Labels: QA Tier 1, QA Passed

#8335 chore: upgrade msfssdk to v0.7
  fbw-a32nx/src/systems/instruments/src/EWD/FormattedFwcText.tsx
  fbw-a32nx/src/systems/instruments/src/ND/instrument.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/instrument.tsx
  package.json
  pnpm-lock.yaml
Labels: QA Tier 1, QA Passed

#8247 feat(efb/fbw): Support for TO/GA button built into the throttle (not on axis)
  .github/CHANGELOG.md
  fbw-a32nx/src/localization/flypad/en.json
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
  fbw-common/src/wasm/fbw_common/src/ThrottleAxisMapping.cpp
  fbw-common/src/wasm/fbw_common/src/ThrottleAxisMapping.h
Labels: QA Tier 2, QA Passed

#8421 fix(FCU): Fix Mach Decimal
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
Labels: QA Tier 1, QA Passed

#8358 feat(elec): implement variable frequency generator and fix A380 electrical config
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/wasm/systems/a320_systems/src/electrical/alternating_current.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/electrical/mod.rs
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/alternating_current.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/mod.rs
  fbw-common/src/wasm/systems/systems/src/electrical/battery_charge_rectifier_unit.rs
  fbw-common/src/wasm/systems/systems/src/electrical/engine_generator.rs
  fbw-common/src/wasm/systems/systems/src/electrical/mod.rs
  fbw-common/src/wasm/systems/systems/src/engine/leap_engine.rs
  fbw-common/src/wasm/systems/systems/src/engine/mod.rs
  fbw-common/src/wasm/systems/systems/src/engine/trent_engine.rs
  fbw-common/src/wasm/systems/systems/src/overhead/mod.rs
Labels: QA Passed

#8398 fix(fms): discard approaches with no runway
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
Labels: QA Tier 1

#8418 feat(A380X): Added systems-host and extras-host to A380X
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Pages/VCockpit/Instruments/A380X/ExtrasHost/extras-host.html
  fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Pages/VCockpit/Instruments/A380X/SystemsHost/systems-host.html
  fbw-a380x/src/systems/extras-host/README.md
  fbw-a380x/src/systems/extras-host/build.js
  fbw-a380x/src/systems/extras-host/index.ts
  fbw-a380x/src/systems/extras-host/modules/common/AircraftPresetsList.ts
  fbw-a380x/src/systems/extras-host/modules/common/ExtrasSimVarPublisher.ts
  fbw-a380x/src/systems/extras-host/modules/key_interceptor/KeyInterceptor.ts
  fbw-a380x/src/systems/extras-host/modules/pushbutton_check/PushbuttonCheck.ts
  fbw-a380x/src/systems/extras-host/modules/version_check/VersionCheck.ts
  fbw-a380x/src/systems/extras-host/tsconfig.json
  fbw-a380x/src/systems/fmgc/src/components/ReadySignal.ts
  fbw-a380x/src/systems/fmgc/src/components/index.ts
  fbw-a380x/src/systems/systems-host/README.md
  fbw-a380x/src/systems/systems-host/build.js
  fbw-a380x/src/systems/systems-host/index.ts
  fbw-a380x/src/systems/systems-host/systems/atsu.ts
  fbw-a380x/src/systems/systems-host/systems/powersupply.ts
  fbw-a380x/src/systems/systems-host/tsconfig.json
  igniter.config.mjs
  package.json
Labels: QA Not Required

#8393 feat(A380X): A380X support for Lighting Presets
  fbw-a32nx/src/wasm/extra-backend-a32nx/src/LightingPresets/LightingPresets_A32NX.cpp
  fbw-a32nx/src/wasm/extra-backend-a32nx/src/LightingPresets/LightingPresets_A32NX.h
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/Climb.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/approach.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/apron.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/cruise.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/final.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/hangar.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/runway.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/taxi.flt
  fbw-a380x/src/wasm/extra-backend-a380x/src/Gauge_Extra_Backend.cpp
  fbw-a380x/src/wasm/extra-backend-a380x/src/LightingPresets/LightingPresets_A380X.cpp
  fbw-a380x/src/wasm/extra-backend-a380x/src/LightingPresets/LightingPresets_A380X.h
  fbw-common/src/wasm/cpp-msfs-framework/MsfsHandler/DataManager.h
  fbw-common/src/wasm/extra-backend/LightingPresets/LightingPresets.cpp
  fbw-common/src/wasm/extra-backend/LightingPresets/LightingPresets.h
Labels: QA Passed

#8407 feat(GSX): Automatically start Refuel Process & allow Instant Refuel with GSX Fuel Sync enabled
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Refuel.js
  fbw-a32nx/src/localization/flypad/en.json
  fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
Labels: QA Passed

#8424 fix(FMS): PROG Page REC MAX Upper Limit
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Passed

#8409 fix(A380X): Fix throttle calibration for A380X
  fbw-a32nx/src/localization/flypad/en.json
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/ThrottleConfig/BaseThrottleConfig.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
  fbw-a32nx/src/systems/instruments/src/EFB/Settings/ThrottleConfig/ThrottleSimVar.tsx
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
  fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp
  fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.h
  fbw-common/src/wasm/fbw_common/src/ThrottleAxisMapping.cpp
  fbw-common/src/wasm/fbw_common/src/ThrottleAxisMapping.h
Labels: QA Passed

#8442 fix(nd): adf tuning flags
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/ND/shared/RadioNavInfo.tsx
Labels: QA Not Required
