Repository flybywiresim/aircraft, pull requests merged in 2024-08, with the labels that each got.

#8701 feat(a380x): port ewd to msfs avionics framework
  fbw-a380x/mach.config.js
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/systems/instruments/src/Common/EWDMessages.tsx
  fbw-a380x/src/systems/instruments/src/EWD/.eslintrc.js
  fbw-a380x/src/systems/instruments/src/EWD/EWD.tsx
  fbw-a380x/src/systems/instruments/src/EWD/EngineWarningDisplay.tsx
  fbw-a380x/src/systems/instruments/src/EWD/config.json
  fbw-a380x/src/systems/instruments/src/EWD/elements/AttentionGetter.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/BleedSupply.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/Checklist.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/EGT.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/EWDMemo.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/EngineGauge.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/FormattedFwcText.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/Idle.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/IgnitionBorder.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/N1.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/PseudoFWC.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/ThrustGauge.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/ThrustRatingMode.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/WdLimitations.tsx
  fbw-a380x/src/systems/instruments/src/EWD/elements/WdMemos.tsx
  fbw-a380x/src/systems/instruments/src/EWD/index.tsx
  fbw-a380x/src/systems/instruments/src/EWD/instrument.tsx
  fbw-a380x/src/systems/instruments/src/EWD/shared/ArincValueProvider.ts
  fbw-a380x/src/systems/instruments/src/EWD/shared/EwdSimvarPublisher.tsx
  fbw-a380x/src/systems/instruments/src/EWD/style.scss
  fbw-a380x/src/systems/instruments/src/EWD/tsconfig.json
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/definitions.scss
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/gauges.scss
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/gauges.tsx
Labels: A380X

#8770 fix(engine): Engine fixes part1
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FuelConfiguration_A380X.h
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/Polynomials_A380X.hpp
Labels: A380X

#8136 fix(gpws): fixed mode 4 logic
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/Climb.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/approach.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/apron.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cruise.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/hangar.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/taxi.flt
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Labels: QA Tier 1, QA Passed

#8772 chore(a380): add a380 fire protection ECAM messages ATA26
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/AbnormalSensed/ata26.tsx
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/index.tsx
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsAbnormalSensed.ts
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts
Labels: QA Not Required, A380X

#8775 chore(a380): Add surveillance memos
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/index.tsx
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsAbnormalSensed.ts
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsMemos.ts
Labels: A380X

#8777 fix(a380x): Engines: Fix EGT and spool up time
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/engines.cfg
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/EngineControl_A380X.cpp
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FadecSimData_A380X.hpp
  fbw-a380x/src/wasm/fadec_a380x/src/Fadec/Polynomials_A380X.hpp
Labels: QA Not Required, A380X

#8768 fix(a32nx): FMS: Only check "TO SPEEDS TO LOW" condition if V speeds are set
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Labels: QA Tier 1, QA Passed

#8811 fix(fms): gs intcp altitude
  fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/BaseFlightPlan.ts
  fbw-common/src/systems/navdata/client/backends/Msfs/Mapping.ts
Labels: QA Tier 1, QA Passed

#8689 chore: use new jest style config
  jest.config.js
Labels: Waiting For Response, QA Not Required

#8809 fix(fws): landing memo gear logic
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Labels: QA Tier 1, QA Passed

#8804 fix: Tweaks to takeoff performance calculator to improve accuracy
  fbw-a32nx/src/systems/shared/src/performance/a32nx_takeoff.ts
Labels: QA Tier 1, QA Passed, QA Ready to Test

#8815 feat(a380x): New issue template for A380X bug reports
  .github/ISSUE_TEMPLATE/bug_report_a32nx.yaml
  .github/ISSUE_TEMPLATE/bug_report_a380x.yaml
  .github/ISSUE_TEMPLATE/feature_request_beta.yaml
  fbw-a380x/README.md
Labels: QA Not Required

#8825 fix(pfd): build deps
  fbw-a32nx/src/systems/instruments/src/PFD/config.json
  fbw-a380x/src/systems/instruments/src/PFD/config.json
Labels: QA Not Required

#8808 feat(a380-prim): splr fixes and updates
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
  fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer.h
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer_data.cpp
  fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer_types.h
Labels: A380X

#8645 feat(a380x-fire): fire protection system
  fbw-a32nx/src/wasm/systems/a320_systems/src/lib.rs
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/Interior/A32NX_Interior_Includes.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_Engine.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/overhead/fire.xml
  fbw-a380x/src/systems/failures/src/a380.ts
  fbw-a380x/src/wasm/extra-backend-a380x/src/AircraftPresets/AircraftPresetProcedures_A380X.h
  fbw-a380x/src/wasm/systems/a380_systems/Cargo.toml
  fbw-a380x/src/wasm/systems/a380_systems/src/fire_and_smoke_protection.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/lib.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/fire.rs
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs
  fbw-common/src/systems/shared/src/ata.ts
  fbw-common/src/wasm/systems/systems/src/apu/electronic_control_box.rs
  fbw-common/src/wasm/systems/systems/src/apu/mod.rs
  fbw-common/src/wasm/systems/systems/src/failures/mod.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
Labels: A380X

#8840 chore: use uniform es target for all code
  fbw-a32nx/src/systems/atsu/fmsclient/tsconfig.json
  fbw-a32nx/src/systems/failures/tsconfig.json
  fbw-a32nx/src/systems/sentry-client/tsconfig.json
  fbw-a32nx/src/systems/simbridge-client/tsconfig.json
  fbw-a32nx/src/systems/tcas/tsconfig.json
  fbw-a32nx/src/systems/tsconfig.json
  fbw-a380x/src/systems/atsu/tsconfig.json
  fbw-a380x/src/systems/failures/tsconfig.json
  fbw-a380x/src/systems/tcas/tsconfig.json
  fbw-a380x/src/systems/tsconfig.json
  fbw-common/src/systems/datalink/aoc/tsconfig.json
  fbw-common/src/systems/datalink/atc/tsconfig.json
  fbw-common/src/systems/datalink/router/tsconfig.json
  fbw-common/src/systems/navdata/tsconfig.json
  fbw-common/src/systems/tsconfig.json
Labels: QA Tier 2, QA Passed

#8817 fix(a380x): SD WHEEL: Remove abnormal indications, add gear and gear door status
  fbw-a380x/src/systems/instruments/src/SD/Pages/BleedPage.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/CruisePage.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/WheelPage.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/elements/Accumulator.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/elements/Gear.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/elements/PowerSupply.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/elements/Wheel.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/elements/WheelBogey.tsx
Labels: QA Not Required, A380X

#8836 feat(fmgc): selected navaids reset on done phase
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
  fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
  fbw-a32nx/src/systems/fmgc/src/efis/EfisVectors.ts
  fbw-a32nx/src/systems/fmgc/src/flightphase/FlightPhaseManager.ts
  fbw-a32nx/src/systems/fmgc/src/flightphase/index.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts
  fbw-a32nx/src/systems/fmgc/src/index.ts
  fbw-a32nx/src/systems/fmgc/src/navigation/LandingSystemSelectionManager.ts
  fbw-a32nx/src/systems/fmgc/src/navigation/NavaidTuner.ts
  fbw-a32nx/src/systems/fmgc/src/navigation/Navigation.ts
  fbw-a32nx/src/systems/fmgc/src/navigation/RequiredPerformance.ts
  fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.tsx
  fbw-common/src/typings/fmgc.d.ts
  fbw-common/src/typings/fs-base-ui/html_ui/JS/common.d.ts
  fbw-common/src/typings/types.d.ts
Labels: QA Tier 2, QA Passed

#8773 chore(a380x): Finish adding checklist items and pseudoFWC logic for ATA 21, 27, 28, 31, 33, and 70 abnormal procedures
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/AbnormalSensed/ata21-22-23.tsx
Labels: A380X

#8849 fix(fms): fix efis overlay/map ref point logic
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/efis-cp.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_EFIS.xml
  fbw-common/src/systems/instruments/src/NavigationDisplay.ts
Labels: QA Tier 1, QA Passed

#8851 feat(fms): complete navaid page
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavaidPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_WaypointPage.js
  fbw-common/src/systems/navdata/client/backends/Msfs/FsTypes.ts
  fbw-common/src/systems/navdata/client/backends/Msfs/Mapping.ts
Labels: QA Tier 1, QA Passed

#8860 ci: Fix GitHub Project action
  .github/workflows/pr-qa-reg.yml
Labels: CI, QA Not Required

#8855 fix(a380x/sd): permanent data area isa delta and weights
  fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx
  fbw-a380x/src/systems/instruments/src/SD/StatusArea.tsx
Labels: QA Not Required

#8861 fix(fms/nd): altitude constraint display on altitude terminated legs
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
  fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/legs/FlightPlanLeg.ts
  fbw-common/src/systems/instruments/src/ND/shared/map/ConstraintsLayer.ts
Labels: QA Tier 1, QA Passed
