Repository flybywiresim/aircraft, pull requests merged in 2025-06, with the labels that each got.

#9840 feat(a32nx): ecam control panel (ecp)
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/docs/a32nx-input-events.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Interior/Inputs/Pedestal_Inputs.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Interior/Pedestal/A32NX_ECP.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/config/a32nx/a320-251n/aircraft_preset_procedures.xml
  fbw-a32nx/src/localization/msfs/en-US.locPak
  fbw-a32nx/src/systems/extras-host/index.ts
  fbw-a32nx/src/systems/extras-host/modules/pushbutton_check/PushbuttonCheck.ts
  fbw-a32nx/src/systems/failures/src/a320.ts
  fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_Core/A32NX_FWC.ts
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts
  fbw-a32nx/src/systems/instruments/src/SD/PagesContainer.tsx
  fbw-a32nx/src/systems/instruments/src/SD/index.tsx
  fbw-a32nx/src/systems/shared/src/publishers/A32NXEcpBusPublisher.ts
  fbw-a32nx/src/systems/shared/src/publishers/A32NXOverheadDiscretePublisher.ts
  fbw-a32nx/src/systems/systems-host/index.ts
  fbw-a32nx/src/systems/systems-host/systems/ECP/Ecp.ts
  fbw-a32nx/src/systems/systems-host/systems/ECP/FakeDmc.ts
  fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts
  fbw-common/src/systems/shared/src/arinc429.ts
  fbw-common/src/systems/shared/src/publishers/Extras/ExtrasSimVarPublisher.ts
Labels: QA Tier 1, QA Passed, A32NX

#10073 feat(fms): add troubleshooting logs for missing navdata
  fbw-a32nx/src/systems/extras-host/modules/flightplan_sync/FlightPlanAsoboSync.ts
  fbw-a32nx/src/systems/fmgc/src/NavigationDatabase.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/test/Database.ts
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts
  fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts
  fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx
  fbw-a380x/src/systems/systems-host/systems/BrakeToVacateDistanceUpdater.ts
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/TroubleshootingPage.tsx
  fbw-common/src/systems/navdata/client/backends/Msfs/FacilityCache.ts
  fbw-common/src/systems/navdata/client/backends/Msfs/Mapping.ts
  fbw-common/src/systems/navdata/client/backends/Msfs/Msfs.ts
  fbw-common/src/systems/navdata/shared/types/ErrorLogger.ts
Labels: QA Tier 1, QA Passed

#10092 feat(a380x/fws): Update normal checklists and harmonize TO memo
  .github/CHANGELOG.md
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/NormalProcedures.tsx
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/index.tsx
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsNormalChecklists.ts
Labels: QA Passed, A380X

#10072 fix(efb): failure listener registration
  fbw-common/src/systems/shared/src/ViewListenerUtils.ts
  fbw-common/src/systems/shared/src/failures/failures-orchestrator.spec.ts
  fbw-common/src/systems/shared/src/failures/failures-orchestrator.ts
  fbw-common/src/systems/shared/src/index.ts
  fbw-common/src/typings/fs-base-ui/html_ui/JS/common.d.ts
Labels: QA Not Required

#10022 feat(a380x/rmp): improve api for hardware users and add standby mode handling
  .github/CHANGELOG.md
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/runway.FLT
  fbw-a380x/src/systems/extras-host/modules/key_interceptor/KeyInterceptor.ts
  fbw-a380x/src/systems/instruments/src/RMP/Pages/VhfCom/VhfComController.ts
  fbw-a380x/src/systems/instruments/src/RMP/Pages/VhfCom/VhfComPage.tsx
  fbw-a380x/src/systems/instruments/src/RMP/Systems/RmpStateController.ts
  fbw-a380x/src/systems/systems-host/systems/Communications/AudioManagementUnit.ts
  fbw-common/src/systems/instruments/src/RMP/RmpUtils.ts
  fbw-common/src/systems/instruments/src/RMP/Systems/VhfComManager.ts
  fbw-common/src/systems/instruments/src/RMP/index.ts
  fbw-common/src/systems/shared/src/ObjectUtils.ts
  fbw-common/src/systems/shared/src/RadioUtils.spec.ts
  fbw-common/src/systems/shared/src/RadioUtils.ts
  fbw-common/src/systems/shared/src/SimVarUtils.ts
  fbw-common/src/systems/shared/src/index.ts
  fbw-common/src/typings/fs-base-ui/html_ui/JS/simvar.d.ts
Labels: RMP, A380X

#10123 fix(a380x/rmp): amu not reading rmp state
  fbw-a380x/src/systems/systems-host/systems/Communications/AudioManagementUnit.ts
Labels: QA Tier 1, QA Passed

#10122 fix(pfd): metric alt dead
  fbw-a32nx/src/systems/instruments/src/PFD/AltitudeIndicator.tsx
  fbw-a380x/src/systems/instruments/src/PFD/AltitudeIndicator.tsx
Labels: QA Not Required

#10131 fix(a380x/mfd): fix mfd tab navigator outer edge color styling
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/UiWidgets/TopTabNavigator.tsx
Labels: QA Passed

#10135 fix(a380x): fix c-chord when baro alti changes in std
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsFlightPhases.ts
Labels: QA Tier 1, QA Passed

#10125 fix(a380x/fmc): use efob to compute step alts
  .github/CHANGELOG.md
  fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts
  fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcInterface.ts
  fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnVertRev.tsx
Labels: QA Tier 1, QA Passed

#10076 feat(a32nx/sd): Add flashing to AUTO BRK element WHEEL SD
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/SD/Common/CommonStyles.scss
  fbw-a32nx/src/systems/instruments/src/SD/Common/animations.scss
  fbw-a32nx/src/systems/instruments/src/SD/Pages/Wheel/Wheel.tsx
Labels: QA Passed, A32NX

#10109 fix(a32nx/fms): Change GA PERF speeds to match APPR PERF speeds
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_PerformancePage.ts
Labels: QA Passed

#10058 feat(a380x/mfd): add RETURN button to DATA/AIRPORT page
  .github/CHANGELOG.md
  fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/DATA/MfdFmsDataAirport.tsx
Labels: QA Passed, QA Ready to Test

#10144 chore: treat gltf as binary
  .gitattributes
Labels: QA Not Required

#10145 fix(efb): rename us units option to reflect reality
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/AircraftOptionsPinProgramsPage.tsx
Labels: QA Tier 1, QA Passed

#10106 fix(atsu): use fms flight number
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/systems/atsu/fmsclient/src/index.ts
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts
  fbw-a32nx/src/systems/shared/src/publishers/A32NXFmBusPublisher.ts
  fbw-common/src/systems/shared/src/arinc429.ts
Labels: QA Tier 1, QA Passed, A32NX

#10134 build: allow USE_4K_TEXTURES to be defined by environment
  .github/Contributing.md
  scripts/build.sh
  scripts/build_a380x.sh
  scripts/dev-env/run-local.cmd
  scripts/dev-env/run.cmd
Labels: QA Not Required

#10156 fix(A32X/MCDU): use NXUnits on arrival airport runway lengths
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableArrivalsPage.ts
Labels: QA Passed

#10172 fix(a32nx/fms): fix automatic cruise temperature calculation according to isa
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy/LegacyFmsPageInterface.ts
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_InitPage.ts
Labels: QA Passed

#10175 fix(fms): treat runways as fixes
  fbw-a32nx/src/systems/fmgc/src/flightplanning/WaypointEntryUtils.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/legs/FlightPlanLeg.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/waypoints/WaypointFactory.ts
  fbw-common/src/systems/navdata/client/backends/Msfs/Mapping.ts
  fbw-common/src/systems/navdata/shared/types/BaseFix.ts
  fbw-common/src/systems/navdata/shared/types/Runway.ts
  fbw-common/src/systems/navdata/shared/types/Waypoint.ts
Labels: QA Passed

#10127 chore: update Rust dependencies
  Cargo.lock
  Cargo.toml
  fbw-a32nx/src/wasm/systems/a320_hydraulic_simulation_graphs/Cargo.toml
  fbw-a32nx/src/wasm/systems/a320_systems/Cargo.toml
  fbw-a32nx/src/wasm/systems/a320_systems/src/payload/test.rs
  fbw-a32nx/src/wasm/systems/a320_systems_wasm/Cargo.toml
  fbw-a380x/src/wasm/systems/a380_systems/Cargo.toml
  fbw-a380x/src/wasm/systems/a380_systems_wasm/Cargo.toml
  fbw-common/src/wasm/systems/systems/Cargo.toml
  fbw-common/src/wasm/systems/systems/src/apu/mod.rs
  fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
  fbw-common/src/wasm/systems/systems/src/shared/arinc429.rs
  fbw-common/src/wasm/systems/systems/src/shared/arinc825.rs
  fbw-common/src/wasm/systems/systems/src/shared/random.rs
  fbw-common/src/wasm/systems/systems/src/simulation/test.rs
  fbw-common/src/wasm/systems/systems_wasm/Cargo.toml
Labels: QA Passed

#10184 fix(a32nx/fms): fix incorrect TOO STEEP PATH AHEAD message logic
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/VerticalProfileManager.ts
Labels: QA Not Required

#10188 docs: add changelog guidance
  .github/CHANGELOG.md
Labels: QA Not Required

#10142 feat(hyd): split slats and flaps in individual surfaces
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts
  fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
  fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/flaps_computer.rs
  fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs
  fbw-a380x/docs/a380-simvars.md
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts
  fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/flaps_computer.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
  fbw-common/src/wasm/systems/systems/src/hydraulic/flap_slat.rs
  fbw-common/src/wasm/systems/systems/src/shared/mod.rs
Labels: QA Passed, A32NX, A380X

#10097 feat(a32nx/fws): improve various AUTO FLT warning logics
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
  fbw-a32nx/src/systems/instruments/src/Common/EWDMessages.tsx
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_Core/A32NX_FWC.ts
  fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/providers/PseudoFwcPublisher.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/DigitalAltitudeReadout.tsx
  fbw-a32nx/src/systems/instruments/src/PFD/PseudoDmc.ts
  fbw-a32nx/src/systems/instruments/src/PFD/style.scss
  fbw-a32nx/src/systems/shared/src/publishers/A32NXDisplayManagementPublisher.ts
  fbw-a32nx/src/systems/systems-host/systems/FWC/FwsSoundManager.ts
  fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts
Labels: QA Passed
