Repository flybywiresim/aircraft, pull requests merged in 2025-04, with the labels that each got.

#9967 feat: notifications first step + enhanced efb experience
  .eslintignore
  fbw-a32nx/src/systems/instruments/src/EFB/index.tsx
  fbw-a380x/mach.config.js
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg
  fbw-a380x/src/systems/instruments/src/EFB/index.tsx
  fbw-a380x/src/systems/instruments/src/OITlegacy/OitLegacy.tsx
  fbw-a380x/src/systems/tsconfig.json
  fbw-a380x/src/systems/ui/README.md
  fbw-a380x/src/systems/ui/buildSrc/directories.mjs
  fbw-a380x/src/systems/ui/buildSrc/igniter/tasks.mjs
  fbw-a380x/src/systems/ui/src/.eslintrc
  fbw-a380x/src/systems/ui/src/Notifications/Notification.scss
  fbw-a380x/src/systems/ui/src/Notifications/config.json
  fbw-a380x/src/systems/ui/src/Notifications/instrument.tsx
  fbw-a380x/src/systems/ui/src/Notifications/tsconfig.json
  fbw-a380x/src/systems/ui/src/index.scss
  fbw-a380x/src/systems/ui/src/util.js
  fbw-a380x/src/systems/ui/tsconfig.json
  fbw-common/src/systems/instruments/src/EFB/AircraftContext.ts
  fbw-common/src/systems/instruments/src/EFB/Settings/Pages/RealismPage.tsx
  fbw-common/src/systems/ui/src/Notifications/Notifications.tsx
  fbw-common/src/systems/ui/src/Notifications/index.ts
  fbw-common/src/systems/ui/src/Notifications/style.scss
  fbw-common/src/systems/ui/src/Notifications/tsconfig.json
  igniter.config.mjs
Labels: QA Not Required, A380X

#9921 fix(a32nx/nd): remove waypoint boxing
  fbw-a380x/src/systems/instruments/src/ND/instrument.tsx
  fbw-common/src/systems/instruments/src/ND/ND.tsx
  fbw-common/src/systems/instruments/src/ND/shared/map/CanvasMap.tsx
  fbw-common/src/systems/instruments/src/ND/shared/map/WaypointLayer.ts
  fbw-common/src/systems/instruments/src/ND/types/MapOptions.ts
Labels: QA Tier 1, QA Passed

#9958 fix: restore pop ups in 2024
  fbw-a32nx/src/systems/extras-host/index.ts
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A320_Neo_CDU_MainDisplay.ts
  fbw-a32nx/src/systems/shared/src/NxNotif.ts
  fbw-a380x/src/systems/extras-host/index.ts
  fbw-common/src/systems/shared/src/TelexCheck.ts
  fbw-common/src/systems/shared/src/index.ts
  fbw-common/src/systems/shared/src/popup.ts
  fbw-common/src/typings/fs-base-ui/html_ui/JS/common.d.ts
Labels: QA Ready to Test, MSFS2024

#9883 fix(a380x/fmc): tmpy state getting descyned on FIX INFO
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/fmgc/src/flightplanning/ObservableFlightPlanManager.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/ObservableFlightPlan.ts
  fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnFixInfo.tsx
Labels: QA Tier 1

#9924 fix(a380x/oit): fix OIT brightness being incorrectly connected to RMP 2 and RMP 3 screen brightness
  .github/CHANGELOG.md
  fbw-a380x/src/base/flybywire-aircraft-a380-842/ModelBehaviorDefs/A380X/id_definitions.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
  fbw-a380x/src/systems/extras-host/modules/light_sync/LightSync.ts
  fbw-a380x/src/systems/instruments/src/OIT/OitDisplayUnit.tsx
  fbw-a380x/src/systems/instruments/src/OIT/OitSimvarPublisher.tsx
Labels: QA Passed

#9938 feat(efb): harmonize takeoff and landing performance calculators
  .github/CHANGELOG.md
  fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json
  fbw-common/src/systems/instruments/src/EFB/Performance/Data/Utils.ts
  fbw-common/src/systems/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx
  fbw-common/src/systems/instruments/src/EFB/Performance/Widgets/TakeoffWidget.tsx
  fbw-common/src/systems/instruments/src/EFB/Store/features/performance.ts
  fbw-common/src/systems/instruments/src/EFB/UtilComponents/Form/SimpleInput/SimpleInput.tsx
Labels: QA Passed

#9994 fix(a380x/mfd): Update tab bar layout with overlapping tabs
  .github/CHANGELOG.md
  fbw-a380x/src/systems/instruments/src/MFD/MfdPageDirectory.tsx
  fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsFuelLoad.tsx
  fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsInit.tsx
  fbw-a380x/src/systems/instruments/src/MFD/pages/common/FmsHeader.tsx
  fbw-a380x/src/systems/instruments/src/MFD/pages/common/widget-style.scss
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/UiWidgets/TopTabNavigator.tsx
Labels: QA Not Required, A380X, MFD

#9860 fix(a32nx/fms): fix preselected cruise speed/mach value showing in the descent phase
  fbw-a32nx/docs/a320-simvars.md
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts
  fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts
Labels: QA Passed, QA Ready to Test, A32NX

#9983 fix(a380x/extras): set rmp brightness correctly
  fbw-a380x/src/systems/extras-host/modules/light_sync/LightSync.ts
Labels: QA Tier 1, QA Passed

#9980 fix(a380x/sd): BLEED: crossbleed indications, ENG BLEED OFF fault; APU BLEED pressure for engine start
  .github/CHANGELOG.md
  fbw-a32nx/docs/a320-simvars.md
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/Climb.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/approach.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/apron.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/cruise.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/final.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/hangar.flt
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_Misc.xml
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/runway.FLT
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/taxi.flt
  fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/AbnormalSensed/ata21-22-23.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/BleedPage.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedApu.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedCrossbleed.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedGnd.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedPack.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Engine/elements/StartValve.tsx
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsAbnormalSensed.ts
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts
  fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs
  fbw-common/src/wasm/systems/systems/src/apu/pw980.rs
Labels: Displays, QA Passed, QA A380 Only, A380X

#9803 fix(elec): fix A380 ground servicing mode
  .github/CHANGELOG.md
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/alternating_current.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/direct_current.rs
  fbw-a380x/src/wasm/systems/a380_systems/src/electrical/mod.rs
  fbw-common/src/wasm/systems/systems/src/electrical/battery_charge_rectifier_unit.rs
Labels: Electrical, QA Passed, A380X

#9984 fix(a380x/ecam): improve STROBE LT OFF memo behaviour
  .github/CHANGELOG.md
  fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsMemos.ts
Labels: QA Tier 1, QA Passed, A380X

#10013 fix(fms): fix predictions with speed constraint on final approach
  fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/ApproachPathBuilder.ts
Labels: QA Tier 1, FMS, QA Passed

#10026 docs(a32nx): add blank annunciator lvar
  fbw-a32nx/docs/a320-simvars.md
Labels: QA Not Required

#10027 fix: unnecessary error
  fbw-common/src/systems/navdata/client/backends/Msfs/NearbyFacilityCache.ts
Labels: QA Not Required

#10025 fix(a32nx/eis): w glyph
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Fonts/fbw-a32nx/ECAMFontRegular.ttf
  fbw-a32nx/src/fonts/ECAMFontRegular_Source.sfd
Labels: QA Not Required, A32NX

#10024 fix(a32nx): add correct typing for simbrief navlog
  fbw-a32nx/src/systems/fmgc/src/flightplanning/uplink/CoRouteUplinkAdapter.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/uplink/SimBriefUplinkAdapter.ts
  fbw-common/src/systems/instruments/src/EFB/Apis/Simbrief/simbriefInterface.ts
Labels: QA Not Required

#10023 fix(a32nx/rmp): don't de-tune atc during runway spawn
  .github/CHANGELOG.md
  fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT
Labels: QA Not Required, A32NX

#10009 fix(mfd/init): TRIP WIND entry not accepting input
  fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsInit.tsx
Labels: QA Tier 1, QA Passed, QA A380 Only

#9845 feat(a380x/mfd): Vertical Revision speed limit modification
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/fmgc/src/flightplanning/FlightPlanInterface.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/FlightPlanService.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/BaseFlightPlan.ts
  fbw-a32nx/src/systems/fmgc/src/flightplanning/rpc/FlightPlanRpcClient.ts
  fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts
  fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_VerticalRevisionPage.ts
  fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts
  fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.ts
  fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnVertRev.scss
  fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnVertRev.tsx
  fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx
Labels: QA Tier 1, QA Passed, A380X

#10039 fix(a32nx/fwc): pred w/s off memo to conf colour
  .github/CHANGELOG.md
  fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts
Labels: QA Not Required, A32NX

#9956 feat(a380x/sd): Add video page with 'not avail' text
  .github/CHANGELOG.md
  fbw-a380x/src/systems/instruments/src/SD/Pages/Video/VideoPage.tsx
  fbw-a380x/src/systems/instruments/src/SD/Pages/Video/config.json
  fbw-a380x/src/systems/instruments/src/SD/SystemDisplay.tsx
Labels: QA Passed, QA Ready to Test, QA A380 Only, A380X

#10012 fix: stuck popup (again)
  fbw-common/src/systems/shared/src/FbwAircraftSentryClient.ts
  fbw-common/src/systems/shared/src/popup.ts
Labels: QA Tier 1, QA Passed, A32NX, MSFS2024

#10019 fix(a380x): apu fire button template simvar name
  fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
Labels: QA Passed

#9892 chore: remove key event workaround
  fbw-common/src/wasm/systems/systems_wasm/src/electrical.rs
Labels: MSFS2024
